### ISSUE TITLE
兄弟，你这个demo都跑不起来啊，看看啥情况呢

### ISSUE THREAD

**Issue by FreAirLy** [fluttify-project/amap_map_fluttify#1]

**Comment by yohom** [comment]
贴个图啊哥

**Comment by FreAirLy** [comment]
好像是 ndk 特性问题 多增加几个就可以了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 小山 <notifications@github.com&gt;
发送时间: 2019年10月22日 17:00
收件人: fluttify-project/amap_map_fluttify <amap_map_fluttify@noreply.github.com&gt;
抄送: FreAirLy <245681616@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[fluttify-project/amap_map_fluttify] 兄弟，你这个demo都跑不起来啊，看看啥情况呢 (#1)




贴个图啊哥
