### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by samuelhuahui** [fluttify-project/amap_map_fluttify#10]
D:\Sdk\ndk-bundle\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\bin\aarch64-linux-android-strip: D:\flutter\cloud_location_app\build\amap_map_fluttify\intermediates\transforms\stripDebugSymbol\debug\0\lib\arm64-v8a\libAMapSDK_MAP_v6_9_2.so: section `.plt' can't be allocated in segment 0
LOAD: .note.gnu.build-id .hash .dynsym .dynstr .gnu.version .gnu.version_r .rela.dyn .rela.plt .plt

**Comment by yohom** [comment]
这个不用管，能打包就行
