### ISSUE TITLE
项目拉下来运行报错

### ISSUE THREAD

**Issue by winnxiegang** [fluttify-project/amap_map_fluttify#101]
**插件版本**
  flutter:
    sdk: flutter
  foundation_fluttify: ^0.2.2+2
  amap_core_fluttify: ^0.2.3
  url_launcher: ^5.2.7
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
Compiler message:
/E:/sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_advanced_networkimage-0.6.0/lib/src/provider/flutter_advanced_networkimage.dart:159:55: Error: Type 'DecoderCallback' not found.
  ImageStreamCompleter load(AdvancedNetworkImage key, DecoderCallback decode) {
                                                      ^^^^^^^^^^^^^^^
/E:/sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_advanced_networkimage-0.6.0/lib/src/provider/flutter_advanced_networkimage.dart:171:33: Error: Type 'DecoderCallback' not found.
      AdvancedNetworkImage key, DecoderCallback decode) async {
                                ^^^^^^^^^^^^^^^
/E:/sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_advanced_networkimage-0.6.0/lib/src/provider/flutter_advanced_networkimage.dart:159:24: Error: The method 'AdvancedNetworkImage.load' has more required arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(AdvancedNetworkImage key, DecoderCallback decode) {
                       ^
/E:/sdk/flutter/packages/flutter/lib/src/painting/image_provider.dart:383:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key);
                       ^
/E:/sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_advanced_networkimage-0.6.0/lib/src/provider/flutter_advanced_networkimage.dart:159:55: Error: 'DecoderCallback' isn't a type.
  ImageStreamCompleter load(AdvancedNetworkImage key, DecoderCallback decode) {
                                                      ^^^^^^^^^^^^^^^
/E:/sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_advanced_networkimage-0.6.0/lib/src/provider/flutter_advanced_networkimage.dart:171:33: Error: 'DecoderCallback' isn't a type.
      AdvancedNetworkImage key, DecoderCallback decode) async {
                                ^^^^^^^^^^^^^^^
Compiler failed on E:\Documents\flutterTest\amap_map_fluttify-0.11.0+a918944\example\lib\main.dart

FAILURE: Build failed with an exception.

* Where:
Script 'E:\sdk\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 765

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugArm64'.
> Process 'command 'E:\sdk\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Finished with error: Gradle task assembleDebug failed with exit code 1

**复现步骤**
克隆下载运行 demo出现。另外amap_map_fluttify: ^0.11.0+a918944项目依赖报错，amap_map_fluttify:  0.10.2+a1a3fff 项目依赖运行可以
**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
`0.11.0`开始flutter环境改为`1.12.13`，如果要使用旧版本的flutter，就使用`0.10`及以下版本。
