### ISSUE TITLE
调用clearMarkers方法会将用户定位点删掉

### ISSUE THREAD

**Issue by q869939686** [fluttify-project/amap_map_fluttify#102]
**插件版本**
0.11
**遇到bug的平台(Android/iOS)**
安卓
**描述bug**

调用await _controller?.clearMarkers();方法之后，showMyLocation方法定位的箭头会消失，只剩下圆圈

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
这个应该是高德地图默认的行为，目前你可以在清除marker后再调用一次定位方法来重新显示一下定位点。

**Comment by q869939686** [comment]
能不能在调用showMyLocation的时候不要强制屏幕移动过去？

**Comment by yohom** [comment]
你开个新的issue吧
