### ISSUE TITLE
调用showMyLocation方法的时候会强制移动屏幕

### ISSUE THREAD

**Issue by q869939686** [fluttify-project/amap_map_fluttify#104]
**插件版本**
0.10.5
**遇到bug的平台(Android/iOS)**
安卓
**描述bug**
能不能在调用showMyLocation的时候不要强制屏幕移动过去？
**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
android端有比较多的定位模式 参考 https://a.amap.com/lbs/static/unzip/Android_Map_Doc/3D/com/amap/api/maps/model/MyLocationStyle.html ，但是ios端只有三种模式，参考 http://a.amap.com/lbs/static/unzip/iOS_Map_Doc/AMap_iOS_API_Doc_3D/_m_a_map_view_8h.html#abd5906b49b1c430e6b3b5cc6b66e0fa0 。我统一起来也比较困难，暂时不知道该怎么处理会比较好。

**Comment by yohom** [comment]
目前(0.17.18)的showMyLocation方法的mode参数的Locate枚举，行为是只显示定位，但不把地图移动到定位点，符合这个issue提出的需求。
