### ISSUE TITLE
地理围栏

### ISSUE THREAD

**Issue by zhengzhuang96** [fluttify-project/amap_map_fluttify#105]
**功能描述**
https://lbs.amap.com/api/webservice/guide/api/geofence_service
**Native端对应字段/方法**
高德地图地理围栏功能

**Comment by zhengzhuang95** [comment]
1:判断坐标是否在围栏内
2:自定义围栏填充色

**Comment by yohom** [comment]
1. 判断坐标是否在围栏内，`Polygon`添加了`contains`方法判断。
2. `fillColor`可以指定多边形的填充色。

**Comment by zhengzhuang95** [comment]
> 1. 判断坐标是否在围栏内，`Polygon`添加了`contains`方法判断。
> 2. `fillColor`可以指定同轴的填充色。
