### ISSUE TITLE
现在是否支持  瓦片图层呢 ？比如使用谷歌卫星图

### ISSUE THREAD

**Issue by yuefeng007** [fluttify-project/amap_map_fluttify#107]
**功能描述**

**Native端对应字段/方法**
现在是否支持  瓦片图层呢 ？比如使用谷歌卫星图，如果不支持  最近有计划支持吗？

**Comment by yohom** [comment]
瓦片图层是指2D地图吗

**Comment by yuefeng007** [comment]
对  2d 的 ，我想使用谷歌卫星图层

**Comment by yuefeng007** [comment]
在web中 我可以这样配置，加载自定义2d图层

`const googleLayer = new AMap.TileLayer({
	  getTileUrl: 'http://mt{1,2,3,0}.google.cn/vt/lyrs=s&hl=zh-CN&gl=cn&x=[x]&y=[y]&z=[z]&s=Galile'
	});
       new AMap.Map('container', {
        ***
        layers: [googleLayer,]
      });
    })`

**Comment by yohom** [comment]
2D地图是另外一个SDK了，暂时没有支持计划。如果你感兴趣并愿意开发插件，我可以用Fluttify为你生成插件项目，并把你设置成维护者。

**Comment by yuefeng007** [comment]
比如在web中，可以这样加载谷歌卫星图层。

`const googleLayer = new AMap.TileLayer({
	  getTileUrl: 'http://mt{1,2,3,0}.google.cn/vt/lyrs=s&hl=zh-CN&gl=cn&x=[x]&y=[y]&z=[z]&s=Galile'
	});
      var map = new AMap.Map('container', {
        resizeEnable: true,
        center: [129.47, 44.35],
        zoom: 14,
        layers: [googleLayer,]
      });
    })`

**Comment by yohom** [comment]
如果你只是想要卫星图的话，有试过切换图层接口吗？

**Comment by yuefeng007** [comment]
感觉应该可行，我去试试！

**Comment by yohom** [comment]
老铁，切换卫星图层能满足你的需求吗？可以的话我就关闭issue了。 @yuefeng007

**Comment by yuefeng007** [comment]
切换卫星图不行哎，  高德本身的卫星图片  清晰度不够用啊。

**Comment by yuefeng007** [comment]
只有 谷歌的卫星图 资源  可以满足清晰度需求

**Comment by yuefeng007** [comment]
我是否可以在源码里直接更改 图层的 api接口呢?我想换成  谷歌 这个 'http://mt{1,2,3,0}.google.cn/vt/lyrs=s&hl=zh-CN&gl=cn&x=[x]&y=[y]&z=[z]&s=Galile'

**Comment by yohom** [comment]
你说的`在源码里直接更改 图层的 api接口`，高德官网有没有对应的api？

**Comment by yuefeng007** [comment]
搞定了  多谢
