### ISSUE TITLE
0.13版本，遇见Unhandled Exception: MissingPluginException(No implementation found for method PlatformFactory::createCLLocationCoordinate2D on channel com.fluttify/foundation_method)

### ISSUE THREAD

**Issue by beydeng** [fluttify-project/amap_map_fluttify#108]
还有 
Unhandled Exception: MissingPluginException(No implementation found for method PlatformFactory::release on channel com.fluttify/foundation_method

**Comment by yohom** [comment]
建议app杀掉之后重新试下，这个应该不会出现的。要么就`flutter packages upgrade; flutter packages get`执行以下。

**Comment by JeasonL** [comment]
Unhandled Exception: MissingPluginException(No implementation found for method PlatformFactory::createCLLocationCoordinate2D on channel com.fluttify/foundation_method)
flutter packages upgrade、flutter packages get 、卸载重新安装App 之后也不行；
另外addPolygon，加载不到多边形
flutter版本：1.13.4-pre.11
amap_map_fluttify版本：^0.13.1+d44bb02
系统：iOS

**Comment by yohom** [comment]
`foundation_fluttify`的0.2.7+1版本修复了，`flutter packages upgrade`更新一下依赖.
