### ISSUE TITLE
addPolygon无法加载多边形

### ISSUE THREAD

**Issue by JeasonL** [fluttify-project/amap_map_fluttify#109]
**插件版本**
0.11.0+a918944

**遇到bug的平台(Android/iOS)**
iOS

**描述bug**
直接使用draw_polygon.screen.dart也无法正常显示多边形

**Comment by yohom** [comment]
跟 #108 一样的原因，已经在`foundation_fluttify`修复，更新一下版本。

**Comment by JeasonL** [comment]
#108 问题可以了，但是仍然无法显示多边形
**log:**
flutter: fluttify-dart: MAPolygon::polygonWithCoordinates(['count':4])
flutter: fluttify-dart: MAMapView@1::addOverlay([])
暂不支持有返回值的回调方法
flutter: fluttify-dart-callback: mapViewDidAddOverlayRenderers([])
flutter: mapViewDidAddOverlayRenderers::kNativeObjectPool: {AMapServices{refId: 10781711008}, MAUserLocationRepresentation{refId: 10789517504}, MAPolygon{refId: 10753699200}, MAMapView{refId: 4410120192}, NSObject{refId: 4714164128}, MAPolygon{refId: 10750008320}, NSObject{refId: 4714336320}, MAPolygon{refId: 10750514432}, NSObject{refId: 4714435280}}
**方法应该调用成功，但是没显示多边形**
