### ISSUE TITLE
添加 显示交通状态的图层

### ISSUE THREAD

**Issue by beydeng** [fluttify-project/amap_map_fluttify#110]
安卓     aMap.setTrafficEnabled(true);// 显示实时交通状况
IOS     self.mapView.showTraffic = YES;

**Comment by yohom** [comment]
https://github.com/fluttify-project/amap_map_fluttify/blob/ce382dbd17c2f470f9932b4b72d5107c816f9e79/lib/src/dart/amap_controller.dart#L292

老铁你先看下`AmapController`的接口啊
