### ISSUE TITLE
设置中心点报空指针

### ISSUE THREAD

**Issue by cccchelly** [fluttify-project/amap_map_fluttify#111]
设置中心点代码如下：
              controller.setCenterCoordinate(lat, lng);
报错：Unhandled Exception: PlatformException(Attempt to invoke virtual method 'void com.amap.api.maps.AMap.animateCamera(com.amap.api.maps.CameraUpdate)' on a null object reference, null, null)

**Comment by Wood-Water-Peng** [comment]
同问，我也出现了这个问题，兄弟怎么解决的啊

**Comment by cccchelly** [comment]
> 同问，我也出现了这个问题，兄弟怎么解决的啊

还没有解决，在等作者回复。我这边迂回了一下，我发现设置初始点是没问题的，初始点就是中心点，而且要换中心点的时候setstate重绘一下把这个要设置的点设置成初始点，能达到这个效果

**Comment by YaoShuwei** [comment]
同样的问题，希望作者能尽快解决
