### ISSUE TITLE
卫星图没有效果

### ISSUE THREAD

**Issue by gelonggld** [fluttify-project/amap_map_fluttify#116]
**amap_all_fluttify: ^0.9.0**

**遇到bug的平台(Android)**

**配置卫星图，还是显示的标准地图**

这是配置代码
```
 _map2d() => AmapView(
    mapType: MapType.Standard,
    showZoomControl: false, ///缩放
    showCompass: false, ///指南针
    showScaleControl: false, ///比例尺
    zoomGesturesEnabled: true, ///缩放
    scrollGesturesEnabled: true, ///滚动
    rotateGestureEnabled: true, ///旋转
    tiltGestureEnabled: false, ///倾斜
    zoomLevel: 10, ///缩放级别
    centerCoordinate: LatLng(39,116), ///中心点坐标

    onMapCreated: (controller) async {
      var permissionResults = await PermissionHandler().requestPermissions([PermissionGroup.location]);
      if(permissionResults[PermissionGroup.location] == PermissionStatus.granted) {
        return true;
      }else {
        showToast('需要定位权限');
        return false;
      }
    },
  );
```

!(https://s2.ax1x.com/2019/12/19/QqrX1H.md.jpg)

我没有使用idea 使用的是android studio
**
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.476], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\mobile\flutter
    • Framework revision 27321ebbad (8 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\mobile\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = D:\mobile\android-sdk
    • Java binary at: D:\mobile\studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at D:\mobile\studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at D:\tools\IntelliJ IDEA 2019.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • MI CC 9e • b580f4e6c631 • android-arm64 • Android 9 (API 28)

**

**Comment by yuefeng007** [comment]
有个补救方法

**Comment by gelonggld** [comment]
我试了下，地图创建完成回调就可以正常显示了。
