### ISSUE TITLE
是否支持限制范围，比如只显示某一个省市 

### ISSUE THREAD

**Issue by yuefeng007** [fluttify-project/amap_map_fluttify#117]
**功能描述**
是否支持限制范围，比如只显示某一个省市
**Native端对应字段/方法**

**Comment by yohom** [comment]
提供一下原生SDK对应的api。

**Comment by yuefeng007** [comment]
http://a.amap.com/lbs/static/unzip/Android_Map_Doc/index.html?3D/com/amap/api/maps/CameraUpdateFactory.html

**Comment by yuefeng007** [comment]
从地图 SDK V4.1.0 起新增了设置地图显示范围的方法，手机屏幕仅显示设定的地图范围，例如：希望设置仅显示北京市区地图，可使用此功能。

注意：如果限制了地图显示范围，地图旋转手势将会失效。

调用示例如下:

Java
LatLng southwestLatLng = new LatLng(33.789925, 104.838326);
LatLng northeastLatLng = new LatLng(38.740688, 114.647472);
LatLngBounds latLngBounds = new LatLngBounds(southwestLatLng, northeastLatLng);
aMap.setMapStatusLimits(latLngBounds);

**Comment by yuefeng007** [comment]
https://lbs.amap.com/api/android-sdk/guide/interaction-with-map/method-interaction/?sug_index=0

**Comment by yohom** [comment]
这个功能应该已经实现了，看下[CHANGELOG](https://github.com/fluttify-project/amap_map_fluttify/blob/master/CHANGELOG.md#0161), 方法名字应该和`setMapStatusLimits`类似，你找一找.
