### ISSUE TITLE
地图加载时会闪一下黑屏

### ISSUE THREAD

**Issue by yanqiqi1996** [fluttify-project/amap_map_fluttify#12]
**插件版本**  最新版

**描述bug**  地图加载的前面会闪一下黑屏

**flutter doctor**
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.39.2)
[✓] Connected device (2 available)

**Comment by yohom** [comment]
这个是`PlatformView`的bug，相关issue https://github.com/flutter/flutter/issues/40568, https://github.com/flutter/flutter/issues/40229, https://github.com/flutter/flutter/issues/26771

**Comment by yanqiqi1996** [comment]
![WX20191029-151527](https://user-images.githubusercontent.com/31203049/67745373-0a1caf80-fa5f-11e9-83d3-221c7eca3713.png)
暂时用了一个Offsatge 遮住了黑屏

**Comment by yohom** [comment]
这个issue不是fluttify的问题，我先关掉了。
