### ISSUE TITLE
希望能增加，监听手势缩放获得动图缩放比例的功能

### ISSUE THREAD

**Issue by houyongfeng1984** [fluttify-project/amap_map_fluttify#122]
**功能描述**
监听手势缩放获得动图缩放比例的功能
**Native端对应字段/方法**

**Comment by yohom** [comment]
0.16.2 增加了获取当前缩放等级的方法`getZoomLevel`

**Comment by houyongfeng1984** [comment]
非常感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"小山"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月25日(星期三) 中午1:36
收件人:&nbsp;"fluttify-project/amap_map_fluttify"<amap_map_fluttify@noreply.github.com&gt;;
抄送:&nbsp;"登顶珠峰"<283229485@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fluttify-project/amap_map_fluttify] 希望能增加，监听手势缩放获得动图缩放比例的功能 (#122)




0.16.2 增加了获取当前缩放等级的方法getZoomLevel

**Comment by houyongfeng1984** [comment]
大佬，最好能有监听地图缩放的事件，目前我用flutter的Listener去监听滑动 ------------------ 原始邮件 ------------------
发件人: "小山"<notifications@github.com>
发送时间: 2019年12月25日(星期三) 中午1:36
收件人: "fluttify-project/amap_map_fluttify"<amap_map_fluttify@noreply.github.com>;
抄送: "houyongfeng1984"<283229485@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [fluttify-project/amap_map_fluttify] 希望能增加，监听手势缩放获得动图缩放比例的功能 (#122)



0.16.2 增加了获取当前缩放等级的方法getZoomLevel
 
&mdash;

**Comment by yohom** [comment]
我看了下android和ios的api，比较尴尬，android这边是当地图缩放和移动的时候会回调`onCameraChange`方法，ios那边移动的时候回调的是`mapViewMapDidMoveByUser`，缩放的时候回调的是`mapViewMapDidZoomByUser`，这样子就比较难搞了。

**Comment by houyongfeng1984** [comment]
目前我在地图上套了Listener组件监听手势滑动，间接实现了。谢谢，大佬的插件非常好用------------------ 原始邮件 ------------------
发件人: "小山"<notifications@github.com>
发送时间: 2019年12月27日(星期五) 下午4:19
收件人: "fluttify-project/amap_map_fluttify"<amap_map_fluttify@noreply.github.com>;
抄送: "houyongfeng1984"<283229485@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [fluttify-project/amap_map_fluttify] 希望能增加，监听手势缩放获得动图缩放比例的功能 (#122)



我看了下android和ios的api，比较尴尬，android这边是当地图缩放和移动的时候会回调onCameraChange方法，ios那边移动的时候回调的是mapViewMapDidMoveByUser，缩放的时候回调的是mapViewMapDidZoomByUser，这样子就比较难搞了。
 
&mdash;

**Comment by houyongfeng1984** [comment]
大神您好！
&nbsp; &nbsp; 我在地图上添加标记的时候一直报空指针，
Attempt to invoke virtual method 'com.amap.api.maps.AMap&nbsp;com_amap_api_maps_AMap.addMarker &nbsp;on a null object reference, null, null)
&nbsp;请问这个是什么原因造成的？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"小山"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月27日(星期五) 下午4:19
收件人:&nbsp;"fluttify-project/amap_map_fluttify"<amap_map_fluttify@noreply.github.com&gt;;
抄送:&nbsp;"登顶珠峰"<283229485@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fluttify-project/amap_map_fluttify] 希望能增加，监听手势缩放获得动图缩放比例的功能 (#122)




我看了下android和ios的api，比较尴尬，android这边是当地图缩放和移动的时候会回调onCameraChange方法，ios那边移动的时候回调的是mapViewMapDidMoveByUser，缩放的时候回调的是mapViewMapDidZoomByUser，这样子就比较难搞了。

**Comment by yohom** [comment]
预计在iOS端合并`mapViewMapDidMoveByUser`和`mapViewMapDidZoomByUser`两个回调，以达到android端`onCameraChange`回调一样的效果。

**Comment by yohom** [comment]
0.17.7版本，setMapMoveListener方法android和ios都能够监听到缩放级别的变化了。

**Comment by maomao1020** [comment]
onMapMoveEnd: (MapMove move) async {

                        print('移动后的维度${move.coordinate}');
                        print('比例${move.zoom}');
                        _zoom   = move.zoom;
                       
                        setState(() {

                        });
                      }

获取不到移动后的经纬度
