### ISSUE TITLE
您好，我遇到了reload时会 Trying to create an already created platform view。

### ISSUE THREAD

**Issue by cn-Meepo** [fluttify-project/amap_map_fluttify#125]
**插件版本**
amap_all_fluttify: ^0.9.0
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
我在热重载的时候会偶发Trying to create an already created platform view
**复现步骤**
编译完成后热重载R
**期望行为**

**截图**
![image](https://user-images.githubusercontent.com/28797329/71437262-d2af4400-272b-11ea-978c-634bef7c5bd4.png)

**flutter doctor**
D:\project\juant_base>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.14393], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\java\flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\java\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\java\android-sdk
    • Java binary at: C:\Users\meepo\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\meepo\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Users\meepo\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\193.5662.53
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7221

[√] Connected device (1 available)
    • MI 6 • bc840644 • android-arm64 • Android 9 (API 28)

• No issues found!

谢谢！！！

**Comment by 972223177** [comment]
老哥最后怎么样了，一样的问题。还不止这种情况。比如将map放在第二个页面，与第一个页面重复进入退出，也会出现这样情况

**Comment by cn-Meepo** [comment]
@972223177 这问题不只是高德地图，谷歌地图也一样，前几周提交flutter官方了，还没提供如何解决

**Comment by 972223177** [comment]
好叻

**Comment by cn-Meepo** [comment]
@972223177 https://github.com/flutter/flutter/issues/45695#issuecomment-574288386

**Comment by 972223177** [comment]
谢谢

**Comment by cn-Meepo** [comment]
@972223177 切换到master分支，更新最新的flutter版本解决问题
