### ISSUE TITLE
自定义当前位置图标指向错误

### ISSUE THREAD

**Issue by hidetag** [fluttify-project/amap_map_fluttify#126]
**插件版本**
`0.15.0+5a112a2`
**遇到bug的平台(Android/iOS)**
`Android`
**描述bug**
`自定义当前位置图标指向错误`
**复现步骤**
`将当前位置的图标替换为自定义图标，旋转手机，当前位置图片不会旋转，指向错误；使用手势双指旋转地图，上述自定义的当前位置图标会随着手指旋转而旋转，指向错误`
**期望行为**
`旋转手机后自定义图标指向正确，双指旋转地图后，自顶替图标指向正确`
**截图**
![Screenshot_2019-12-26-09-44-45-163_com goldenridg](https://user-images.githubusercontent.com/15097928/71453088-7815f680-27c4-11ea-8d5d-a390bfe67ed5.jpg)
**flutter doctor**
`
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.30.2)
[✓] Connected device (1 available)
`

**Comment by yohom** [comment]
这个在android端可以做(监听角度变化然后调用`setMyLocationRotateAngle`，ios端还未实现)，但是ios端实现起来比较麻烦，建议还是先用默认的图标顶一下。

**Comment by hidetag** [comment]
@yohom 阔以，这边先行在 android 端实现
