### ISSUE TITLE
ios 循环创建marker 时不能正常显示

### ISSUE THREAD

**Issue by yanqiqi1996** [fluttify-project/amap_map_fluttify#13]
**插件版本** 0.2.8+591effd

**描述bug**  ios端循环创建marker时要么不显示，要么只显示一个，android没问题。按照example那样点击按钮添加则没有问题。

**复现步骤**
![WX20191029-151527](https://user-images.githubusercontent.com/31203049/67829165-1f521680-fb11-11e9-8176-a3548088d5a3.png)

**flutter doctor**  flutter1.91+hotfix.4
@yohom 大佬帮我看下

**Comment by yohom** [comment]
@yanqiqi1996 添加的时候加await试一下
```
markerList.forEach((l) {
  _controller?.addMarker(...);
});
```
改为
```
for(final marker in markerList) {
 await _controller?.addMarker(...);
}
```

**Comment by yanqiqi1996** [comment]
没问题啦 谢谢
