### ISSUE TITLE
需要提供一个添加固定显示在某个坐标位置（如地图中心点）不跟随地图移动而移动的marker的方法

### ISSUE THREAD

**Issue by luckmlc** [fluttify-project/amap_map_fluttify#134]
**功能描述**
需要提供一个添加固定显示在某个坐标位置（如地图中心点）不跟随地图移动而移动的marker的方法

**Native端对应字段/方法**
Marker 类的  setPositionByPixels 方法

**Comment by yohom** [comment]
这种需求我一般是套一个`Stack`，然后在叠一个`Center(child: XXX())`上去就行了。

**Comment by luckmlc** [comment]
> 这种需求我一般是套一个`Stack`，然后在叠一个`Center(child: XXX())`上去就行了。

嗯嗯，这个倒是可以这样做

不过还有修改某个marker在地图上的位置，和点平滑移动的功能也需要，看能不能提供下

**Comment by yohom** [comment]
修改marker经纬度的问题开了个新的Issue #138
