### ISSUE TITLE
ios 下遇到地图无法显示,app异常退出

### ISSUE THREAD

**Issue by khkdz** [fluttify-project/amap_map_fluttify#135]
**插件版本**
amap_map_fluttify: 0.10.5+be1d1e5
**遇到bug的平台(Android/iOS)**
ios 13.3(13.2.12.1) 不能正常显示地图,安卓下显示正常.
**描述bug**
打开地图,显示划线,地图显示为黑色一片
**复现步骤**
依赖项及代码如下
pubspec.yaml 
environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: 3.0.7
  permission_handler: ^4.0.0
  oktoast: 2.2.0
  shared_preferences: 0.5.3+4
  flutter_swiper: 1.1.6
  flutter_easyrefresh: 1.2.7
  image_picker: 0.6.2
  photo_view: 0.4.2
  flutter_cupertino_date_picker: 1.0.12
  device_info: 0.4.0+2
  package_info: 0.4.0+6
  path_provider: 1.3.0
  open_file: 2.0.3
  provider: 3.1.0
  cached_network_image: 1.1.1
  flutter_webview_plugin: 0.3.5
  flutter_image_compress: 0.6.3
  qr_flutter: 3.1.0

  url_launcher: ^5.2.7
 # amap_core_fluttify: 0.2.3+324aaff
  amap_map_fluttify: 0.10.5+be1d1e5
  amap_location_fluttify: 0.4.2+be1d1e5
#  amap_all_fluttify: 0.4.1
代码文件 amap.dart
import 'package:amap_map_fluttify/amap_map_fluttify.dart';
import 'package:flutter/material.dart';
import 'package:gangtongbao/color/my_color.dart';
import 'package:gangtongbao/view/my_header.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:amap_location_fluttify/amap_location_fluttify.dart';
import 'package:gangtongbao/utils/base_util.dart';

class Amap extends StatefulWidget {
  List<String> pointStrList;

  Amap({this.pointStrList});

  List<LatLng> pointList = List();

  @override
  _AmapState createState() => _AmapState();
}

class _AmapState extends State<Amap> {
  AmapController _controller;
  double longitude, latitude; //经纬度

  Widget build(BuildContext context) {
    return WillPopScope(
        child: Scaffold(
          backgroundColor: Colors.white,
          appBar: MyHeader(
            backgroundColor: MyColor.themeColor,
            height: 40,
            isShowLeft: true,
            title: "预约范围",
            titleColor: Colors.white,
            clickLeft: () {
              Navigator.pop(context, true);
            },
          ),body: AmapView(
              // 地图类型
              mapType: MapType.Standard,
              // 是否显示缩放控件
              showZoomControl: false,
              // 是否显示指南针控件
              showCompass: true,
              // 是否显示比例尺控件
              showScaleControl: true,
              // 是否使能缩放手势
              zoomGesturesEnabled: true,
              // 是否使能滚动手势
              scrollGesturesEnabled: true,
              // 是否使能旋转手势
              rotateGestureEnabled: true,
              // 是否使能倾斜手势
              tiltGestureEnabled: true,
              // 缩放级别
              zoomLevel: 12,
              // 中心点坐标
      //        centerCoordinate: LatLng(39, 120),
              // 地图创建完成回调
              onMapCreated: (controller) async {
                _controller = controller;
                // requestPermission是权限请求方法, 需要你自己实现
                // 如果不知道怎么处理, 可以参考example工程的实现
                  await controller.showMyLocation(true);
              //绘制预约范围（可能多个）
                List<LatLng> ShowptList = new List<LatLng>();
                  for (var i = 0; i < widget.pointStrList.length; i++) {
                    String pointsStr = widget.pointStrList[i];
                    List pointList = pointsStr.split(";");
                    widget.pointList.clear();

                    for (var j = 0; j < pointList.length; j++) {
                      List points = pointList[j].toString().split(",");
                      LatLng p =
                      LatLng(double.parse(points[1]), double.parse(points[0]));
                      widget.pointList.add(p);
                      ShowptList.add(p);
                    }
                    PolygonOption plgopt = new PolygonOption(latLngList: widget.pointList,
                    width: 5,
                    strokeColor: Colors.red,
                    fillColor: Colors.transparent);

                    await controller.addPolygon(plgopt );
                  }
                  controller. zoomToSpan(ShowptList);
                  },

            ),

        ),
        onWillPop: () {
          Navigator.pop(context, true);
          return null;
        });
  }

  @override
  void initState() {
    super.initState();
    getLocation();
  }

  Future<bool> requestPermission() async {
    final permissions =
    await PermissionHandler().requestPermissions([PermissionGroup.location]);

    if (permissions[PermissionGroup.location] == PermissionStatus.granted) {
      return true;
    } else {
      showToastWithMessage('需要定位权限!');
      return false;
    }
  }
  /*
    获取当前经纬度信息
   */
  void getLocation() async {
    if (await requestPermission())  {
      await for (final location in AmapLocation.listenLocation()) {
        Future<LatLng> point =  location.latLng;
        point.then((onValue){
          latitude = onValue.latitude;
          longitude = onValue.longitude;

          if(_controller!= null){
            List<LatLng> ShowptList = new List<LatLng>();
            for (var i = 0; i < widget.pointStrList.length; i++) {
              String pointsStr = widget.pointStrList[i];
              List pointList = pointsStr.split(";");

              for (var j = 0; j < pointList.length; j++) {
                List points = pointList[j].toString().split(",");
                LatLng p =
                LatLng(double.parse(points[1]), double.parse(points[0]));

                ShowptList.add(p);
              }
              LatLng p1 =
              LatLng(latitude,longitude);
              ShowptList.add(p1);

            }
            _controller.zoomToSpan(ShowptList);
            _controller.zoomOut();
          }
        });
      }
    }
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
    AmapLocation.stopLocation();
  }
}
**期望行为**
ios调试输出如下:
2019-12-30 10:53:22.781154+0800 Runner[13322:5226449] [] nehelper sent invalid result code [1] for Wi-Fi information request
2019-12-30 10:53:22.783270+0800 Runner[13322:5226171] [MAMapKit] 无效的资源bundle，请检查AMap.bundle是否正确导入。
2019-12-30 10:53:22.783357+0800 Runner[13322:5226171] [MAMapKit] 无效的资源bundle，请检查AMap.bundle是否正确导入。
2019-12-30 10:53:22.876258+0800 Runner[13322:5226171] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x2815661e0> to GL_RENDERBUFFER 1
2019-12-30 10:53:22.876986+0800 Runner[13322:5226171] Failed to make complete framebuffer object 8cd6
2019-12-30 10:53:22.880060+0800 Runner[13322:5226171] Failed to bind EAGLDrawable: <CAEAGLLayer: 0x2815661e0> to GL_RENDERBUFFER 1
2019-12-30 10:53:22.880126+0800 Runner[13322:5226171] Failed to make complete framebuffer object 8cd6
2019-12-30 10:53:22.880752+0800 Runner[13322:5226430] flutter: fluttify-dart: MAMapView@1::setUserTrackingMode(['animated':true])
2019-12-30 10:53:22.881069+0800 Runner[13322:5226430] flutter: fluttify-dart: AMapLocationManager@10772296256::startUpdatingLocation([])
2019-12-30 10:53:22.902102+0800 Runner[13322:5226430] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Bad state: Stream has already been listened to.
#0      _StreamController._subscribe (dart:async/stream_controller.dart:668:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
#3      new _AddStreamState (dart:async/stream_controller.dart:885:34)
#4      new _StreamControllerAddStreamState (dart:async/stream_controller.dart:937:9)
#5      _StreamController.addStream (dart:async/stream_controller.dart:560:13)
#6      _AsyncStarStreamController.addStream (dart:async-patch/async_patch.dart:197:37)
#7      AmapLocation.listenLocation (package:amap_location_fluttify/src/dart/amap_location.dart:228:7)
<asynchronous suspension>
#8      _AmapState.getLocation (package:gangtongbao/activity/amap.dart:150:49)
<asynchronous suspension>
#9      _AmapState.initState (package:gangtongbao/activity/amap.dart:130:5)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#28     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
#29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#48     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#53     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#54     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#58     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#64     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#65     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#71     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#77     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#81     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#90     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#96     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#101    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#102    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#103    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#106    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#111    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#112    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#117    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#118    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#119    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#120    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#124    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#125    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#126    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#129    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4910:32)
#130    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5243:17)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#132    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:607:16)
#133    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#135    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#136    StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#139    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#140    ProxyElement.update (package:flutter/src/widgets/framework.dart:4254:5)
#141    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#143    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#147    StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#149    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
#150    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#151    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#154    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#155    StatelessElement.update (package:flutter/src/widgets/framework.dart:4016:5)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#158    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#159    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
#160    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
#161    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
#162    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
#163    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
#164    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
#165    _rootRun (dart:async/zone.dart:1124:13)
#166    _CustomZone.run (dart:async/zone.dart:1021:19)
#167    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#168    _invoke (dart:ui/hooks.dart:249:10)
#169    _drawFrame (dart:ui/hooks.dart:207:3)
2019-12-30 10:53:22.903604+0800 Runner[13322:5226574] [] nehelper sent invalid result code [1] for Wi-Fi information request
2019-12-30 10:53:22.903859+0800 Runner[13322:5226430] flutter: fluttify-dart: MAMapView@1::updateUserLocationRepresentation([])
2019-12-30 10:53:22.904153+0800 Runner[13322:5226430] flutter: fluttify-dart-callback: amapLocationManagerDidUpdateLocationreGeocode([])
2019-12-30 10:53:22.904333+0800 Runner[13322:5226430] flutter: amapLocationManagerDidUpdateLocationreGeocode::kNativeObjectPool: {AMapServices{refId: 10765673376}, AMapLocationManager{refId: 10772296256}, CLLocation{refId: 10760957056}, AMapLocationReGeocode{refId: 0}, CLLocation{refId: 10760958288}, AMapLocationReGeocode{refId: 10798304000}, MAUserLocationRepresentation{refId: 10753969920}, CLLocation{refId: 10760957120}, AMapLocationReGeocode{refId: 10798313088}}
**截图**

**flutter doctor**
admin@admindeMacBook-Pro gtb_mobile % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[!] VS Code (version 1.41.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by yohom** [comment]
这个问题是AMap.bundle没有加载，参考 #64 .
