### ISSUE TITLE
添加标记的时候，报空指针

### ISSUE THREAD

**Issue by houyongfeng1984** [fluttify-project/amap_map_fluttify#137]
**插件版本**
amap_map_fluttify: ^0.16.2+a3d4e61
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
I/flutter (12719): PlatformException(Attempt to invoke virtual method 'com.amap.api.maps.model.Marker com.amap.api.maps.AMap.addMarker(com.amap.api.maps.model.MarkerOptions)' on a null object reference, null, null)
**复现步骤**
执行 await _controller?.addMarker(marker);
我已经判断过controller不为空
**期望行为**
如何解决，我通过
  addMarker(MarkerOption marker) async {
    try{
     await _controller?.addMarker(marker);
    }catch (e){
      print(e);
      await addMarker(marker);
    }
  }
标记上去后，但是里面的内容很多是重复，我觉得是线程不安全，或者全局变量被改动了
**截图**
![Uploading image.png…]()

**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.914], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] VS Code (version 1.38.1)
[√] Connected device (1 available)

**Comment by bentu-noodoe** [comment]
+1

**Comment by Maconzhang** [comment]
我也遇到这样的问题 在ios 端是好的在安卓就报控指针。 @yohom

**Comment by AugustToko** [comment]
+1

**Comment by bentu-noodoe** [comment]
我這裡發現是自己沒寫好，目前已經解決了
錯誤在於我的clearMarkers()和addMarkers()沒有用async做

原本的版本：
```Dart
class _MapState extends State<Map> {
  AmapController _controller;

  @override
  Widget build(BuildContext context) {
    return Consumer<MyModel>(
      builder: (context, model, child) {
          _controller?.clearMarkers(); //這裡是錯的，必須async去做
          _controller?.addMarkers(model.markerOptions);  //這裡是錯的，必須async去做
        return child;
      },
      child: AmapView(
        mapType: MapType.Standard,
        markers: <MarkerOption>[],
        onMapMoveEnd: (move) async {
          loadMarkerOptions();
        },
        onMapCreated: (controller) async {
          _controller = controller;
        },
      ),
    );
  }
}
```

更新後的版本：
```Dart
class _MapState extends State<Map> {
  AmapController _controller;

  @override
  Widget build(BuildContext context) {
    return Consumer<MyModel>(
      //改成用FutureBuilder加上promise語法
      builder: (context, model, child) => FutureBuilder(
        future: _controller?.clearMarkers()?.then((_) {
          _controller?.addMarkers(model.markerOptions);
        }),
        initialData: child,
        builder: (context, snapshot) => child,
      ),
      child: AmapView(
        mapType: MapType.Standard,
        markers: <MarkerOption>[],
        onMapMoveEnd: (move) async {
          loadMarkerOptions();
        },
        onMapCreated: (controller) async {
          _controller = controller;
        },
      ),
    );
  }
}
```

**Comment by houyongfeng1984** [comment]
难怪，太好了，谢谢，解决了项目中的问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"bentu-noodoe"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月24日(星期一) 中午12:20
收件人:&nbsp;"fluttify-project/amap_map_fluttify"<amap_map_fluttify@noreply.github.com&gt;;
抄送:&nbsp;"登顶珠峰"<283229485@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fluttify-project/amap_map_fluttify] 添加标记的时候，报空指针 (#137)




我這裡發現是自己沒寫好，目前已經解決了
 錯誤在於我的clearMarkers()和addMarkers()沒有用async做
 
原本的版本：
 class _MapState extends State<Map&gt; {   AmapController _controller;   @override   Widget build(BuildContext context) {     return Consumer<MyModel&gt;(       builder: (context, model, child) {           _controller?.clearMarkers(); //這裡是錯的，必須async去做           _controller?.addMarkers(model.markerOptions);  //這裡是錯的，必須async去做         return child;       },       child: AmapView(         mapType: MapType.Standard,         markers: <MarkerOption&gt;[],         onMapMoveEnd: (move) async {           loadMarkerOptions();         },         onMapCreated: (controller) async {           _controller = controller;         },       ),     );   } }
 
更新後的版本：
 class _MapState extends State<Map&gt; {   AmapController _controller;   @override   Widget build(BuildContext context) {     return Consumer<MyModel&gt;(       //改成用FutureBuilder加上promise語法       builder: (context, model, child) =&gt; FutureBuilder(         future: _controller?.clearMarkers()?.then((_) {           _controller?.addMarkers(model.markerOptions);         }),         initialData: child,         builder: (context, snapshot) =&gt; child,       ),       child: AmapView(         mapType: MapType.Standard,         markers: <MarkerOption&gt;[],         onMapMoveEnd: (move) async {           loadMarkerOptions();         },         onMapCreated: (controller) async {           _controller = controller;         },       ),     );   } }
