### ISSUE TITLE
[enhance] 提供一个example工程的apk二维码供下载

### ISSUE THREAD

**Issue by yohom** [fluttify-project/amap_map_fluttify#140]
**功能描述**
目前看示例需要下载工程然后编译，整个过程比较繁琐而且容易出错，需要提供一个编译好的apk供下载，保证统一性。如果可以的话看下有没有提供ipa的方式（蒲公英之类的）。

**Native端对应字段/方法**
N/A

**Comment by hidetag** [comment]
readme 中可以新增一些内容：
在抬升`amap_map_fluttify`版本之后，Android 端可能出现无法编译的问题，例如 amap Android 工程重复类等，iOS 端出现的问题相对好排查，此时可以进入到 flutter 本地的库缓存位置删除老版本本地缓存依赖，重新 get packages，同时使用 Android Studio 打开 example 中的 android 工程，带其 indexing 索引完毕后，执行 clean，一般可以解决大部分`amap_map_fluttify `中遇到的编译问题.

**Comment by yohom** [comment]
> readme 中可以新增一些内容：
> 在抬升`amap_map_fluttify`版本之后，Android 端可能出现无法编译的问题，例如 amap Android 工程重复类等，iOS 端出现的问题相对好排查，此时可以进入到 flutter 本地的库缓存位置删除老版本本地缓存依赖，重新 get packages，同时使用 Android Studio 打开 example 中的 android 工程，带其 indexing 索引完毕后，执行 clean，一般可以解决大部分`amap_map_fluttify `中遇到的编译问题.

老铁的建议不错，如果方便的话可以来个PR 😉

**Comment by yohom** [comment]
@hidetag 当前issue主体已经处理，如果你有完善README的好的建议可以另外开一个issue，或者直接发起PR。一般常见问题的处理可以放在 [Troubleshooting.md](https://github.com/fluttify-project/amap_map_fluttify/blob/master/Troubleshooting.md) 下。
