### ISSUE TITLE
addMarker 渲染异常问题请教，作者看过来。

### ISSUE THREAD

**Issue by Maconzhang** [fluttify-project/amap_map_fluttify#146]
**插件版本**
amap_map_fluttify: ^0.17.5
**遇到bug的平台(Android/iOS)**
ios
**描述bug**
代码1:

```
> Future.forEach(_vehicleList, (item) async{
>       MarkerOption _markerOption = MarkerOption(
>           widget: Container(
>             height: 40,
>             width: 40,
>             decoration: BoxDecoration(
>                 image: DecorationImage(
>               image: _getImage(item['type']),
>               fit: BoxFit.fill,
>             )),
>             child: Center(
>                child: Text('${item["electricity"].toString()}%'),
>             ),
>           ),
>           title: '${item["customNo"]}',
>           latLng: LatLng(item['coordinate']['lat'], item['coordinate']['lng']));
>       await _controller.addMarker(_markerOption);
>     });
```

如代码1 这样渲染markers 保证了背景图片能正确渲染渲染，但是只能一个个渲染，速度较慢，大概了有1000-2000多个点。

代码2: 
```
_vehicleList.forEach((item) async {
      MarkerOption _markerOption = MarkerOption(
          widget: Container(
            height: 40,
            width: 40,
            decoration: BoxDecoration(
                image: DecorationImage(
              image: _getImage(item['type']),
              fit: BoxFit.fill,
            )),
            child: Center(
               child: Text('${item["electricity"].toString()}%'),
            ),
          ),
          title: '${item["customNo"]}',
          latLng: LatLng(item['coordinate']['lat'], item['coordinate']['lng']));
      await _controller.addMarker(_markerOption);
    });
```

代码2的问题的是image 没有正确的渲染， icon 错乱了。我初步的判断是否循环中的异步导致的。
注： 用addMarkers的话页面反应较慢，有一段时间卡在那里。

有什么办法能实现代码的一次性快速渲染，image 能对应上呢？ 比如类似js 中let 块级作用域的这种

**Comment by yohom** [comment]
使用widget作为marker这种方式本身就不是用常规方式实现的，需要先渲染出widget然后再转换为Uint8List，然后再把Uint8List传给native端处理，整个过程都是比较耗时的，如果能用普通的图片实现的话就尽量用普通图片的方式实现吧。

**Comment by yohom** [comment]
你可以想办法优化下展示出来的marker数量。

**Comment by Maconzhang** [comment]
> 使用widget作为marker这种方式本身就不是用常规方式实现的，需要先渲染出widget然后再转换为Uint8List，然后再把Uint8List传给native端处理，整个过程都是比较耗时的，如果能用普通的图片实现的话就尽量用普通图片的方式实现吧。

我必须要marker上面标注信息， 如果不用widget的方式，有什么更好的实现吗？ 普通图片上面可以添加标注信息吗？

**Comment by yohom** [comment]
我感觉还是缩减一下展示的marker可行性更高，你可以模拟一下点聚合的效果，插件目前还没有实现这个功能，相关issue #143 。

**Comment by dsmjoy** [comment]
感觉1000-2000 个点确实有点多了.   是一个屏幕就显示这么多个点吗?   可以只渲染屏幕这个矩形内的Marker.  移动屏幕再渲染另外的.

另外, Marker里的图片有时候出不来,  我打算直接用iconUri了.   我这边图片比较简单,  打算直接让后台把图片该有的一些样式处理好, 返回给我的就是带有样式的图片了.
iconUri 感觉确实比widget快了一些.

**Comment by dsmjoy** [comment]
不过即使几十个Marker(普通图片, 不是widget)渲染也比较慢. 

我测试了一下, 耗时主要是这一块, 基本200+, 300+毫秒, 平均300毫秒吧
![image](https://user-images.githubusercontent.com/15439238/73454614-63231900-43a9-11ea-9a1f-dce4ba9582c5.png)

发现, 这一块好像是会等这张图片加载并处理完成再继续往下走,  然后整个过程又是包在一个for循环内的. 所以整个渲染需要等所有图片串行加载并处理完成, 才能完成整个渲染.

这个图片处理的过程还有优化的空间吗? 有没有可能并行的去处理这些图片?
