### ISSUE TITLE
addMarkers功能，使用MarkerOption的widget第一个位置不显示图片

### ISSUE THREAD

**Issue by wangdongmeng** [fluttify-project/amap_map_fluttify#147]
**插件版本**
amap_all_fluttify: 0.11.0

**遇到bug的平台(Android/iOS)**
Android和IOS
**描述bug**
使用addMarkers批量添加marker，使用MarkerOption的widget第一个index不显示图片，其它index都能显示。另外使用iconUri添加图片都显示。目前需求只能使用widget来显示marker。
**复现步骤**
代码：

final markers = await _controller?.addMarkers(
              [
                for (int i = 0; i < _trackList.length; i++)
                  MarkerOption(
                    latLng: _trackList[i],
                    widget: Container(
                      child: Stack(
                        alignment: Alignment.topCenter,
                        children: <Widget>[
                          Image.asset(
                            'images/pic_point_green.png',
                            width: 26,
                            height: 36,
                          ),
                          Padding(
                            padding: EdgeInsets.only(top: 5.0),
                            child: Text(
                              (i + 1).toString(),
                              style:
                                  TextStyle(color: Colors.white, fontSize: 11),
                            ),
                          ),
                        ],
                      ),
                    ),
                    imageConfig: createLocalImageConfiguration(context),
                  ),
              ],
            );

**期望行为**

**截图**
![image](https://user-images.githubusercontent.com/7833854/71867878-f2406680-3146-11ea-8344-7230f2131e9b.png)
**flutter doctor**
[✓] Flutter (Channel dev, v1.13.2, on Mac OS X 10.14.6 18G95, locale en-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

麻烦帮看下。谢谢

**Comment by yohom** [comment]
这个是flutter的bug，只能等flutter修复，参考 #97 。
