### ISSUE TITLE
Android 三指截图后地图卡死

### ISSUE THREAD

**Issue by KossFun** [fluttify-project/amap_map_fluttify#148]
**插件版本**

  0.17.5 

**遇到bug的平台(Android/iOS)**

   Android (小米手机 MIUI11.0.4 Android9)

**描述bug**

  三指截图后地图卡死, 无法继续点击或其他操作

**复现步骤**

**期望行为**

**截图**
  
![图片](https://user-images.githubusercontent.com/49841387/71962672-ed59e080-3234-11ea-9203-d0e72fe35c1c.png)

**flutter doctor**
   [√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.914], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at E:\software\flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at E:\software\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\software\JetBrains\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at C:\software\JetBrains\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

**Comment by yohom** [comment]
这个看上去好像是PlatformView崩了？可以去flutter官方Repo下看看有没有类似issue。

**Comment by hidetag** [comment]
我这边 Andorid 也遇到了，不过只是 debug 版会卡死，release 不会
