### ISSUE TITLE
指南针的位置可以自定义吗

### ISSUE THREAD

**Issue by KossFun** [fluttify-project/amap_map_fluttify#149]
**功能描述**

**Native端对应字段/方法**

**Comment by yohom** [comment]
提供一下相关高德api文档。

**Comment by KossFun** [comment]
安卓自定义指南针 https://blog.csdn.net/u010575303/article/details/78002232
没搞过iOS(>_<)

**Comment by KossFun** [comment]
![图片](https://user-images.githubusercontent.com/49841387/71966745-1f6f4080-323d-11ea-8887-a2eed3c97cb5.png)
ios?

**Comment by yohom** [comment]
你给的自定义指南针的文档，也是在高德地图上面盖了一层View，可以不依赖高德。在Flutter中你可以先隐藏高德自带的指南针控件，然后用Stack堆一个Widget上去，然后放一个指南针widget。
