### ISSUE TITLE
Marker图标不能调整大小，不能绑定数据

### ISSUE THREAD

**Issue by q869939686** [fluttify-project/amap_map_fluttify#15]
**功能描述**
Marker图标不能调整大小，会把原图片大小显示上去

**Comment by q869939686** [comment]
Marker不能绑定数据，只有title和snipper字符串类型，不能在Marker上绑定Map类型的数据
![image](https://user-images.githubusercontent.com/29123332/67841909-1292ea00-fb34-11e9-852d-4fba17bbdede.png)

**Comment by yohom** [comment]
绑定数据这个功能，android上实现起来是比较快的，但是iOS端我一直都没能找到对应的api。

**Comment by Maconzhang** [comment]
我还想问新版本的MarkerOption 中的ImageConfiguration是否能改变图片渲染的大小呢？感觉不是很好理解。

**Comment by yohom** [comment]
@Maconzhang 目前利用到的信息只有[devicePixelRatio], 使用[devicePixelRatio]获取当前设备对应分辨率的图片(Android), iOS使用1.0x的图片. 所以[size]设置了是没用的, 这是flutter的PlatformView的bug, 参考https://github.com/flutter/flutter/issues/24865.这个bug彻底解决之后才能保证marker是完美的。

**Comment by yohom** [comment]
Flutter的这个bug不解决，marker图片大小的问题就难以解决，我目前做的也只是变通方法，没有完全解决这个问题。对这个bug更加详细的分析看这个评论 https://github.com/flutter/flutter/issues/24865#issuecomment-455791375 .
