### ISSUE TITLE
使用addMarker问题

### ISSUE THREAD

**Issue by wangdongmeng** [fluttify-project/amap_map_fluttify#150]
**插件版本**
amap_all_fluttify: 0.11.0
**遇到bug的平台(Android/iOS)**
IOS 
**描述bug**
使用addMarker添加点，添加marker点的时候，坐标不能解析为正常坐标，（错误的坐标latitude: 0.0, longitude: 5.0927706332594685e-168）导致marker点会显示到大西洋几内亚湾。。
**复现步骤**

不能正常显示的坐标为：
39.921214,116.575486

code:
await _controller.addMarker(
            MarkerOption(
              latLng:
                  LatLng(39.921214, 116.575486),
              infoWindowEnabled: false,
              widget: Container(
                child: Stack(
                  alignment: Alignment.topCenter,
                  children: <Widget>[
                    Image.asset(
                      'images/pic_point_green.png',
                      width: 26,
                      height: 36,
                    ),
                    Padding(
                      padding: EdgeInsets.only(top: 5.0),
                      child: Text(
                        'index',
                        style: TextStyle(color: Colors.white, fontSize: 11),
                      ),
                    ),
                  ],
                ),
              ),
              imageConfig: createLocalImageConfiguration(context),
            ),
          );

麻烦帮忙看下。谢谢
**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
你传入的经纬度是通过定位获取到的还是手动输入的？因为看你出错的坐标
> （错误的坐标latitude: 0.0, longitude: 5.0927706332594685e-168）
应该是传入了(0, 0)，这个坐标应该是在非洲那边。

**Comment by wangdongmeng** [comment]
这个坐标是从我后台获取的，是正常坐标，我把这个坐标用高德坐标拾取器能正常显示。
从后台返回的坐标如下，
![image](https://user-images.githubusercontent.com/7833854/72028795-ce079580-32be-11ea-8c61-5a52ad4dd75e.png)

**Comment by wangdongmeng** [comment]
补充一下，图片中的两个坐标点会显示，但是会显示到非洲那边，Android没有问题。麻烦作者可以测试下这些坐标。多谢

**Comment by theecn** [comment]
ios端要用真机做测试，然后你的bundle name 要和你在高德地图里申请的应用名是一样的

**Comment by wangdongmeng** [comment]
@theecn  我试过了  还是不行
![image](https://user-images.githubusercontent.com/7833854/75209114-6945c300-57b8-11ea-9c2a-55f360df1725.png)
![image](https://user-images.githubusercontent.com/7833854/75209137-7cf12980-57b8-11ea-9319-a90737a5b0e9.png)

bundle name 和应用名称都一样  marker点还是显示到了非洲那边

求大神帮下，多谢
