### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by apegeek** [fluttify-project/amap_map_fluttify#153]
The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/apegeek/work/development/flutter/workspace/uav/ios/Pods/AMap3DMap/MAMapKit.framework and /Users/apegeek/work/development/flutter/workspace/uav/ios/Pods/AMapFoundation/AMapFoundationKit.framework)

**Comment by apegeek** [comment]
什么原因呢？

**Comment by yohom** [comment]
参考下 https://github.com/fluttify-project/amap_map_fluttify/blob/develop/Troubleshooting.md#swift%E5%B7%A5%E7%A8%8B%E9%9B%86%E6%88%90%E6%97%B6-%E6%8A%A5the-pods-runner-target-has-transitive-dependencies-that-include-statically-linked-binaries

**Comment by zfy1988** [comment]
注掉 use_frameworks!

**Comment by apegeek** [comment]
谢谢各位，升级amap_map_fluttify到最新版本就好了
