### ISSUE TITLE
android真机运行奔溃，iOS真机正常

### ISSUE THREAD

**Issue by zfy1988** [fluttify-project/amap_map_fluttify#154]
**插件版本**
0.17.6+107df19
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
安装debug版后  点击桌面图标 APP奔溃 无法打开
**复现步骤**

**期望行为**
APP能正常打开
**截图**

**flutter doctor**
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/zhufengyuan/Library/flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/zhufengyuan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • AOSP on taimen • 710KPDT0426330 • android-arm64 • Android 9 (API 28)

**Comment by yohom** [comment]
报什么错

**Comment by zfy1988** [comment]
> 报什么错

控制台无任何错误日志输出
