### ISSUE TITLE
Problems when adding widget markers and map display

### ISSUE THREAD

**Issue by yhf1414104530** [fluttify-project/amap_map_fluttify#159]
**插件版本**
0.17.9+356f11c
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
When the widget marker is added, the marker will be displayed outside the map, and the map will have a top margin
**复现步骤**
`
Container(
      height: sHeight(500),
      child: AmapView(
        key: _mapKey,
        showZoomControl: false,
        centerCoordinate: LatLng(30.0, 120.0),
        markers: [
          MarkerOption(
            latLng: LatLng(30.1, 120.1),
            title: '北京',
            snippet: '描述',
            widget: Image.asset(
              ImagePath.logo,
              width: 24,
              height: 24,
            ),
            imageConfig:
                createLocalImageConfiguration(context, size: Size(6.0, 6.0)),
            infoWindowEnabled: false,
          ),
          MarkerOption(
            latLng: LatLng(30.11, 120.1),
            title: '北京',
            snippet: '描述',
            widget: Image.asset(
              ImagePath.logo,
              width: 24,
              height: 24,
            ),
            imageConfig:
                createLocalImageConfiguration(context, size: Size(6.0, 6.0)),
            infoWindowEnabled: false,
          ),
          MarkerOption(
            latLng: LatLng(30.12, 120.1),
            title: '北京',
            snippet: '描述',
            widget: Image.asset(
              ImagePath.logo,
              width: 24,
              height: 24,
            ),
            imageConfig:
                createLocalImageConfiguration(context, size: Size(6.0, 6.0)),
            infoWindowEnabled: false,
          ),
        ],
        onMapCreated: (controller) async {
          controller.setZoomLevel(8, animated: false);
        },
      ),
    )
`
**期望行为**
fix bug
**截图**
[https://i.postimg.cc/cLpcYW3f/Wechat-IMG2.jpg](url)
**flutter doctor**
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G95,
    locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)

**Comment by yohom** [comment]
1. AndroidView的上边距问题是flutter的bug，参考 https://github.com/flutter/flutter/issues/24657
2. 正如你发现的widget marker出现在地图外面，是因为这就是widget marker的实现机制，先在地图下面渲染好widget，然后再转换成图片数据，再传递给原生端。
结论：widget marker出现在地图外面是预期的行为，上边距是flutter的bug，所以我先关掉issue了。
