### ISSUE TITLE
iOS点击Marker无法获取数据

### ISSUE THREAD

**Issue by q869939686** [fluttify-project/amap_map_fluttify#16]
**插件版本**
0.2.8
**描述bug**
iOS设备点击Marker获取不到marker数据返回，安卓可以
**复现步骤**

**期望行为**

**截图**
![image](https://user-images.githubusercontent.com/29123332/67853325-475d6c00-fb49-11e9-80e7-25cc4390a9b8.png)

**flutter doctor**

**Comment by yohom** [comment]
@q869939686 0.3.0版本，已处理。
