### ISSUE TITLE
iOS真机测试错误：'amap_core_fluttify/AmapCoreFluttifyPlugin.h' file not found

### ISSUE THREAD

**Issue by WxxShirley** [fluttify-project/amap_map_fluttify#161]
**插件版本**amap_map_fluttify: ^0.5.4+d2eb645， amap_search_fluttify: ^0.2.11+d2eb645

**遇到bug的平台(Android/iOS)** iOS13.3(iPhone7), Xcode 11.3

**描述bug**amap_search_fluttify: ^0.2.11+d2eb645

**Comment by yohom** [comment]
1. 你的主工程是不是swift工程？
2. 更新一下插件版本，你的这个太老了。

**Comment by WxxShirley** [comment]
flutter工程，那我跟新插件版本看看。谢谢！

**Comment by WxxShirley** [comment]
请问插件最新的版本对应的flutter版本是？
更新失败，显示sdk版本低了

**Comment by WxxShirley** [comment]
iOS端真机调试报错： Module 'amap_core_fluttify' not found

**使用的插件版本**：amap_map_fluttify: ^0.17.11+69360c9
  amap_search_fluttify: ^0.7.4+356f11c
**平台**： iOS13.3 ，Xcode11.3
