### ISSUE TITLE
pod install 报错问题

### ISSUE THREAD

**Issue by houqinzhe** [fluttify-project/amap_map_fluttify#163]
**插件版本**
amap_map_fluttify: 0.17.11+69360c9
**遇到bug的平台(Android/iOS)**
ios 

**描述bug**
Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "AMapFoundation":
      In snapshot (Podfile.lock):
        AMapFoundation (= 1.5.6, ~> 1.4, ~> 1.5)

      In Podfile:
        amap_core_fluttify (from `.symlinks/plugins/amap_core_fluttify/ios`) was resolved to 0.0.1, which depends on
          AMapFoundation (~> 1.6)

    Specs satisfying the `AMapFoundation (= 1.5.6, ~> 1.4, ~> 1.5), AMapFoundation (~> 1.6)` dependency were found, but they required a higher minimum deployment target.
**复现步骤**

**期望行为**

**截图**
![image](https://user-images.githubusercontent.com/18320861/73731860-27ef6400-4774-11ea-8bc3-bfbd728b7ce2.png)

**flutter doctor**

**Comment by yohom** [comment]
你更新一下pod本地索引，`pod update AMapFoundation`跑一下。

**Comment by houqinzhe** [comment]
> 你更新一下pod本地索引，`pod update AMapFoundation`跑一下。

感谢，
