### ISSUE TITLE
离线地图

### ISSUE THREAD

**Issue by 390057892** [fluttify-project/amap_map_fluttify#166]
**功能描述**
离线地图能否实现，高德提供的sdk原生直接有对应的页面。

**Comment by yohom** [comment]
0.18.3版本开始起提供打开离线地图管理器的方法。

**Comment by 390057892** [comment]
> 0.18.3版本开始起提供打开离线地图管理器的方法。

麻烦告诉我下是什么方法。我没找到对应文档

**Comment by yohom** [comment]
https://github.com/fluttify-project/amap_map_fluttify/blob/3996a6d8c340c18250937ca7c8095c1e06ddb74c/lib/src/facade/amap_service.dart#L325

**Comment by 390057892** [comment]
> https://github.com/fluttify-project/amap_map_fluttify/blob/3996a6d8c340c18250937ca7c8095c1e06ddb74c/lib/src/facade/amap_service.dart#L325

十分感谢
