### ISSUE TITLE
IOS下地图marker点击事件无效

### ISSUE THREAD

**Issue by uemaker** [fluttify-project/amap_map_fluttify#167]
**插件版本**
amap_map_fluttify: 0.17.12+767ea66

**遇到bug的平台(Android/iOS)**
IOS

**描述bug**
IOS下地图加marker后设置点击事件无效, 偶尔又可以, 像是事件冲突, widget 和 iconUri方式都一样,
Android版本没有这个问题

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
0.17.14以上版本已解决这个问题

**Comment by hidetag** [comment]
依然复现了，iOS 。。。最新 0.18.3+ddeef69，我是批量添加 marker 的，每次进入界面只能有一个可以点，之后其他的就再也点不了了，必须要退出 app 重新进才行，控制台也没有任何报错
