### ISSUE TITLE
热重载的时候一直白屏

### ISSUE THREAD

**Issue by qllqll** [fluttify-project/amap_map_fluttify#169]
**插件版本**
^0.17.13+767ea66
**遇到bug的平台(Android/iOS)**
热重载的时候一直白屏
**描述bug**

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
参考 https://github.com/fluttify-project/amap_map_fluttify/issues/128#issuecomment-590018080
