### ISSUE TITLE
新版本iOS还是无法获取Marker点击事件

### ISSUE THREAD

**Issue by q869939686** [fluttify-project/amap_map_fluttify#17]
**插件版本**
0.3.0
**描述bug**
点击Marker无法触发事件，Android是可以的

**Comment by yohom** [comment]
我这边试了example工程是可以的，你那边有什么Marker点击事件相关的日志有吗

**Comment by q869939686** [comment]
![image](https://user-images.githubusercontent.com/29123332/67917397-d616cb00-fbd3-11e9-9c89-f549f417759d.png)
Xcode的Log，无法触发点击事件
![image](https://user-images.githubusercontent.com/29123332/67917426-f2b30300-fbd3-11e9-9f70-be2ad37ad109.png)
![image](https://user-images.githubusercontent.com/29123332/67917441-fd6d9800-fbd3-11e9-8775-e2eb96cdddcb.png)
