### ISSUE TITLE
插件是不是没有实现showInfoWindow，无法使用弹窗功能

### ISSUE THREAD

**Issue by lg21792565** [fluttify-project/amap_map_fluttify#170]
**插件版本**

**遇到bug的平台(Android/iOS)**

**描述bug**插件是否没有实现showInfoWindow()如果是的话，目前可以怎么处理这个问题

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
https://github.com/fluttify-project/amap_map_fluttify/blob/8fc4840de494f856b9ab9d85cf94d6416f3e279e/lib/src/dart/models.dart#L424
