### ISSUE TITLE
导航功能

### ISSUE THREAD

**Issue by 390057892** [fluttify-project/amap_map_fluttify#174]
**功能描述**
请问导航功能有实现么

**Comment by yohom** [comment]
https://github.com/fluttify-project/amap_map_fluttify/blob/fbf5156a7a7fc9e0a12f3d4b663f1a283f9d7e6c/lib/src/dart/amap_service.dart#L224

**Comment by 390057892** [comment]
> https://github.com/fluttify-project/amap_map_fluttify/blob/fbf5156a7a7fc9e0a12f3d4b663f1a283f9d7e6c/lib/src/dart/amap_service.dart#L224

非常感谢，我试试

**Comment by 390057892** [comment]
> https://github.com/fluttify-project/amap_map_fluttify/blob/fbf5156a7a7fc9e0a12f3d4b663f1a283f9d7e6c/lib/src/dart/amap_service.dart#L224

有一个问题，没有应用内导航么。现在只能跳转高德吗？

**Comment by yohom** [comment]
目前没有应用内导航计划。

**Comment by 390057892** [comment]
导航有封装好的页面。我打开android项目替换你的3dmap加入导航sdk, 然后flutter和native交互唤起封装好的页面，不知道会不会对您的依赖库有影响?

**Comment by yohom** [comment]
你可以先自己fork一份去搞一下。
