### ISSUE TITLE
您好，可以添加 规划结果 + 驾车路线绘制的功能吗？ 谢谢

### ISSUE THREAD

**Issue by bladeofgod** [fluttify-project/amap_map_fluttify#175]
**功能描述**
将规划出来的驾车路线按照实际的路况显示在地图上，同时将 DrivingRouteOverlay 开源，帮助您做特殊样式的显示方案。

**Native端对应字段/方法**
api 说明书：
https://lbs.amap.com/dev/demo/drive-route#Android
官方demo：
https://lbs.amap.com/api/javascript-api/example/driving-route/driving-custom

**Comment by yohom** [comment]
你可以把amap_search_fluttify里获取到的路线信息在amap_map_fluttify里用addPolyline画出来。

**Comment by bladeofgod** [comment]
> 你可以把amap_search_fluttify里获取到的路线信息在amap_map_fluttify里用addPolyline画出来。

谢谢您的回复
