### ISSUE TITLE
关于Marker的清除

### ISSUE THREAD

**Issue by criusKer** [fluttify-project/amap_map_fluttify#177]
需求：一键清空所有Marker。
1._controller.clearMarkers()时只会清除可视区域内的Marker，其他标记仍然存在。
2.使用for循环一个个remove的方式，清除的有点慢，且重新绘制所需的时间会加长，貌似没有被真正的remove掉。

**Comment by yohom** [comment]
android端我没有找到获取地图上所有marker的api，如果你能找到的话告知我一声。实在不行也只能循环remove。

**Comment by criusKer** [comment]
remove后重新add会越来越久这个有注意到不

**Comment by yohom** [comment]
0.20.0版本AmapController的removeMarker方法增加List<Marker>参数，可以控制删除那些marker。
