### ISSUE TITLE
addMarkers 设置rotateAngle无效

### ISSUE THREAD

**Issue by yuanThink** [fluttify-project/amap_map_fluttify#181]
**插件版本**
0.17.21+481e45c
**遇到bug的平台(Android/iOS)**
Android/iOS
**描述bug**
addMarkers 设置rotateAngle无效
**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by kuww** [comment]
请问怎么解决的

**Comment by yohom** [comment]
> 请问怎么解决的

更新到0.18.0
