### ISSUE TITLE
locationStyle.interval 没有公开接口

### ISSUE THREAD

**Issue by Gitldx** [fluttify-project/amap_map_fluttify#182]
AmapController.showMyLocation方法可以再增加一个interval参数设置locationStyle.interval吗？
现在的问题是设置了 myLocationType = MyLocationType.Rotate，但用户需要拖动地图到其他地方查看，不设置间隔时间的话，地图会频繁拖回到当前用户位置

**Comment by Gitldx** [comment]
我发现高德地图的MyLocationType还有一个选项： LOCATION_TYPE_MAP_ROTATE_NO_CENTER ，所以上面的问题可以通过设置成这个值也是可以的，同样需要作者多提供这个选项

**Comment by yohom** [comment]
其实加这一个选项是简单的，问题是iOS端没有对应的接口，所以不太好直接处理。我在想通过一些间接的方式在iOS端达到同样的效果。

**Comment by yohom** [comment]
0.8.0已经加入interval参数
