### ISSUE TITLE
定位

### ISSUE THREAD

**Issue by criusKer** [fluttify-project/amap_map_fluttify#183]
_controller?.showMyLocation(true,myLocationType: MyLocationType.Locate);
单次定位在某次版本更新后画面不会移到定位点。当时用0.17.12版本的时候好像是默认单次定位并且定位后会移过去。

**Comment by zzzj1233** [comment]
我也定不过去,我跑master的example是可以定位定过去的。跑自己的画面不会移动，后来我把master的key替换成自己的，master的也无法定位了，应该是key的问题

**Comment by yohom** [comment]
这个方法我花个版本优化一下好了，因为这个功能相关的原生接口差异比较大，不好统一
