### ISSUE TITLE
建议编写几个泛型模板替代subhandler

### ISSUE THREAD

**Issue by Gitldx** [fluttify-project/amap_map_fluttify#184]
目前的subhandler 方法体模式都差不多，可以编写如下范型方法：
class Tasks{
public <T,K> void task(Object args, MethodChannel.Result methodResult,String methodName){
        int refId = (int) ((Map<String, Object>) args).get("refId");
        T ref = (T) getHEAP().get(refId);
        Class tClass = ref.getClass();
        if (getEnableLog()) {
            String debugInfo =  MessageFormat.format("fluttify-java: {0}@{1}::{2}()",tClass.getName(),refId,methodName);
            Log.d("fluttify-java", debugInfo);
        }

        K result=null;
        try {

            Method method = tClass.getMethod(methodName);
            result =  (K) method.invoke(ref); 
        } catch (Throwable throwable) {
            throwable.printStackTrace();
            if (getEnableLog()) {
                Log.d("Current HEAP: ", getHEAP().toString());
            }
            methodResult.error(throwable.getMessage(), null, null);
            return;
        }

        // convert result to jsonable result
        K jsonableResult = result;

        methodResult.success(jsonableResult);
    }
}

使用：
Tasks t = new Tasks();
t.<com.amap.api.services.geocoder.RegeocodeRoad,String>task(methodCall.arguments,methodResult,"getName");

**Comment by yohom** [comment]
感谢建议，不过我在生成代码的时候就不会去考虑可读性和抽象性了，一切以方便生成代码为准。你可以看到生成的代码里其实有很多冗余的操作，这是因为我为了减小代码生成的复杂度而做的。

**Comment by Gitldx** [comment]
明白了，就是阅读的时候有点累
