### ISSUE TITLE
sample 无法跑通，存在依赖包和 flutter 分支矛盾，详见内文

### ISSUE THREAD

**Issue by DesmondX** [fluttify-project/amap_map_fluttify#186]
**插件版本**
已更新至当日最新

**遇到bug的平台(Android/iOS)**
android 

**描述bug**
sample code 无法跑通, 有包依赖和 flutter 分支的矛盾：
1. flushbar 最新包中： flushbar_route.dart: 273 
                                        void  install()   !无参数
    而 flutter stable分支中：          widgets/route.dart:41
                                        void install(OverlayEntry insertionPoint) !有参数
    flutter master 中无参数。因而使用 master。

此时导致第二个问题
2. decorated_flutter_0.11.0+1:  decorated_route.route.dart: 38
                                         使用了 RouteSettings 的成员 isInitialRoute
    而 flutter master 版本中：  widgets/navigator.dart: 83
                                         RouteSettings 中根本没有 isInitialRoute 成员
    flutter stable 中有。

因而出现分支矛盾，哪个分支都跑不通。

**复现步骤** 
到 example 目录下 flutter run 即可.

**期望行为**
跑通sample

**截图**

![intall](https://tva1.sinaimg.cn/large/00831rSTly1gcnpdlwvyhj31ak0fon06.jpg) 

![isInitialRoute](https://tva1.sinaimg.cn/large/00831rSTly1gcnpfdydppj31a60eutc1.jpg) 

**flutter doctor**
全都正常

**Comment by yohom** [comment]
我本地的环境是beta channel的，你可以用beta试下。

**Comment by DesmondX** [comment]
切换 beta 后，install报错，如问题描述。

**Comment by DesmondX** [comment]
这个问题我凉凉了。 另外请问哪里有相关的文档/博客吗？ 只有这个 readme 对于类似我这样的 flutter 新手，无从理解该技术方案。

**Comment by yohom** [comment]
贴下你的flutter doctor -v.
相关文章 https://juejin.im/user/57b79a98d342d3005abe2d83/posts

**Comment by DesmondX** [comment]
[16:29:04]
$ flutter doctor -v
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.14.6 18G3020, locale en-CN)
    • Flutter version 1.14.6 at /Users/desmond/Documents/WorkSpace/FlutterDev/flutter/flutter
    • Framework revision fabeb2a16f (6 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/desmond/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/desmond/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (4 available)
    • OS105             • d357dcd0                             • android-arm64  • Android 7.1.1 (API 25)
    • iPhone 11 Pro Max • 4E703A37-1AF6-4FD6-A57C-BFDDB7810A01 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome            • chrome                               • web-javascript • Google Chrome 80.0.3987.132
    • Web Server        • web-server                           • web-javascript • Flutter Tools

• No issues found!

**Comment by yohom** [comment]
要么你强制指定一下flushbar的版本，可能flushbar的某个版本有破坏性更新，至于哪个flushbar版本有用你得尝试一下。

**Comment by DesmondX** [comment]
嗯嗯 我在尝试指定节点
