### ISSUE TITLE
批量添加markers，拿不到marker的object

### ISSUE THREAD

**Issue by sisychen** [fluttify-project/amap_map_fluttify#188]
**插件版本**

**遇到bug的平台(Android/iOS)**

**描述bug**

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
贴一下插件版本

**Comment by yohom** [comment]
据我测试0.18.0(android, ios)已经能够正常获取到object，试下这个版本。
