### ISSUE TITLE
作者您好

### ISSUE THREAD

**Issue by shanzhenghan** [fluttify-project/amap_map_fluttify#19]
作者您好，能否增加一些功能
1、增加option自定义，比如定位周期interval
2、拖动地图后 由于一直在定位 总是又将当前定位点移到屏幕中央，想查看别的地方，导致没法查看
3、页面销毁dispose之后 好像还一直在定位，调用了_controller.dispose()了
4、如何获取当前定位点的位置信息（XX省XX市....）

**Comment by yohom** [comment]
2. 0.3.1版本默认的定位行为已经改成只定位一次
4. `AmapController`已经提供`getLocation`方法，获取当前位置
另外不同的issue最好还是单独开，不然不好追溯。

**Comment by yohom** [comment]
1、最好能提供一下两端对应的api文档，这样我实现起来比较快。

**Comment by shanzhenghan** [comment]
> 1、最好能提供一下两端对应的api文档，这样我实现起来比较快。

1、定位周期能否开放接口让用户自定义呀
Android原生：mLocationOption.setInterval(2000);
IOS原生：不会，哈哈
2、是否是定位一次是否也可以让用户自定义呀 我看现在是默认定位一次
Android原生：mLocationOption.setOnceLocation(true);
IOS原生：不会，哈哈
3、定位模式
   // 设置定位的类型为定位模式 ，可以由定位 LOCATION_TYPE_LOCATE、跟随 
    LOCATION_TYPE_MAP_FOLLOW 或地图根据面向方向旋转 LOCATION_TYPE_MAP_ROTATE
        aMap.setMyLocationType(AMap.LOCATION_TYPE_MAP_FOLLOW);
