### ISSUE TITLE
升级0.18版本后，批量添加的marker点击事件不管用

### ISSUE THREAD

**Issue by qyxm521** [fluttify-project/amap_map_fluttify#192]
**插件版本**
0.18
**遇到bug的平台(Android/iOS)**
android
**描述bug**
升级0.18版本后，批量添加的marker点击事件不管用
**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
根据你的描述我复现了一下步骤：批量添加marker，然后设置marker点击事件，但是我无法复现你说的bug，如下gif:
![issue192](https://user-images.githubusercontent.com/10418364/76969491-6710f780-6965-11ea-9ce8-6694e74f14b2.gif)

**Comment by qyxm521** [comment]
在AMa

**Comment by yuanThink** [comment]
ios 下批量添加marker 会偶现报错

**Comment by qyxm521** [comment]
好的，非常感谢，我再试试。
