### ISSUE TITLE
iOS添加marker一直不执行的问题

### ISSUE THREAD

**Issue by wkzz31** [fluttify-project/amap_map_fluttify#195]
**插件版本**
0.18.0+481e45c
**遇到bug的平台(Android/iOS)**
iOS
**描述bug**
在iOS端，当界没有切换到要添加marker的经纬度时，addMarker方法一直不返回结果
**复现步骤**
在iOS端，默认显示城市为北京，然后给西安添加一个marker，如果先调用addMarker，再去调用setCenterCoordinate，addMarker会一直执行不完，代码会一直卡在这里，不执行下面的语句。我不懂iOS，所以不会，请大佬帮看看。
**期望行为**
我不太懂iOS地图机制，希望无论在何处都能直接执行addMarker方法，并返回结果。
**截图**

**flutter doctor**

**Comment by yohom** [comment]
根据你的描述，bug为：添加不在当前显示范围内的marker时，addMarker方法不返回。
我试了一下，无法复现你的问题，还是说有我理解不对的地方？
![issue](https://user-images.githubusercontent.com/10418364/76968102-53649180-6963-11ea-9b6d-2a7353bbd766.gif)

**Comment by wkzz31** [comment]
作者你好！首先感谢你的阅读与回复。

我遇到的问题时这样子的：
使用example工程，DrawPointScreen类，将AmapView设置如下：
AmapView(
              zoomLevel: 15,
              onMapCreated: (controller) async {
                _controller = controller;
                if (await requestPermission()) {
                  await controller.setZoomLevel(15);
                }
              },
            )


将AddMarker改为如下：
                ListTile(
                  title: Center(child: Text('添加Marker')),
                  onTap: () async {
                    print('addMarker start');
                    final marker = await _controller?.addMarker(
                      MarkerOption(
                        latLng: LatLng(34,108),
                        title: '北京',
                        snippet: '描述',
                        iconUri: _assetsIcon1,
                        imageConfig: createLocalImageConfiguration(context),
                        width: 48,
                        height: 48,
                        object: '自定义数据',
                      ),
                    );
                    print('addMarker end');
                    _controller?.setCenterCoordinate(34, 108);
                    _markers.add(marker);
                  },
                ),

addMarker start可以打印出来
addMarker end始终无打印

这时如果缩小地图，可以看到34,108坐标时，addMarker方法才执行完毕，addMarker end这时就打印出来了。
不知道这是不是高德sdk本身的问题。

**Comment by wkzz31** [comment]
@yohom 作者你好，不知道你那边出现了这样的问题吗？

**Comment by yohom** [comment]
最新版本0.18.2试一下，有做过处理
