### ISSUE TITLE
Execution failed for task ':foundation_fluttify:compileDebugKotlin

### ISSUE THREAD

**Issue by bladeofgod** [fluttify-project/amap_map_fluttify#197]
**插件版本**
0.17.18+5fd57b0
**遇到bug的平台(Android/iOS)**
android
**描述bug**
开发时，编译打包 报错：Execution failed for task ':foundation_fluttify:compileDebugKotlin
**复现步骤**

**期望行为**

**截图**

**flutter doctor**
谢谢您的帮助

**Comment by yuefeng007** [comment]
我也有同样的问题

**Comment by chaochaox1990** [comment]
+1

**Comment by yuefeng007** [comment]
使用amap  18.1 好了

**Comment by bladeofgod** [comment]
> 使用amap 18.1 好了

谢谢

**Comment by xj728** [comment]
> 使用amap 18.1 好了

我用的是amap_map_fluttify，用amap 18.1是什么意思？ pub.dev里没有找到amap这个插件
