### ISSUE TITLE
demo 报错

### ISSUE THREAD

**Issue by yyc123** [fluttify-project/amap_map_fluttify#2]
demo运行不起来，ios端模拟器
![image](https://user-images.githubusercontent.com/13059922/67540084-b5073380-f716-11e9-9b89-43654d3f9476.png)

**Comment by yohom** [comment]
@yyc123 要用真机跑

**Comment by yyc123** [comment]
@yohom 真机也不行，报相同错误

**Comment by yohom** [comment]
@yyc123 不会吧，你这里的报错是因为模拟器是x86架构的，真机是arm架构的

**Comment by yyc123** [comment]
![image](https://user-images.githubusercontent.com/13059922/67546089-ed663c00-f72d-11e9-9e96-b4cb31155543.png)
@yohom

**Comment by yohom** [comment]
`flutter package upgrade`，然后去ios文件夹下`pod install`试下

**Comment by yyc123** [comment]
都试过了，不行。难道在你那边是正常的么，很好奇



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "小山"<notifications@github.com&gt;; 
发送时间: 2019年10月25日(星期五) 中午1:50
收件人: "fluttify-project/amap_map_fluttify"<amap_map_fluttify@noreply.github.com&gt;; 
抄送: "quietly"<645746043@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [fluttify-project/amap_map_fluttify] demo 报错 (#2)




flutter package upgrade，然后去ios文件夹下pod install试下

**Comment by yohom** [comment]
我这边是可以运行的，你报这个错的原因是编译器在产物.o文件里找不到对应的symbol，那说明高德sdk里的那些二进制肯定没有被合并进去，你可以顺着这个思路排查一下

**Comment by yohom** [comment]
@yyc123 你是不是通过`Download Zip`下载后运行的？如果是这种情况的话，因为MAMapKit超过100MB，使用了git-lfs，导致你下载下去的MAMapKit其实是个指针文件，不是真实的高德二进制文件，所以会报找不到符号的错误。
在0.2.8版本中，我在README说明了一个运行example工程的变通方法，你可以查看一下。
