### ISSUE TITLE
界面跳转会导致AmapView的build()回调多次调用

### ISSUE THREAD

**Issue by javadickliu** [fluttify-project/amap_map_fluttify#200]
**插件版本**
  amap_map_fluttify: ^0.17.0
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
1.使用路由跳转到其他界面和返回当前界面的时候AmapView的build()方法都会再次调用
，导致地图白屏.
Navigator.push(context, CustomRouteZoom(LoginPage()));
**复现步骤**

**期望行为**

**截图**

**flutter doctor**
[√] Flutter (Channel master, v1.13.3-pre.13, on Microsoft Windows [Version 10.0.18362.720], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 3.6)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

**Comment by hidetag** [comment]
同款问题，因为最近 iOS 13.1 左右版本无法运行，所以只能在 Android 上测试，但从 0.12 左右版本开始一直到现在 0.18 版本，有概率出现白屏：
1.上个界面返回到带有地图的界面，概率白屏
2.app 退居后台(moveTaskToBack())后再唤起，概率白屏

**Comment by li305263** [comment]
同款问题..
还有个问题 初始化只要一次吗?
我多个页面都调地图插件还会闪退

**Comment by hidetag** [comment]
Duplicate of #207

**Comment by hidetag** [comment]
怀疑和 #207 类似。
iOS 没有似乎不会白屏，但 iOS 存在的问题是从上个地图界面返回这个地图界面后，marker 无法点击，地图点击也不会响应，只有重新添加 marker 才能继续点击一次。会不会是 android 返回上级界面后 build 被调用所以可能白屏，marker 能点击，iOS 返回上级界面后 build 没被调用所以没遇到白屏，marker 点击失效
