### ISSUE TITLE
Xcode在Archive阶段出错（真机和模拟机都是vscode环境运行正常）

### ISSUE THREAD

**Issue by WxxShirley** [fluttify-project/amap_map_fluttify#205]
**插件版本**
 amap_map_fluttify: ^0.17.13+767ea66
  amap_search_fluttify: ^0.7.4+356f11c
**遇到bug的平台(Android/iOS)**
iOS , IDE: **XCode 11.4**
**描述bug**
（因为我这app已经开发得差不多了，准备在app store上上架）
在Archive阶段出错：Module 'amap_core_fluttify' not found
其实用Xcode运行的时候也会出现这个错误，用vscode倒不会

**截图**
![image](https://user-images.githubusercontent.com/48085932/77774472-1779ac80-7086-11ea-8d94-0361e5a48e82.png)

**Comment by yohom** [comment]
建议根据flutter官网介绍的app store发布流程来进行，有可能需要一些特殊的步骤。

**Comment by WxxShirley** [comment]
解决了，在product -> archive阶段应该是打开 ios/workspace 。
抱歉。

**Comment by zjl801** [comment]
> 解决了，在product -> archive阶段应该是打开 ios/workspace 。
> 抱歉。

请问您说的“打开 ios/workspace ”指的是怎么个打开法？在那里打开？谢谢，我也是同样的问题
