### ISSUE TITLE
iOS marker 无法响应点击事件

### ISSUE THREAD

**Issue by hidetag** [fluttify-project/amap_map_fluttify#207]
**插件版本**
0.18.3+ddeef69
**遇到bug的平台(Android/iOS)**
iOS
**描述bug**
批量添加了 marker，marker 点击事件只有第一次进入地图界面才有效，并且只能点击其中任意一个，响应这次点击事件后再回到此地图界面，所有 marker 点击事件均无法响应，只有杀掉 app 重启后才能又重复上述操作
**复现步骤**
批量添加了 marker，marker 点击事件只有第一次进入地图界面才有效，并且只能点击其中任意一个，响应这次点击事件后再回到此地图界面，所有 marker 点击事件均无法响应，只有杀掉 app 重启后才能又重复上述操作
**期望行为**
可以点击 marker，像 Android 一样正常
**截图**

**flutter doctor**
一切 ok，稳定版

**Comment by hidetag** [comment]
找到问题点了：
Future<void> _onMarkerClick(Marker marker) async {
     Router.push("page").then((value){  // do something  });
}
这种方式下处理点击事件，第一次可以，后续都不行，目测 _onMarkerClick 被挂起了，导致无法响应后续点击事件。。
如果是：
Future<void> _onMarkerClick(Marker marker) async {
     showToast("toast");
}
这种方式下，点击事件一切正常....

@yohom

**Comment by hidetag** [comment]
定位复现步骤了：
iOS 下在界面一点击任意 marker 跳转界面二，如果界面二也有 MapView，此时返回界面一后，任一 marker 点击事件都不会生效了；但如果界面二没有用到地图，返回界面一后任一 marker 的点击事件依然能生效
@yohom

**Comment by yohom** [comment]
我往develop分支推送了更新代码来处理这个问题，你试一下依赖develop分支测试一下是否已解决。 @hidetag 如果可以的话我再更新一个版本。

**Comment by hidetag** [comment]
好的，我稍候试试看

**Comment by hidetag** [comment]
已测试，可用 @yohom  thx

**Comment by hidetag** [comment]
现在 marker 问题修复了，但，，白屏问题超级严重，只要一运行起来，哪怕是静置在那不动 app，几秒后自动白屏，无法用了
Duplicate of 200#
还是回退到之前的版本算了，iOS marker 无法点击的问题我之前修复过，就是返回界面时 clearMarkers，然后重新 add，虽然这样做界面的 markers 会闪现一下，但没办法。。
