### ISSUE TITLE
创建两个AmapView会有bug

### ISSUE THREAD

**Issue by li305263** [fluttify-project/amap_map_fluttify#209]
**插件版本**
0.17.16+b961bcc
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
home页面创建一个，路由跳转第三个页面创建一个，返回上一页面会报错
**复现步骤**
home页面创建一个，路由跳转第三个页面创建一个，返回上一页面会报错
**期望行为**
不报错
![aefed1f28e483a7d2b0236db3526a25](https://user-images.githubusercontent.com/12217674/78223099-e7ecf900-74f8-11ea-83bf-b5b99c04de91.png)

**Comment by yohom** [comment]
报什么错？

**Comment by li305263** [comment]
> 报什么错？
图片能看到吗 我上传了

**Comment by yohom** [comment]
可以提供一个可以复现bug的工程吗

**Comment by SunLongbri** [comment]
该问题是怎么解决的呢？我也是返回上一个带有地图的页面，报错信息一样。
