### ISSUE TITLE
在地图创建完成的生命周期中添加点/线会报错

### ISSUE THREAD

**Issue by q869939686** [fluttify-project/amap_map_fluttify#21]
**插件版本**
0.3.0
**描述bug**
在地图创建完成的生命周期中添加点/线会报错
![image](https://user-images.githubusercontent.com/29123332/67932281-88638800-fbfe-11e9-9959-eecad157f471.png)
**复现步骤**
可能会有这种需求，通过路由传参跳转到地图页面，想通过参数同步生成点/线，而不通过网络请求之后再异步生成，因为异步请求可能会有延迟
**期望行为**
如果可以的话希望增加更多生命周期
**截图**
![image](https://user-images.githubusercontent.com/29123332/67932329-a7fab080-fbfe-11e9-8efc-a6addd24cec9.png)

**flutter doctor**

**Comment by yohom** [comment]
你在你上面截图里的`// 禁用旋转`等方法前面，加一下`await`，保证dart这边的调用顺序是从上往下的，这样试试看还会不会报错。@q869939686

**Comment by q869939686** [comment]
谢谢了，可以了
