### ISSUE TITLE
marker响应点击报错

### ISSUE THREAD

**Issue by WxxShirley** [fluttify-project/amap_map_fluttify#212]
**插件版本**
amap_map_fluttify: ^0.19.1+b2681d9
**遇到bug的平台(Android/iOS)**
iOS

**复现步骤**
调用了setMarkerClickedListener, 我想实现的逻辑是点击后有底部弹窗，但是会出现marker上方的toast。我就把toast的内容修改为一个字符串，然后就报错了。
```dart
Future<void> _onMarkerClick(Marker marker) async{
    toast("Microsoft Suzhou");
  }
```

**截图**
![image](https://user-images.githubusercontent.com/48085932/78557884-34f80480-7844-11ea-84f3-9cf89d49e83e.png)
![image](https://user-images.githubusercontent.com/48085932/78557905-3de8d600-7844-11ea-92d5-501e25b654a0.png)

**flutter doctor**
all ok

**Comment by yohom** [comment]
你这个是OKToast没用对，你要在最外层套OkToast widget。

**Comment by yohom** [comment]
跟地图没什么关系，我先关闭了。

**Comment by WxxShirley** [comment]
ohhh 抱歉😅😅😅
