### ISSUE TITLE
AmapSearch 地址解析错误  地图空白

### ISSUE THREAD

**Issue by CcSimple** [fluttify-project/amap_map_fluttify#213]
**插件版本**
amap_search_fluttify 0.8.2+1
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
E/libEGL (27534): eglCreateWindowSurface: native_window_api_connect (win=0x55859973e0) failed (0xffffffed) (already connected to another API?)
E/libEGL (27534): eglCreateWindowSurface:456 error 3003 (EGL_BAD_ALLOC)
W/System.err(27534): **com.amap.api.services.core.AMapException: IO 操作异常 - IOException**
W/System.err(27534): at com.amap.api.services.a.a.g(BasicHandler.java:169)
W/System.err(27534): at com.amap.api.services.a.a.c(BasicHandler.java:116)
W/System.err(27534): at com.amap.api.services.a.av.getFromLocation(GeocodeSearchCore.java:86)
W/System.err(27534): at com.amap.api.services.a.av$1.run(GeocodeSearchCore.java:144)
W/System.err(27534): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err(27534): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err(27534): at java.lang.Thread.run(Thread.java:818)
D/java-callback(27534): fluttify-java-callback: onRegeocodeSearched(null1902)
I/flutter (27534): fluttify-dart-callback: onRegeocodeSearched(['var2':{var2: 1902, var1: null}[var2]])
I/flutter (27534): onRegeocodeSearched::kNativeObjectPool: {com_amap_api_maps_AMapOptions{refId: 255043341}, com_amap_api_maps_model_LatLng{refId: 116541122}, com_amap_api_maps_model_CameraPosition{refId: 46361811}, com_amap_api_maps_AMap{refId: 38735871}, com_amap_api_maps_UiSettings{refId: 137149226}, com_amap_api_maps_model_MyLocationStyle{refId: 143568155}, com_amap_api_maps_model_CameraPosition{refId: 249897609}, com_amap_api_maps_model_CameraPosition{refId: 118203022}, com_amap_api_maps_model_LatLng{refId: 827346211}, com_amap_api_services_core_LatLonPoint{refId: 158531460}, com_amap_api_services_geocoder_RegeocodeQuery{refId: 65614701}, com_amap_api_services_geocoder_GeocodeSearch{refId: 66230633}, android_location_Location{refId: 108692157}, com_amap_api_maps_model_LatLng{refId: 183782517}, com_amap_api_maps_model_CameraPosition{refId: 68670587}, com_amap_api_maps_model_CameraPosition{refId: 200718038}, com_amap_api_maps_CameraUpdate{refId: 54869335}, com_amap_api_maps_model_CameraPosition{refId: 58681954}, com_amap_ap
I/flutter (27534): fluttify-dart: com.amap.api.services.geocoder.RegeocodeResult@null::getRegeocodeAddress([])
W/System.err(27534): **java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference**
W/System.err(27534): at me.yohom.amap_search_fluttify.sub_handler.SubHandler4$1.lambda$new$141(SubHandler4.java:4945)
W/System.err(27534): at me.yohom.amap_search_fluttify.sub_handler.-$$Lambda$SubHandler4$1$5OrY_smv79B4KSZNsfcz66QzllM.call(lambda)
W/System.err(27534): at me.yohom.amap_search_fluttify.AmapSearchFluttifyPlugin.onMethodCall(AmapSearchFluttifyPlugin.java:158)
W/System.err(27534): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
W/System.err(27534): at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
W/System.err(27534): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
W/System.err(27534): at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(27534): at android.os.MessageQueue.next(MessageQueue.java:323)
W/System.err(27534): at android.os.Looper.loop(Looper.java:141)
W/System.err(27534): at android.app.ActivityThread.main(ActivityThread.java:5603)
W/System.err(27534): at java.lang.reflect.Method.invoke(Native Method)
W/System.err(27534): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
W/System.err(27534): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
E/flutter (27534): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] **Unhandled Exception: PlatformException(Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null)**
E/flutter (27534): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (27534): #1 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (27534):
E/flutter (27534): #2 com_amap_api_services_geocoder_RegeocodeResult.getRegeocodeAddress (package:amap_search_fluttify/src/android/com/amap/api/services/geocoder/RegeocodeResult.g.dart:104:77)
E/flutter (27534): #3 _AndroidSearchListener.onRegeocodeSearched (package:amap_search_fluttify/src/facade/amap_search.dart:1096:31)
E/flutter (27534): #4 com_amap_api_services_geocoder_GeocodeSearch.setOnGeocodeSearchListener. (package:amap_search_fluttify/src/android/com/amap/api/services/geocoder/GeocodeSearch.g.dart:123:21)
E/flutter (27534): #5 MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
E/flutter (27534): #6 MethodChannel.setMethodCallHandler. (package:flutter/src/services/platform_channel.dart:370:54)
E/flutter (27534): #7 _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
E/flutter (27534): #8 _invoke3. (dart:ui/hooks.dart:303:15)
E/flutter (27534): #9 _rootRun (dart:async/zone.dart:1126:13)
E/flutter (27534): #10 _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (27534): #11 _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (27534): #12 _invoke3 (dart:ui/hooks.dart:302:10)
E/flutter (27534): #13 _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)
复现步骤
**逆地址解析后 setState 地图空白， 可能是这里的问题**
**java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference**
**Unhandled Exception: PlatformException(Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null)**
期望行为

截图

**flutter doctor**
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
✗ Flutter plugin not installed; this adds Flutter specific functionality.
✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

**Comment by CcSimple** [comment]
记过多次测试， 发现AmapView 会因为尺寸变化而变空白。

**Comment by hidetag** [comment]
白屏太常见了。。比如现在

![bug](https://user-images.githubusercontent.com/15097928/78853294-1dda3200-7a51-11ea-8363-0bb86a558ce3.jpg)
