### ISSUE TITLE
图片覆盖物

### ISSUE THREAD

**Issue by yuanThink** [fluttify-project/amap_map_fluttify#214]
**功能描述**
图片覆盖物
图片覆盖物类为 MAGroundOverlay，可完成将一张图片以合适的大小贴在地图指定的位置上的功能。
**Native端对应字段/方法**
https://lbs.amap.com/api/ios-sdk/guide/draw-on-map/draw-plane

添加图片覆盖物的步骤如下：
（1） 在ViewController.m的viewDidLoad方法中根据范围和图片构造图片覆盖物。
Objective-C	Swift
- (void) viewDidLoad
{
    MACoordinateBounds coordinateBounds = MACoordinateBoundsMake(CLLocationCoordinate2DMake
(39.939577, 116.388331),CLLocationCoordinate2DMake(39.935029, 116.384377));
    
    MAGroundOverlay *groundOverlay = [MAGroundOverlay groundOverlayWithBounds:coordinateBounds icon:[UIImage imageNamed:@"GWF"]];
    
    [_mapView addOverlay:groundOverlay];
    _mapView.visibleMapRect = groundOverlay.boundingMapRect;
}
（2） 实现<MAMapViewDelegate>协议中的mapView:rendererForOverlay:回调函数，以在地图上显示图片覆盖物。
Objective-C	Swift
- (MAOverlayRenderer *)mapView:(MAMapView *)mapView rendererForOverlay:(id<MAOverlay>)overlay
{
    if ([overlay isKindOfClass:[MAGroundOverlay class]])
    {
        MAGroundOverlayRenderer *groundOverlayRenderer = [[MAGroundOverlayRenderer alloc] initWithGroundOverlay:overlay];
        
        return groundOverlayRenderer;
    }

    return nil;
}

**Comment by yohom** [comment]
有急需可以新开[技术支持工单](https://github.com/fluttify-project/technical-support-plan/issues/new/choose), 关于技术支持详见[technical-support-plan](https://github.com/fluttify-project/technical-support-plan).
