### ISSUE TITLE
初始化设置高德Key无效，调用定位等功能鉴权错误Key值为空

### ISSUE THREAD

**Issue by Chanow** [fluttify-project/amap_map_fluttify#215]
**插件版本**
amap_all_fluttify: ^0.13.1+1
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
初始化高德Key日志成功打印设置Key成功，但是调用定位等功能时又会弹出鉴权错误信息窗口，
前几天未加入获取当前定位城市时，地图定位添加标记等功能均无问题，前天添加该功能后真机调试、模拟机调试也均无问题，但打包之后无法实现、且再次进行真机调试等就会弹出鉴权错误信息窗口显示key值为空
**复现步骤**
1.在main.dart里调用AmapService.init()方法设置高德Key值
2.日志成功打印com.amap.api.maps.MapsInitializer::setApiKey(['var0':高德Key])
3.调用添加标记功能
4.打印鉴权错误信息窗口且key值为空
**期望行为**
定位、添加标记等实现
**截图**
![TIM截图20200415094247](https://user-images.githubusercontent.com/40227095/79290653-48b80080-7eff-11ea-8fcf-c4df60eb1b9f.png)
**flutter doctor**
![flutter](https://user-images.githubusercontent.com/40227095/79290722-78ff9f00-7eff-11ea-852e-eecddb8b8785.png)

**Comment by yohom** [comment]
用到定位和搜索的包时，要在AndroidManifest里配置key。

**Comment by Chanow** [comment]
> 用到定位和搜索的包时，要在AndroidManifest里配置key。

感谢，已经解决了！
