### ISSUE TITLE
能否增加MyLocationOption 中，设置定位图标的宽和高的属性。

### ISSUE THREAD

**Issue by SunLongbri** [fluttify-project/amap_map_fluttify#216]
**功能描述**
能否增加MyLocationOption 中，设置定位图标的宽和高的属性。

**Native端对应字段/方法**
  MyLocationOption({
    this.show = true,
    this.myLocationType = MyLocationType.Locate,
    this.interval = Duration.zero,
    this.iconUri,
    this.imageConfiguration,
    this.strokeColor,
    this.strokeWidth,
    this.fillColor,
  }) :

**Comment by yohom** [comment]
0.23.0以上版本，图片已经可以自适应，ios端不会出现模糊出现了。
