### ISSUE TITLE
建议增加加载在线瓦片数据的功能

### ISSUE THREAD

**Issue by louyanqi** [fluttify-project/amap_map_fluttify#217]
**功能描述**
https://blog.csdn.net/xiaolaohuqwer/article/details/71583651
**Native端对应字段/方法**
UrlTileProvider

**Comment by yohom** [comment]
有急需可以新开[技术支持工单](https://github.com/fluttify-project/technical-support-plan/issues/new/choose), 关于技术支持详见[technical-support-plan](https://github.com/fluttify-project/technical-support-plan).

**Comment by yohom** [comment]
专业版已实现在线瓦片图功能，如有需要请联系qq 382146139 :)
