### ISSUE TITLE
ios编译失败

### ISSUE THREAD

**Issue by Xue-Wenbin** [fluttify-project/amap_map_fluttify#218]
[!] CocoaPods could not find compatible versions for pod "AMapFoundation":
      In Podfile:
        amap_core_fluttify (from `.symlinks/plugins/amap_core_fluttify/ios`) was resolved to 0.0.1, which depends on
          AMapFoundation (~> 1.6)

    None of your spec sources contain a spec satisfying the dependency: `AMapFoundation (~> 1.6)`.

**Comment by yohom** [comment]
pod repo update
