### ISSUE TITLE
IOS设备Marker会莫名消失

### ISSUE THREAD

**Issue by q869939686** [fluttify-project/amap_map_fluttify#22]
**插件版本**
0.3.0
**描述bug**
1.
此时有一个Marker
![image](https://user-images.githubusercontent.com/29123332/67938813-3117e480-fc0b-11e9-967f-3a4ef71659d1.png)
划着划着点消失了
![image](https://user-images.githubusercontent.com/29123332/67938854-44c34b00-fc0b-11e9-95bc-46531ff5ae0e.png)
2.
绑定点击事件不成功，但是用户位置会被绑定上点击事件
![image](https://user-images.githubusercontent.com/29123332/67938935-72a88f80-fc0b-11e9-9176-83833244e47d.png)
自定义的Marker无法绑定上事件
**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
develop分支已经处理了第一个bug，独立的issue最好还是单独开。@q869939686

**Comment by q869939686** [comment]
好的，谢谢回复
