### ISSUE TITLE
地图界面重复退出-进入的步骤有很大几率会白屏

### ISSUE THREAD

**Issue by SuperZiLu** [fluttify-project/amap_map_fluttify#220]
**插件版本**
0.21.0-dev.3（另外项目里还集成了amap_location_fluttify版本：0.11.0）

**遇到bug的平台(Android/iOS)**
iOS（iphonex 13.3.1）

**描述bug**
重复点击按钮进入地图界面除了第一次，其他时候有很大几率白屏

**复现步骤**
进入地图界面然后退出再次进入就有很大几率白屏了,没有的话可重复多次。

**期望行为**
每次进入地图界面都能正常显示

**截图**
错误的：
![image](https://user-images.githubusercontent.com/30061527/80301023-f5359480-87d3-11ea-9781-65a2a5d20764.png)

正常的：
![image](https://user-images.githubusercontent.com/30061527/80301034-0088c000-87d4-11ea-84b1-2356bb345c98.png)

错误显示的时候点击地图获取到的经纬度log：
![image](https://user-images.githubusercontent.com/30061527/80301047-23b36f80-87d4-11ea-9014-2559ed05a6c3.png)

**flutter doctor**
![image](https://user-images.githubusercontent.com/30061527/80301102-a805f280-87d4-11ea-9c02-87dd6bcdf04a.png)

**Comment by yohom** [comment]
是不是你的经纬度有问题？看上去全都是0。你缩放看看是不是跑非洲去了。

**Comment by SuperZiLu** [comment]
> 是不是你的经纬度有问题？看上去全都是0。你缩放看看是不是跑非洲去了。

这个经纬度是他白屏的时候 我点屏幕 打印出来的log 不是因为经纬度导致白屏 是因为白屏导致经纬度错误。

**Comment by SuperZiLu** [comment]
最后我把插件换成了 amap_all_fluttify,问题就解决了，就是这么神奇。
