### ISSUE TITLE
NO-IDFA支持

### ISSUE THREAD

**Issue by mentalmap** [fluttify-project/amap_map_fluttify#221]
**功能描述**
因为App Store上线时的IDFA问题，能不能提供什么选项可以选择依赖AMap3DMap-NO-IDFA，而不是AMap3DMap呢？

**Comment by yohom** [comment]
我增加了NO-IDFA分支，你要的话开[技术支持工单](https://github.com/fluttify-project/technical-support-plan/issues/new/choose)我给你提供，关于技术支持，详见[technical-support-plan](https://github.com/fluttify-project/technical-support-plan)。

**Comment by yohom** [comment]
已开放feature/NO-IDFA分支。
