### ISSUE TITLE
如何移除掉某一个marker

### ISSUE THREAD

**Issue by shoudengren** [fluttify-project/amap_map_fluttify#223]
目前我查看api只有一个clear以及clearMarkers，如果我想要移除掉某一个marker有没有api。
如果没有的话，是不是每次都要clearMarkers然后在重新addMarkers

**Comment by yohom** [comment]
https://github.com/fluttify-project/amap_map_fluttify/blob/9e58225e3b78b0c12b238d2031f66bf6d00ef2fd/lib/src/facade/models.dart#L535
