### ISSUE TITLE
首次打开地图页面黑屏，需要通过屏幕锁屏-解锁，方可正常显示地图

### ISSUE THREAD

**Issue by theecn** [fluttify-project/amap_map_fluttify#224]
**插件版本**
0.21.0
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
##### 测试手机：vivoX20A
bug描述：debug 版本、release版本在首次加载地图时，都会出现黑屏的情况，添加maskDelay,也无法正常显示地图，需要锁定屏幕，然后再唤醒，才能正常显示地图（仅第一次加载需要这个操作）。
##### 代码如下
![image](https://user-images.githubusercontent.com/22100544/81057401-e8fdb580-8efe-11ea-9717-189a593ffdc4.png)

**复现步骤**

**期望行为**
正常显示地图
**截图**
![image](https://user-images.githubusercontent.com/22100544/81057435-f450e100-8efe-11ea-8007-84d5411ac56e.png)
![image](https://user-images.githubusercontent.com/22100544/81060228-9e7f3780-8f04-11ea-86a1-b5e3cc3961ef.png)

**flutter doctor**
![image](https://user-images.githubusercontent.com/22100544/81057566-41cd4e00-8eff-11ea-8121-41644a5315bf.png)

**Comment by wkzz31** [comment]
同样的问题，oppo和vivo手机会出现首次安装打开后，地图会是黑的。当home到桌面再打开app时，地图会显示正常。 @yohom 可以帮忙定位一下问题吗

**Comment by TshineZheng** [comment]
我这里也出现这个情况
