### ISSUE TITLE
地图widget遮挡侧边栏弹出层

### ISSUE THREAD

**Issue by awagege** [fluttify-project/amap_map_fluttify#228]
**插件版本**
0.22.0
**遇到bug的平台(Android/iOS)**
ios
**描述bug**
地图widget遮挡侧边栏弹出层
**复现步骤**
scaffold加入endDrawer，且body中放入amapview即可复现
**期望行为**

**截图**
<img width="395" alt="WX20200508-213754@2x" src="https://user-images.githubusercontent.com/26294948/81410966-359df680-9174-11ea-9b55-9ac4ca80ff6f.png">

**flutter doctor**
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.0)
[✓] Connected device (1 available)

**Comment by yohom** [comment]
1.17.0还没有适配，建议先留在1.12.13观望一段时间，我这个月底或下个月初会进行适配。

**Comment by awagege** [comment]
我还没测试过1.12.13是否也遮挡

**Comment by BugSir** [comment]
> 1.17.0还没有适配，建议先留在1.12.13观望一段时间，我这个月底或下个月初会进行适配。

https://github.com/flutter/flutter/issues/56660 跟这个问题一样，view每次重新创建导致的。

**Comment by BugSir** [comment]
@yohom 
flutter/flutter#56660 跟这个问题一样，view每次重新创建导致的。修改完后模拟器当前位置也不会一直是北京了。

**Comment by scottlaw** [comment]
> @yohom
> [flutter/flutter#56660](https://github.com/flutter/flutter/issues/56660) 跟这个问题一样，view每次重新创建导致的。修改完后模拟器当前位置也不会一直是北京了。

很棒的解决方案。

**Comment by yohom** [comment]
使用0.22.2以上的版本
