### ISSUE TITLE
flutter pub get  amap_map_fluttify: ^0.3.1+70bd548 失败

### ISSUE THREAD

**Issue by lyy1005664097** [fluttify-project/amap_map_fluttify#23]
Because flutter_yunwei depends on amap_map_fluttify ^0.3.1+70bd548 which doesn't match any versions, version sol
ving failed.

![image](https://user-images.githubusercontent.com/46982041/67995838-901b3f00-fc87-11e9-8035-353b31ff5aa5.png)

**Comment by yohom** [comment]
这个我也感觉很奇怪，可能是pub有延迟，你可以先直接依赖github。 @lyy1005664097

**Comment by lyy1005664097** [comment]
好的
