### ISSUE TITLE
【闪退代码已定位】iOS地图加入自定义Widget，进入页面快速返回闪退

### ISSUE THREAD

**Issue by WeiQiZhang** [fluttify-project/amap_map_fluttify#231]
**插件版本**
0.22.0
**遇到bug的平台(Android/iOS)**
iOS
**描述bug**
iOS地图加入自定义Widget，进入页面快速返回闪退，代码定位

PlatformService.m line72 objc_setAssociatedObject方法的target为空

PlatformService.m line150 objc_setAssociatedObject方法的target为空

MAMapViewFactory.m line804 [annotations addObject:item];的item为空

我暂时判空可修复问题，具体问题只能等大佬来定位了..

**Comment by kennenfromchina** [comment]
请问你解决这个问题了吗？
