### ISSUE TITLE
热重载地图白屏

### ISSUE THREAD

**Issue by zhoutengshen** [fluttify-project/amap_map_fluttify#232]
**插件版本**
^5.0.0+hotfix.5

**遇到bug的平台(Android/iOS)**
Android

**描述bug**
在 as 下 按保存 进行热重载的时候地图会变成空白。这个问题只在开发环境出现。
仓库里面的例子也会出现这个问题。

**复现步骤**
发生热重载即可复现

**期望行为**
期望在代码热重载的时候不会空白

**截图**
![bug](https://user-images.githubusercontent.com/26021548/81549550-7df62800-93b1-11ea-996d-2c2f266c83b9.gif)

**flutter doctor**
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.535], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!

代码:
```
Container(
    height: 500,
    width: 300,//====>>>>更改高度或者宽度，按保存地图又出现了，在按保存地图白屏
    child: AmapView(
      ),
);
```

**Comment by yohom** [comment]
使用`0.22.3-dev.0`以上版本试一下，用TextureMapView代替了MapView，目前测试hot reload不会出现白屏了。

**Comment by zhoutengshen** [comment]
> 使用`0.22.3-dev.0`以上版本试一下，用TextureMapView代替了MapView，目前测试hot reload不会出现白屏了。

问题已经解决了
