### ISSUE TITLE
能问一下各个系统的兼容性吗？

### ISSUE THREAD

**Issue by jiyangjjj** [fluttify-project/amap_map_fluttify#233]
客户反映和实测发现，引入后有些低版本的android和ios系统会产生冲突闪退的现象，想了解一下各个版本的兼容性方面以确认是我们的问题还是插件的问题……

**Comment by yohom** [comment]
低版本是多低？闪退又有什么日志？

**Comment by jiyangjjj** [comment]
> 低版本是多低？闪退又有什么日志？

之前是安卓7和ios11都会闪退，现在在编译的过程中都报androidX冲突什么的了，估计是我们项目的问题了……
