### ISSUE TITLE
适配permission_handler 5

### ISSUE THREAD

**Issue by zzlhr** [fluttify-project/amap_map_fluttify#234]
**插件版本**
0.22.2
**遇到bug的平台(Android/iOS)**
android

**描述bug**
The use of `permission_handler: ^5.0.0+hotfix.6 ` is 
```dart
if (await Permission.location.request().isGranted) {
    return true;
  } else {
    Toast.show('需要定位权限！');
    return false;
  }
```

**复现步骤**
update permission_handler to ^5.0.0+hotfix.6

**期望行为**
update permission_handler
**截图**

**flutter doctor**

**Comment by yohom** [comment]
这个没有适配不适配的，插件本身没有使用这个插件，只是example工程使用了一下，不影响插件本身。
