### ISSUE TITLE
IOS使用widget marker时，marker大小缩放有问题

### ISSUE THREAD

**Issue by ykrank** [fluttify-project/amap_map_fluttify#237]
**插件版本**
^0.22.2

**遇到bug的平台(Android/iOS)**
IOS

**描述bug**
IOS使用widget marker时，marker大小缩放有问题，2倍分辨率的手机上会显示为实际大小的两倍。
Android没问题。

**Comment by yohom** [comment]
这个是UiKitView的bug，你可以通过设置MarkerOption(:width:height)来避免。

**Comment by yohom** [comment]
0.23.0-dev.0以上版本试一下。
