### ISSUE TITLE
当有地图未销毁时调用输入框，部分手机会 oom 闪退

### ISSUE THREAD

**Issue by hidetag** [fluttify-project/amap_map_fluttify#238]
**插件版本**
任何版本
**遇到bug的平台(Android/iOS)**
只测试了 android，iOS 未知
**描述bug**
进入 app 后，app 首页是个地图，此时打开新界面，新界面上只有一个输入框。在 小米8 MIUI12 上界面会闪屏黑屏，在 vivo 和华为部分手机上，键盘刚弹出就卡死 oom。如将地图控件替换为其他控件则不会有这个问题，另外如果地图调用了 dispose 也不会出现上述情况。
简单地说：在 app 的路由栈内，某个或者某几个界面持有未销毁的地图，后续呼出（收起）输入框均会出现问题，在我的小米上黑屏闪烁是必现，在 vivo 上 oom 闪退几乎是必现

**Comment by yohom** [comment]
试下在有地图的页面，Scaffold都配置一下resizeToAvoidBottomInset: false

**Comment by hidetag** [comment]
OK，我试一下

**Comment by hidetag** [comment]
已解决，thx
