### ISSUE TITLE
setCenterCoordinate 的动画问题

### ISSUE THREAD

**Issue by AOWOAO** [fluttify-project/amap_map_fluttify#24]
**插件版本**
0.3.1+70bd548

**描述bug**
setCenterCoordinate 的动画没有过渡效果

**复现步骤**

**期望行为**

**截图**
![微信截图_20191101104737](https://user-images.githubusercontent.com/25810208/67998905-1427f380-fc95-11e9-9533-16a3d481075e.png)
![ttt](https://user-images.githubusercontent.com/25810208/67998917-1e49f200-fc95-11e9-9462-a366ba171c79.gif)

**flutter doctor**

**Comment by yohom** [comment]
develop分支已修复 @AOWOAO
