### ISSUE TITLE
iOS Marker点击事件失效

### ISSUE THREAD

**Issue by HongWeiChen** [fluttify-project/amap_map_fluttify#240]
具体原因：

flutter: type 'List<MAAnnotationView>' is not a subtype of type 'MAAnnotationView'
flutter: #0      AmapController.addMarkers.<anonymous closure> (package:amap_map_fluttify/src/facade/amap_controller.dart:1038:33)
<asynchronous suspension>
#1      AmapController.addMarkers.<anonymous closure> (package:amap_map_fluttify/src/facade/amap_controller.dart)
#2      platform (package:foundation_fluttify/src/function/functions.dart:27:23)
#3      AmapController.addMarkers (package:amap_map_fluttify/src/facade/amap_controller.dart:932:12)
<asynchronous suspension>
#4      _AmapViewState._initIOS (package:amap_map_fluttify/src/facade/amap_view.widget.dart:327:28)
<asynchronous suspension>
#5      _AmapViewState.build.<anonymous closure> (package:amap_map_fluttify/src/facade/amap_view.widget.dart:184:21)
#6      _MAMapView_iOSState._onViewCreated (package:amap_map_fluttify/src/ios/platformview/MAMapView.g.dart:58:27)
#7      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:635:35)
<asynchronous suspension>
#8      _UiKitViewState._initializeOnce (package:flutter/src/widgets/platform_view.dart:573:5)
#9      _UiKitViewState.didChangeDependencies (package:flutter/src/widgets/platform_view.dart:583:5)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4661:12)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#15     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
#18     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
#19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#21     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
#28     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
#29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3211:20)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
#33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#35     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
#36     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
#37     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
#38     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#39     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
#40     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
#41     _rootRun (dart:async/zone.dart:1184:13)
#42     _CustomZone.run (dart:async/zone.dart:1077:19)
#43     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#44     _invoke (dart:ui/hooks.dart:261:10)
#45     _drawFrame (dart:ui/hooks.dart:219:3)

**Comment by yohom** [comment]
0.23.0-dev.1试一下
