### ISSUE TITLE
centerCoordinate修改后调用setState,地图没有发生改变

### ISSUE THREAD

**Issue by 350887156** [fluttify-project/amap_map_fluttify#244]
**插件版本**
0.23.0
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
centerCoordinate修改后调用setState,地图没有发生改变
**复现步骤**
必现
**期望行为**
AmapView的所有参数都应该在被修改后及时刷新
**截图**

**flutter doctor**
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

**Comment by yohom** [comment]
使用AmapController类控制地图。参考example工程的写法。
