### ISSUE TITLE
Attempt to invoke virtual method 'void com.amap.api.maps.model.BasePointOverlay.remove()' on a null object reference

### ISSUE THREAD

**Issue by fangshengfy** [fluttify-project/amap_map_fluttify#245]
**插件版本**
  amap_all_fluttify: ^0.15.0
**遇到bug的平台(Android/iOS)**
Android
**描述bug**
在从第一个有地图的页面跳转到第二个有地图的页面，然后关闭第二个有地图的页面，在第一个页面调用所有marker的position，remove，object都会出现
Attempt to invoke virtual method 'void com.amap.api.maps.model.BasePointOverlay.remove()' on a null object reference

**Comment by fangshengfy** [comment]
如果是跳转到没有地图的页面就不会出现问题

**Comment by fangshengfy** [comment]
[https://github.com/fluttify-project/amap_map_fluttify/issues/207](url) 可能跟这个问题比较像，但我遇到的问题是 点击事件能触发但_markers数组里面的marker 调用remove都会提示marker为null

**Comment by fangshengfy** [comment]
我用example里面的进入二级页面也会出现这个问题

**Comment by momtboy** [comment]
我也遇到这个问题了，有什么解决办法嘛？

**Comment by SunLongbri** [comment]
我也遇到了，怎么解决的呢？
