### ISSUE TITLE
INVALID_USER_KEY 错误码：10001

### ISSUE THREAD

**Issue by manburenshenglu** [fluttify-project/amap_map_fluttify#248]
**插件版本**
最新版
**遇到bug的平台(Android)**
Android平台中
**描述bug**
即使在flutter的main.dart中设置了
await AmapService.init(
    iosKey: '你的iOS key',
    androidKey: '你的Android key',
  );
仍需要在原生Android目录下的AndroidManifest文件中添加
<meta-data
            android:name="com.amap.api.v2.apikey"
            android:value="你的key"></meta-data>
否则就会出现地图白屏，提示INVALID_USER_KEY用户key不存在或者过期

这个坑爬了2个小时，文档中没有提到，希望作者加上去，提示使用者。
iOS中不需要做其他处理
**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
![image](https://user-images.githubusercontent.com/10418364/84212674-14bd1e00-aaf1-11ea-93f8-1b279ebfb012.png)
如果依赖了定位和搜索插件，是需要配置AndroidManifest的
