### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by super-yolin** [fluttify-project/amap_map_fluttify#249]
**插件版本**
0.23.1

**遇到bug的平台(Android/iOS)**
IOS: iphone se 模拟器

**描述bug**
出现异常。
MissingPluginException (MissingPluginException(No implementation found for method MAMapView::set_showsUserLocation on channel me.yohom/amap_map_fluttify/MAMapView))

**复现步骤**
直接运行官方example工程,进入自定义地图,点击是否显示定位
使用了自己的合法高德key

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
0.23.2试一下

**Comment by super-yolin** [comment]
问题已解决
