### ISSUE TITLE
[feat] 可以访问海外地图吗

### ISSUE THREAD

**Issue by LoseRecall** [fluttify-project/amap_map_fluttify#25]
**功能描述**
希望添加海外地图

**Comment by yohom** [comment]
有高德对应api文档链接吗？高德支持就可以，不支持就不可以。

**Comment by LoseRecall** [comment]
http://a.amap.com/lbs/static/pdf/海外地图Android SDK V1.0.0.pdf
定位：http://lbs.amap.com/api/android-location-sdk/locationsummary/

以下为android海外地图开发包，请您通过钉盘查收。
https://space.dingtalk.com/s/gwHOAH_QRwLOGtuI1QPaACA4YmNiM2MzY2YzYjY0NTUwOWJhMzhlMzdjMjU2MzlhNA 密码: Rz6B

**Comment by pingxiaodou** [comment]
感谢作者的付出，请问海外地图有支持时间表吗 @yohom

**Comment by yohom** [comment]
有需求的可以开技术支持工单 https://github.com/fluttify-project/technical-support-plan/issues/new/choose
