### ISSUE TITLE
AMapCoordinateType 类型的值与高德SDK里的AMapCoordinateType 值不一致

### ISSUE THREAD

**Issue by ls-andy** [fluttify-project/amap_map_fluttify#250]
**插件版本**
0.23.1

**遇到bug的平台(Android/iOS)**
ios

**描述bug**
AMapCoordinateType 类型与高德地图原生SDK里的AMapCoordinateType 值不一致，导致使用到AMapCoordinateType的地方与原生的值不一致，会导致坐标系统错乱问题

**复现步骤**
1.使用纠偏功能，默认传的坐标类型是AMapCoordinateType.AMapCoordinateTypeAMap (取值是0)
2.纠偏的结果会出现整体偏移几百米

因为AMapCoordinateType这个类型是FLUTTIFY生成的，不好怎么修改。
本地规避方案：
amap_map_fluttify-0.23.1/lib/src/ios/MATraceManager.g.dart :119行的type.index改成type.index - 1

Dart enum取值从0开始
```dart
enum AMapCoordinateType {
  AMapCoordinateTypeAMap,
  AMapCoordinateTypeBaidu,
  AMapCoordinateTypeMapBar,
  AMapCoordinateTypeMapABC,
  AMapCoordinateTypeSoSoMap,
  AMapCoordinateTypeAliYun,
  AMapCoordinateTypeGoogle,
  AMapCoordinateTypeGPS
}
```

ios 高德地图SDK坐标系统从-1开始
```OC
///坐标类型枚举
typedef NS_ENUM(NSInteger, AMapCoordinateType)
{
    AMapCoordinateTypeAMap = -1,    ///<AMap
    AMapCoordinateTypeBaidu = 0,    ///<Baidu
    AMapCoordinateTypeMapBar,       ///<MapBar
    AMapCoordinateTypeMapABC,       ///<MapABC
    AMapCoordinateTypeSoSoMap,      ///<SoSoMap
    AMapCoordinateTypeAliYun,       ///<AliYun
    AMapCoordinateTypeGoogle,       ///<Google
    AMapCoordinateTypeGPS,          ///<GPS
};

```

**期望行为**
纠偏时传入Native的坐标系值正常

**截图**

**flutter doctor**

**Comment by yohom** [comment]
0.23.3-dev.0试一下，优化了枚举类型的处理。
