### ISSUE TITLE
使用widget添加marker不能正常显示

### ISSUE THREAD

**Issue by licc** [fluttify-project/amap_map_fluttify#252]
**插件版本**
  amap_map_fluttify: ^0.23.2

**遇到bug的平台(Android/iOS)**
 ios13.4.1

**描述bug**
 添加2个marker 使用 widget来显示网络图片，1.第一次添加不显示，2.多个marker的图片内容不正确，
**复现步骤**

`    MarkerOption(`
    `  latLng: LatLng(loc[0], loc[1]),`
    `  widget: new CircleAvatar(`
    `    radius: 25.0,`
      `  backgroundImage: ImageUtils.getAvatarImageProvider(dev["avatar"]),`
     ` ),
    `  title: "zs",  );`

**期望行为**
1.第一次加载图片正确2 .正确展示两个不同图片头像

**截图**
![image](https://user-images.githubusercontent.com/4024963/84281911-b719e780-ab6b-11ea-81be-c23b9612196b.png)

**flutter doctor**
 Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.2, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.5)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

**Comment by yohom** [comment]
网络图片加载需要时间，widget marker只能加载下一帧能渲染出来的图像。

**Comment by yohom** [comment]
可以先调用precacheImage(:image:context)来预加载图片到内存，这样widget中的Image就能够在一帧中绘制完成。

**Comment by Jinxishihenian** [comment]
> precacheImage(:image:context)

这个操作解决了我的问题。

**Comment by n305225282** [comment]
> 可以先调用precacheImage(:image:context)来预加载图片到内存，这样widget中的Image就能够在一帧中绘制完成。

解决了
