### ISSUE TITLE
如果添加markers的话 则无法定位，而且onMapCreated 方法也没调用，无法获取到controller，marker是显示在地图上的。一进去地图是显示在北京

### ISSUE THREAD

**Issue by qllqll** [fluttify-project/amap_map_fluttify#253]
**插件版本**
  amap_map_fluttify: ^0.23.2

**遇到bug的平台(Android/iOS)**
   iOS
**描述bug**
如果添加markers的话 则无法定位，而且onMapCreated 方法也没调用，无法获取到controller，marker是显示在地图上的。一进去地图是显示在北京
**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by guotong314** [comment]
遇到同样的问题

**Comment by shenyunyou** [comment]
我也遇到同样的问题

**Comment by bugs2** [comment]
开定位权限试试。
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
	<string>App需要您的同意，才能访问位置。</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>App需要您的同意，才能始终访问位置。</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>App需要您的同意，才能访问位置。</string>
