### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList com.amap.api.maps.AMap.addMarkers(java.util.ArrayList, boolean)' on a null object reference

### ISSUE THREAD

**Issue by qllqll** [fluttify-project/amap_map_fluttify#254]
**插件版本**

**遇到bug的平台(Android/iOS)**
Android
**描述bug**
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList com.amap.api.maps.AMap.addMarkers(java.util.ArrayList, boolean)' on a null object reference
**复现步骤**
在iOS中添加打点是好的 在Android 报这个错误
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList com.amap.api.maps.AMap.addMarkers(java.util.ArrayList, boolean)' on a null object reference

**期望行为**

**截图**

**flutter doctor**

**Comment by momtboy** [comment]
我也遇到这个问题了 报空指针了，大佬能出来解决一下嘛

**Comment by momtboy** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList com.amap.api.maps.AMap.addMarkers(java.util.ArrayList, boolean)' on a null object reference
W/System.err( 8312): 	at me.yohom.amap_map_fluttify.sub_handler.SubHandler13$1.lambda$new$195(SubHandler13.java:6848)
W/System.err( 8312): 	at me.yohom.amap_map_fluttify.sub_handler.-$$Lambda$SubHandler13$1$pdaY8fV_p1ckVJfoulP2hhen5Es.call(Unknown Source:0)
W/System.err( 8312): 	at me.yohom.amap_map_fluttify.AmapMapFluttifyPlugin.onMethodCall(AmapMapFluttifyPlugin.java:190)
W/System.err( 8312): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
W/System.err( 8312): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err( 8312): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
W/System.err( 8312): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 8312): 	at android.os.MessageQueue.next(MessageQueue.java:326)
W/System.err( 8312): 	at android.os.Looper.loop(Looper.java:189)
W/System.err( 8312): 	at android.app.ActivityThread.main(ActivityThread.java:7210)
W/System.err( 8312): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 8312): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
W/System.err( 8312): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)

**Comment by momtboy** [comment]
if (_cache.containsKey(iconUri.toString())) {
    debugPrint('命中缓存');
    imageData.complete(_cache[iconUri.toString()]);
  }

我尝试把这里代码注释以后，发现不从缓存取图片，就不会报错

**Comment by momtboy** [comment]
大佬，能出来解决一下嘛？版本现在已经升级到0.23.3-dev.2还是会出出现空指针的情况

**Comment by yohom** [comment]
onMapCreated回调里，稍微延迟几百毫秒再操作AmapController试一下。
