### ISSUE TITLE
能否自定义marker的infowindow

### ISSUE THREAD

**Issue by Gitldx** [fluttify-project/amap_map_fluttify#258]
**功能描述**
现在只能显示标题和副标题，是否可以再加一张图片

**Comment by yohom** [comment]
目前不能，而且阻力比较大，不太好实现。

**Comment by Gitldx** [comment]
我看见开发日志里有自定义infoWindow的记录了，不知道官方是否正式发布了接口。
我在ios（安卓没有试）下尝试了以下两种写法，好像还没有效果
1:controller.showCustomInfoWindow(_marker, Image.network("imgurl",height:100,width:100))
2、controller.showCustomInfoWindow(_marker, Container(child: Column(children: <Widget>[
  Text("text1"),
  Text("text2"),
  Image.network("imgurl")
])));

两种方式弹出的窗口都空白。是不是我调用的方式不对

**Comment by yohom** [comment]
`Image.network("imgurl",height:100,width:100))`不能在一帧内完成绘制，建议你先调用`precacheImage(:context:provider)`方法先把图片缓存在内存里再去调用`showCustomInfoWindow`.

**Comment by Gitldx** [comment]
按照示例中的代码，点击marker 是可以正确显示自定义窗口的，但有时候是希望系统加载完地图后就自己弹出框来，尽管我加了延迟显示，弹出来的依然是空白,不管加不加图片都一样空白
MarkerOption markerOption = MarkerOption(
                infoWindowEnabled: true,
                latLng: widget.initMarker,
                );
_marker = await controller.addMarker(markerOption);

Future.delayed(Duration(seconds: 5)).then((value) async{
              await _controller.showCustomInfoWindow(
                        _marker,
                        Container(
                          width: 128,
                          height: 222,
                          decoration: BoxDecoration(
                            color: Colors.yellow,
                            borderRadius: BorderRadius.circular(16),
                          ),
                          child: Column(children:[
                            Text("text1"),
                            Text("text2"),
                            Text("text3"),
                          ]),
                        ),
                      );
            });

fluttify现在越来越棒了  ^_^

**Comment by yohom** [comment]
已在专业版中提供。
