### ISSUE TITLE
stack布局加载地图出现地图穿透现象

### ISSUE THREAD

**Issue by LittleTadpole** [fluttify-project/amap_map_fluttify#259]
![image](https://user-images.githubusercontent.com/35562133/85384307-99894c80-b573-11ea-9fe0-93913093b9df.png)
上面是我的UI图, 之前写过Andorid原生,现在flutter重构.

之前做android原生开发,主页有四个Fragment,第1,2个Fragment都设置了地图,使用高德地图会出现地图穿透现象,在高德官方找到了解决办法(GlSurfaceView叠放会出现穿透现象，建议使用TextureMapView避免这个问题),链接https://lbs.amap.com/dev/demo/map-fragment#Android, 这个问题只有android有,IOS不存在.

现在我用flutter重写这个app,同样遇到了类似问题,设置完首页第一个地图后,第二个地图能显示,但是点击事件走的是首页的点击回调,不走当前地图的回调,而且一套代码,ios真机运行正常,还是只有android有这种穿透问题, 是不是也可以使用高德官方的解决?

**Comment by yohom** [comment]
你用的什么版本，0.23.0以上版本地图View实现已经改成TextureMapView。

**Comment by LittleTadpole** [comment]
我使用的amap_map_fluttify: ^0.23.2, 地图都能正常显示,就是第二个页面的点击事件会响应第一个的回调...哪怕我不设置点击事件,都走第一个页面的,ios运行正常,android才有这个问题..  我再琢磨琢磨吧

**Comment by LittleTadpole** [comment]
> 你用的什么版本，0.23.0以上版本地图View实现已经改成TextureMapView。

大佬,有地图长按回调吗? 我没有找到....
