### ISSUE TITLE
3.1版本编译失败

### ISSUE THREAD

**Issue by yanqiqi1996** [fluttify-project/amap_map_fluttify#26]
**截图**

![image](https://user-images.githubusercontent.com/31203049/68008516-2a947600-fcba-11e9-85a7-d1275d026795.png)
@yohom 大佬这是怎么回事 冲突了还是啥

**Comment by yohom** [comment]
`flutter packages upgrade; flutter packages get;`
如果升级出现新的错误，就去`$flutter_root/.pub-cache/hosted/pub.dartlang.org/`下删除旧版本的`foundation_fluttify`，剩一个最新的版本即可。

**Comment by yanqiqi1996** [comment]
谢谢  没问题了 羞愧
