### ISSUE TITLE
多个Marker使用iconProvider会导致用同一个图片

### ISSUE THREAD

**Issue by TshineZheng** [fluttify-project/amap_map_fluttify#262]
**插件版本**
amap_map_fluttify: ^0.23.3

**遇到bug的平台(Android/iOS)**
iOS

**描述bug**
onMapCreated 之后，调用_controller.addMarkers增加两个Marker，设置不同的iconProvider，两个Marker都会显示同一张图片。
使用老方法iconUri和imageConfiguration则正常。

**复现步骤**

**期望行为**
Marker显示各自的图片

**截图**

**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F96, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

**Comment by yohom** [comment]
0.23.4版本先试一下

**Comment by TshineZheng** [comment]
> 0.23.4-dev.0版本先试一下

正常了
