### ISSUE TITLE
大佬能帮忙看一下问题吗？

### ISSUE THREAD

**Issue by JackZhang1994** [fluttify-project/amap_map_fluttify#263]
**插件版本**

**遇到bug的平台(Android/iOS)**
Android
**描述bug**
调试可以正常运行，打Release包后，APP无法启动
**Logcat日志**
07-01 18:12:49.118 E/com.aaa.bbb(10240): Unknown bits set in runtime_flags: 0x20000
07-01 18:12:49.122 E/com.aaa.bbb(10240): Not starting debugger since process cannot load the jdwp agent.
07-01 18:12:49.164 I/com.aaa.bbb(10240): [GL_OOM] ClampGrowthLimit 268435456
07-01 18:12:49.164 I/com.aaa.bbb(10240): [GL_OOM] limited APP ClampGrowthLimit, set size to 268435456
07-01 18:12:49.467 I/com.aaa.bbb(10240): Method exceeds compiler instruction limit: 18984 in void me.yohom.amap_map_fluttify.AmapMapFluttifyPlugin$1.<init>(me.yohom.amap_map_fluttify.AmapMapFluttifyPlugin)
07-01 18:12:49.940 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.onething.minecloud-d8JZYlvCG2qGdun5zSIHIQ==/base.apk' is compressed.
07-01 18:12:49.977 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.sankuai.meituan-J22r66lOmncEW0A4IQ46hg==/base.apk' is compressed.
07-01 18:12:50.001 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.black.unique-6tX_xme02TkwkunGHganUA==/base.apk' is compressed.
07-01 18:12:50.032 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.dianping.v1-z1IIKVrsBSDL3B2xWUWS8Q==/base.apk' is compressed.
07-01 18:12:50.103 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/me.ele-VFV52DUxd584fsvi0hQz7w==/base.apk' is compressed.
07-01 18:12:50.113 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.xingin.xhs-Cfd-KaRf1tkvz6y4ymZSqA==/base.apk' is compressed.
07-01 18:12:50.125 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.tencent.mm-R6kNUYVvHaOZsqYoE3xPGA==/base.apk' is compressed.
07-01 18:12:50.177 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.shizhuang.duapp-nOWQ0WHKcafc1WT6ZQLSLQ==/base.apk' is compressed.
07-01 18:12:50.194 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.lufax.android-EsYQ_vbUDIovapYjxl_DXw==/base.apk' is compressed.
07-01 18:12:50.226 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.tencent.qqlive-Ic8W2xpKDz79YgKnFinjbQ==/base.apk' is compressed.
07-01 18:12:50.256 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.xunmeng.pinduoduo-zGPrNC2AHtmd3GzBiB011A==/base.apk' is compressed.
07-01 18:12:50.268 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.tencent.weread-39to2M0ZIhpOS4bl_XOlOg==/base.apk' is compressed.
07-01 18:12:50.276 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.tencent.wework-rjc98FYat5zfj7dg1y4Dzw==/base.apk' is compressed.
07-01 18:12:50.307 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.meituan.retail.v.android-Q8Bvs-hHx3sWqn33yEylTw==/base.apk' is compressed.
07-01 18:12:50.327 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.ss.android.article.lite-s1sciPngniW3X6ha5cyhpg==/base.apk' is compressed.
07-01 18:12:50.362 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.nearme.gamecenter-zdXgkZ8rm0Y30tbKcVuYXg==/base.apk' is compressed.
07-01 18:12:50.398 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.ss.android.ugc.aweme-0l4RnO7eZlo4PvfeY_apwA==/base.apk' is compressed.
07-01 18:12:50.434 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.gotokeep.keep-vjqyfcseHG6le-FETh0Y3w==/base.apk' is compressed.
07-01 18:12:50.452 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.sankuai.movie-FPL5RS3WNhqbgyK9UoUUaA==/base.apk' is compressed.
07-01 18:12:50.498 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.Qunar-OeDn9s2h5ft-zjR_AvNiyQ==/base.apk' is compressed.
07-01 18:12:50.533 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.jingdong.app.mall-KOyGffLHBx1hKNn3KJxnBA==/base.apk' is compressed.
07-01 18:12:50.543 W/com.aaa.bbb(10240): resources.arsc in APK '/system/reserve/NearmeBrowser/NearmeBrowser.apk' is compressed.
07-01 18:12:50.593 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.alibaba.android.rimet-DZfNWlbR3Vpcq6gfguPz8w==/base.apk' is compressed.
07-01 18:12:50.656 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.sina.weibo-jMFLTDhqa7lwBCgIF5s3zw==/base.apk' is compressed.
07-01 18:12:50.683 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.ayerdudu.app-F3DUas1vP6nCG9oJXgNbEA==/base.apk' is compressed.
07-01 18:12:50.701 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.songheng.eastnews-ttYmC3da_ezQqfNSE8saaA==/base.apk' is compressed.
07-01 18:12:50.746 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.netease.cloudmusic-LW1G3ZU8cgQDaf_mrJsxkA==/base.apk' is compressed.
07-01 18:12:50.772 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.eg.android.AlipayGphone-mJ-Sp1Mp4xtgTMB7QrU-Qg==/base.apk' is compressed.
07-01 18:12:50.778 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/cn.wps.moffice_eng-VSTIXIthI0B0NyTh0pK2RA==/base.apk' is compressed.
07-01 18:12:50.960 W/com.aaa.bbb(10240): resources.arsc in APK '/system/app/QQBrowser/QQBrowser.apk' is compressed.
07-01 18:12:50.974 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.heytap.market-5vzgTy-KzRlZb8l-g3XcNQ==/base.apk' is compressed.
07-01 18:12:51.058 W/com.aaa.bbb(10240): resources.arsc in APK '/data/app/com.oneplus.gallery-1HZN4OpqnjqCaR15W9OU0w==/base.apk' is compressed.

**Comment by yohom** [comment]
你这插件什么版本的？

**Comment by JackZhang1994** [comment]
> 你这插件什么版本的？

amap_map_fluttify: 0.17.5+26272df
