### ISSUE TITLE
ios端地图显示全黑

### ISSUE THREAD

**Issue by Jiawei-Yu** [fluttify-project/amap_map_fluttify#265]
**插件版本**
^0.10.2+a1a3fff

**遇到bug的平台(Android/iOS)**
iOS

**描述bug**
key也申请好，调用了init方法了。就是不知为什么地图显示不出来，黑色的

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
plist里这个配置了吗
/// 使用PlatformView的声明
<key>io.flutter.embedded_views_preview</key>
<string>YES</string>
