### ISSUE TITLE
不同页面的AmapView耦合,A页面设置的setMapClick事件,在B页面设置也设置了,造成A页面的setMapClick无法监听

### ISSUE THREAD

**Issue by lyzhonghua** [fluttify-project/amap_map_fluttify#269]
**插件版本0.23.2**

**遇到bug的平台(Android)**

**
W/System.err(14133): java.lang.NullPointerException: Attempt to invoke virtual method 'com.amap.api.maps.AMap com.amap.api.maps.TextureMapView.getMap()' on a null object reference
W/System.err(14133): 	at me.yohom.amap_map_fluttify.TextureMapViewFactory$1.lambda$new$0(TextureMapViewFactory.java:74)
W/System.err(14133): 	at me.yohom.amap_map_fluttify.-$$Lambda$TextureMapViewFactory$1$sTRsczXe7ZZeUs9kkyXROGrCT-c.call(lambda)
W/System.err(14133): 	at me.yohom.amap_map_fluttify.TextureMapViewFactory.lambda$new$0$TextureMapViewFactory(TextureMapViewFactory.java:42)
W/System.err(14133): 	at me.yohom.amap_map_fluttify.-$$Lambda$TextureMapViewFactory$gVjqqupo-taBlB3fD12jxM_Lz8A.onMethodCall(lambda)
W/System.err(14133): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
W/System.err(14133): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(14133): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
W/System.err(14133): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(14133): 	at android.os.MessageQueue.next(MessageQueue.java:330)
W/System.err(14133): 	at android.os.Looper.loop(Looper.java:137)
W/System.err(14133): 	at android.app.ActivityThread.main(ActivityThread.java:5659)
W/System.err(14133): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(14133): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
W/System.err(14133): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
E/flutter (14133): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(Attempt to invoke virtual method 'com.amap.api.maps.AMap com.amap.api.maps.TextureMapView.getMap()' on a null object reference, null, null)
**

**1. A页面设置了setMapClickedListener, 从A启动B页面;
2. B页面也设置setMapClickedListener,,,,
3.回到A之后,A页面不响应mapclicked事件(造成A页面点击地图空白的地方,没法clear我的widget marker),而是关闭B的页面响应了(debug时,错误断点定位到了B页面)**

**A,B....N页面,都含有地图控件, 页面中的页面不相互影响**

**截图**

**flutter doctor**

顺便回答一下我自己的解决方案:  在重新回答A页面的时候,重新setMapClickListener就可以重新响应事件了

**Comment by yohom** [comment]
最新版本中增加了 `autoRelease` 参数，作用参考 https://github.com/fluttify-project/amap_map_fluttify/blob/83ae7aca5f0a251dad6461bf83bd03defc34d9bf/lib/src/facade/amap_view.widget.dart#L123

**Comment by SunhaoGogo** [comment]
我A页面设置 onMarkerClicked事件，B页面也设置了 onMarkerClicked事件，AmapView中也设置了autoRelease,但是我从a进b,再从b返回a时，a中的事件被b中的事件覆盖了

**Comment by SunhaoGogo** [comment]
目前处理方式也是返回a页面再手动添加事件
