### ISSUE TITLE
[feat] 修改定位箭头图标

### ISSUE THREAD

**Issue by yusheng-jia** [fluttify-project/amap_map_fluttify#27]
**插件版本**

**描述bug**

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
没有java版本的计划，不建议修改生成的代码，每次生成都会被覆盖。你想改什么东西？

**Comment by yusheng-jia** [comment]
> 没有java版本的计划，不建议修改生成的代码，每次生成都会被覆盖。你想改什么东西？

我想修改默认定位的那个箭头图标呢

**Comment by yohom** [comment]
提供一下两端api的官方文档，我看下加上去
