### ISSUE TITLE
地图显示空白，_onMapCreated 好像会打断什么东西？

### ISSUE THREAD

**Issue by TshineZheng** [fluttify-project/amap_map_fluttify#271]
**插件版本**
amap_map_fluttify: ^0.23.4

**遇到bug的平台(Android/iOS)**
iOS

**描述bug**
创建AmapView时传入centerCoordinate参数，并在onMapCreated调用controller.showMyLocation，有几率地图不显示，显示空白。
在onMapCreated之后追加controller.setCenterCoordinate好像就正常了。

**复现步骤**
创建ApmapView时传入centerCoordinate参数，在onMapCreated回调中调用controller.showMyLocation，多次进入该界面，有几率出现地图空白的问题。

**期望行为**
正常显示地图

**截图**

**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F96, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

**Comment by yohom** [comment]
调用`controller.showMyLocation`时有加await吗

**Comment by TshineZheng** [comment]
> 调用`controller.showMyLocation`时有加await吗

有加

**Comment by dishcheng** [comment]
同样遇到了

**Comment by gushisan** [comment]
原因是使用模拟器定位不准，定位到了一个根本不存在的经纬度或者国外，就会显示不出来一直空白。建议定位的时候将定位到的经纬度输出来看看是否准确
