### ISSUE TITLE
设置地图相对屏幕的中心点，方法缺失

### ISSUE THREAD

**Issue by influency-github** [fluttify-project/amap_map_fluttify#273]
**功能描述**
层叠布局中，地图上层被部分覆盖后无法看到中心点，需要动态设置地图中心。
**Native端对应字段/方法**
高德地图移动中心点的方法：
AMap.setPointToCenter(centerX, centerY)

**Comment by yohom** [comment]
你好，我貌似没有在ios端找到相同功能的接口，你知道ios端对应的接口是哪个吗

**Comment by influency-github** [comment]
你好，没注意消息，回复有点晚，资料如下：
MAMapStatus *status = [self.mapView getMapStatus];
status.screenAnchor = CGPointMake(0.5, 0.76);//地图左上为(0,0)点，右下为(1,1)点。
[self.mapView setMapStatus:status animated:NO];
[参考地址](https://lbs.amap.com/api/ios-sdk/guide/interaction-with-map/gesture-interaction#point_to_center)
