### ISSUE TITLE
[iOS]MAMapViewFactory.m，- (UIView *)view 方法，空指针导致iOS 程序崩溃

### ISSUE THREAD

**Issue by bugs2** [fluttify-project/amap_map_fluttify#279]
**插件版本**
0.17.0

**遇到bug的平台(Android/iOS)**
iOS

**描述bug**

//region method call handler
  FlutterMethodChannel *channel = [FlutterMethodChannel
      methodChannelWithName:@"me.yohom/amap_map_fluttify/MAMapView"
            binaryMessenger:[_registrar messenger]];

  [channel setMethodCallHandler:^(FlutterMethodCall *methodCall, FlutterResult methodResult) {
    NSDictionary<NSString *, id> *args = (NSDictionary<NSString *, id> *) [methodCall arguments];

    __strong __typeof(weakSelf) strongSelf = weakSelf;
    
//strongSelf可能为空，strongSelf->_handlerMap导致程序崩溃
//需要加如下保护
   //if (strongSelf == nil) {
     //   methodResult(FlutterMethodNotImplemented);
      //  return;
    //}
      
    if (strongSelf->_handlerMap[methodCall.method] != nil) {
      strongSelf->_handlerMap[methodCall.method](strongSelf->_registrar, args, methodResult);
    } else {
      methodResult(FlutterMethodNotImplemented);
    }
  }];

**复现步骤**
地图页面反复创建

**期望行为**
不崩溃

**截图**

**flutter doctor**

**Comment by bugs2** [comment]
好了，赞一个👍

**Comment by hidetag** [comment]
依然存在：
<img width="771" alt="image" src="https://user-images.githubusercontent.com/15097928/92209710-0d26ce80-eec0-11ea-8c42-78a960b9282c.png">
