### ISSUE TITLE
打包release apk打开地图就崩溃.

### ISSUE THREAD

**Issue by AOWOAO** [fluttify-project/amap_map_fluttify#28]
**插件版本**
0.3.1+70bd548

**描述bug**
打包release 版本打开地图就崩溃.
高德后台设置了keystore的sha1
地图页同时引用 map location, debug版本是可以正常运行的.

打包命令:
flutter build apk --target-platform android-arm --split-per-abi

**复现步骤**

**期望行为**

**截图**
![ttt](https://user-images.githubusercontent.com/25810208/68082597-c0b2d280-fe59-11e9-8a3e-26eba21eb120.gif)

**flutter doctor**

**Comment by yohom** [comment]
奔溃日志可以发一下吗 @AOWOAO

**Comment by yusheng-jia** [comment]
会不会是混淆问题？

**Comment by yohom** [comment]
debug可以，release就不行的话很大可能是so的abi没设置好，最好还提供下奔溃日志，不然只能猜

**Comment by AOWOAO** [comment]
是混淆问题. 我刚刚加上混淆的配置的现在打包出来可以打开地图页面了.
![微信截图_20191104094915](https://user-images.githubusercontent.com/25810208/68095942-657bf100-fee8-11e9-92be-c266f1664579.png)

**Comment by yohom** [comment]
ok，我把混淆规则加到插件里面去好了，你把混淆的那几句代码发一下

**Comment by AOWOAO** [comment]
![微信截图_20191104094915](https://user-images.githubusercontent.com/25810208/68095997-d02d2c80-fee8-11e9-8072-e300fdc6452b.png)

buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

android/app/proguard-rules.pro
# 地图
-keep   class com.amap.api.maps.**{*;}
-keep   class com.autonavi.**{*;}
-keep   class com.amap.api.trace.**{*;}

# 定位
-keep class com.amap.api.location.**{*;}
-keep class com.amap.api.fence.**{*;}
-keep class com.autonavi.aps.amapapi.model.**{*;}

# 搜索
-keep   class com.amap.api.services.**{*;}

**Comment by yohom** [comment]
好的，多谢，我关掉这个issue了
