### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amap.api.maps.model.BasePointOverlay.remove()' on a null object reference

### ISSUE THREAD

**Issue by momtboy** [fluttify-project/amap_map_fluttify#281]
**插件版本**
版本 0.24.0+2
**遇到bug的平台(Android/iOS)**
Android（IOS端暂不需要）
**描述bug**
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amap.api.maps.model.BasePointOverlay.remove()' on a null object reference
**复现步骤**
tab切换，数据重新刷新
**期望行为**
无报错
**截图**
`W/System.err(25208): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amap.api.maps.model.BasePointOverlay.remove()' on a null object reference
W/System.err(25208): 	at me.yohom.amap_map_fluttify.sub_handler.SubHandler8$1.lambda$new$77(SubHandler8.java:2858)
W/System.err(25208): 	at me.yohom.amap_map_fluttify.sub_handler.-$$Lambda$SubHandler8$1$RFmCy6aLz23Yy9p74zn4UdQwlvQ.call(Unknown Source:0)
W/System.err(25208): 	at me.yohom.amap_map_fluttify.AmapMapFluttifyPlugin.onMethodCall(AmapMapFluttifyPlugin.java:164)
W/System.err(25208): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
W/System.err(25208): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(25208): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
W/System.err(25208): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(25208): 	at android.os.MessageQueue.next(MessageQueue.java:363)
W/System.err(25208): 	at android.os.Looper.loop(Looper.java:173)
W/System.err(25208): 	at android.app.ActivityThread.main(ActivityThread.java:8147)
W/System.err(25208): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(25208): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(25208): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
W/System.err(25208): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amap.api.maps.model.BasePointOverlay.remove()' on a null object reference
W/System.err(25208): 	at me.yohom.amap_map_fluttify.sub_handler.SubHandler8$1.lambda$new$77(SubHandler8.java:2858)
W/System.err(25208): 	at me.yohom.amap_map_fluttify.sub_handler.-$$Lambda$SubHandler8$1$RFmCy6aLz23Yy9p74zn4UdQwlvQ.call(Unknown Source:0)
W/System.err(25208): 	at me.yohom.amap_map_fluttify.AmapMapFluttifyPlugin.onMethodCall(AmapMapFluttifyPlugin.java:164)
W/System.err(25208): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
W/System.err(25208): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(25208): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
W/System.err(25208): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(25208): 	at android.os.MessageQueue.next(MessageQueue.java:363)
W/System.err(25208): 	at android.os.Looper.loop(Looper.java:173)
W/System.err(25208): 	at android.app.ActivityThread.main(ActivityThread.java:8147)
W/System.err(25208): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(25208): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(25208): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)`
**flutter doctor**
Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.959], locale zh-CN

**Comment by SunLongbri** [comment]
我也遇到这个情况了，我这个是跳转到下一个地图之后，再返回这个地图，进行刷新的时候，出现这个情况。

**Comment by yohom** [comment]
AmapView dispose时，会释放当前插件分配的所有原生对象，所以后面的地图页弹出时会清空前面地图页分配的对象。
AmapView提供了`autoRelease`参数，设置为false时就不会在dispose时自动释放原生对象。

**Comment by SunLongbri** [comment]
可以了，亲测有效。

**Comment by wenziyangday** [comment]
请问你们是怎么解决的

**Comment by wenziyangday** [comment]
你们有没有遇到移除标记或者markers 时，就会报错
![Uploading image.png…]()
