### ISSUE TITLE
ios addMarker 为美国经纬度报错

### ISSUE THREAD

**Issue by long51xy** [fluttify-project/amap_map_fluttify#284]
**插件版本**

**遇到bug的平台(Android/iOS)**
ios
**描述bug**
添加美国经纬度无效果报错
**复现步骤**
爱思助手 虚拟定位 设置为美国的地理位置
**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
高德地图据我所知海外版需要另外的SDK，不在本插件范围内。
