### ISSUE TITLE
android 端 debug 版本正常，release 版本地图组件无法显示，屏幕灰色，android 端已关闭代码混淆

### ISSUE THREAD

**Issue by changgongxinshi** [fluttify-project/amap_map_fluttify#286]
**插件版本**
0.25.0
**遇到bug的平台(Android/iOS)**
android 
**描述bug**
android 端 debug 版本正常，release 版本地图组件无法显示，屏幕灰色
**复现步骤**

**期望行为**
release 环境下也可以正常使用
**截图**
![device-2020-08-17-204043](https://user-images.githubusercontent.com/16306138/90397178-0a5b6980-e0ca-11ea-8db3-cf0828fe6f16.png)

**flutter doctor**
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!

**Comment by ZMNOTZ** [comment]
> **插件版本**
> 0.25.0
> **遇到bug的平台(Android/iOS)**
> android
> **描述bug**
> android 端 debug 版本正常，release 版本地图组件无法显示，屏幕灰色
> **复现步骤**
> 
> **期望行为**
> release 环境下也可以正常使用
> **截图**
> ![device-2020-08-17-204043](https://user-images.githubusercontent.com/16306138/90397178-0a5b6980-e0ca-11ea-8db3-cf0828fe6f16.png)
> 
> **flutter doctor**
> $ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [√] Android Studio (version 3.6)
> [√] Connected device (1 available)
> 
> • No issues found!

_controller.showMyLocation 没有定位到当前位置，是怎么回事？

**Comment by changgongxinshi** [comment]
这个问题定位到了，应该跟地图组件没有关系。
在release 环境下，Stack 套 Expend ,再套地图组件，就会出现上述的黑屏问题。
同样的代码在debug 下就不会有任何问题。因为没有看到任何有意义的报错信息，以为是地图组件出了问题。
解决方法，去掉地图组件外层的Expend ，在release 环境下就正常了
