### ISSUE TITLE
获取定位信息失败

### ISSUE THREAD

**Issue by q869939686** [fluttify-project/amap_map_fluttify#29]
**插件版本**
0.3.1
**描述bug**
获取定位信息报错
**复现步骤**
![image](https://user-images.githubusercontent.com/29123332/68101845-b270bf00-ff0a-11e9-98bf-ed5ae38a5087.png)

**期望行为**

**截图**
![image](https://user-images.githubusercontent.com/29123332/68101877-e4822100-ff0a-11e9-933a-41d3ed9b38ff.png)

**flutter doctor**

**Comment by theecn** [comment]
同样遇到了这个问题，在onMapCreated 里调用controller.getLocation()会报错。
![image](https://user-images.githubusercontent.com/22100544/68175404-156e5e80-ffbc-11e9-8999-528fb28b8717.png)
![image](https://user-images.githubusercontent.com/22100544/68175425-2ae38880-ffbc-11e9-8a7d-2077429d9224.png)

**Comment by yohom** [comment]
我在android端复现了这个问题，在尝试延迟几秒钟后再获取位置之后就能正常获取到定位，示例代码：
```dart
Future.delayed(Duration(seconds: 3), () {
  controller
    .getLocation()
    .then((latLng) => print('latlng: $latLng'));
});
```
我感觉应该还是创建地图后马上获取位置时，定位还没完成，所以返回了null。建议先使用延迟获取试试。
@q869939686 @theecn

**Comment by theecn** [comment]
那是不是意味着我在 onMapCreated里面针对getlocation这个问题，再用一次异步的方法？

**Comment by yohom** [comment]
@theecn 你可以先试一下我说的方法，或者使用`amap_location_fluttify`.

**Comment by theecn** [comment]
测试过了，这个定位方法确实可行

**Comment by theecn** [comment]
ios- 地图不显示会是什么原因啊--（报错内容为请求超时） 需要在那个appdelegate。m 里面添加些其他的代码-

![image](https://user-images.githubusercontent.com/22100544/68365313-3c1ec780-016b-11ea-949c-9cc53b950ae9.png)

**Comment by yohom** [comment]
日志可以发上来看一下吗

**Comment by theecn** [comment]
![image](https://user-images.githubusercontent.com/22100544/68366024-332ef580-016d-11ea-93a4-a48a908dac0e.png)
![image](https://user-images.githubusercontent.com/22100544/68366035-3b873080-016d-11ea-930f-6aedcd448265.png)

**Comment by yohom** [comment]
是跟 https://github.com/fluttify-project/amap_map_fluttify/issues/33#issue-518214646 一样的问题吗

**Comment by yohom** [comment]
> ios- 地图不显示会是什么原因啊--（报错内容为请求超时） 需要在那个appdelegate。m 里面添加些其他的代码-
> 
> ![image](https://user-images.githubusercontent.com/22100544/68365313-3c1ec780-016b-11ea-949c-9cc53b950ae9.png)

关于这个问题 @theecn 开个新的issue吧，当前这个issue我关掉了。

**Comment by dinner** [comment]
@yohom 你好 我今天用这个定位的时候貌似又出问题，报的错好像都是这个定位的库过时了，定位始终失败，但是我运行example的时候又是好的
![WX20191121-185625](https://user-images.githubusercontent.com/2777780/69332162-13312300-0c91-11ea-96d8-f4e2c8e88859.png)
![WX20191121-185650](https://user-images.githubusercontent.com/2777780/69332169-14fae680-0c91-11ea-81a9-8c87560aba3b.png)

**Comment by yohom** [comment]
@q869939686 `0.7.2`版本中，`getLocation`增加了`delay`参数，用来指定延迟多少时间后再获取定位数据。具体使用多少数值可以自行测试，我自己测试，打开定位后一般延迟1秒钟就够了。

**Comment by q869939686** [comment]
OK
