### ISSUE TITLE
onMarkerClicked点击事件. 

### ISSUE THREAD

**Issue by uchengwang** [fluttify-project/amap_map_fluttify#291]
**插件版本**
0.25.0

**遇到bug的平台(Android/iOS)**
android

**描述bug**
在A界面创建地图对象, 跳转到B界面, B界面也创建地图对象.  退出B界面后, A界面的onMarkerClicked会无效, 无回调事件

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by uchengwang** [comment]
设置了autoRelease = false  还是不起作用

**Comment by zero0909** [comment]
> 设置了autoRelease = false 还是不起作用

这个问题 找到方式解决了吗 求教

**Comment by ZMNOTZ** [comment]
https://github.com/fluttify-project/amap_map_fluttify/issues/291#issuecomment-696496686
绑定了object数据后，点击没有数据

**Comment by 948911908** [comment]
问题解决了吗，遇到同样问题
