### ISSUE TITLE
设置轨迹线，不能动态缩放至正好显示的缩放级别

### ISSUE THREAD

**Issue by jackerchongchong** [fluttify-project/amap_map_fluttify#293]
在原生地图上有方法
        [self.mapView showOverlays:@[self.smoothedTrace] edgePadding:UIEdgeInsetsMake(80, 80, 80, 80) animated:YES];

功能需要，望回复

**Comment by yohom** [comment]
专业版中有提供 AmapController.zoomToSpan(List<LatLng>)

**Comment by jackerchongchong** [comment]
专业版的集成地址是什么

**Comment by ZMNOTZ** [comment]
> 专业版中有提供 AmapController.zoomToSpan(List)

_controller.showMyLocation 没有定位到当前位置，是怎么回事？

**Comment by ZMNOTZ** [comment]
> 在原生地图上有方法
> [self.mapView showOverlays:@[self.smoothedTrace] edgePadding:UIEdgeInsetsMake(80, 80, 80, 80) animated:YES];
> 
> 功能需要，望回复

_controller.showMyLocation 没有定位到当前位置，是怎么回事？
