### ISSUE TITLE
infowindow 在build之后会立刻自动dispose

### ISSUE THREAD

**Issue by xt-cool** [fluttify-project/amap_map_fluttify#294]
**插件版本**
v0.8.7
**遇到bug的平台(Android/iOS)**
android
**描述bug**
infowindow在build之后会立刻自动dispose，导致无法在infowindow组件中进行状态变更操作，无法播放视频
**复现步骤**
点击marker显示infowindow后，infowindow组件会立刻dispose掉
**期望行为**
不会自动销毁，能够进行状态变更
**截图**
![image](https://user-images.githubusercontent.com/30097150/91938991-9bb41800-ed27-11ea-8c97-67fe99cbd885.png)
![image](https://user-images.githubusercontent.com/30097150/91939026-aa9aca80-ed27-11ea-9c21-7d353a5908b6.png)

**flutter doctor**
![image](https://user-images.githubusercontent.com/30097150/91937225-0e22f900-ed24-11ea-9b24-ab56db66952b.png)

**Comment by yohom** [comment]
自定义的Widget InfoWindow只是对widget的一个截图，然后传给原生处理，播放视频是不可能的😂

**Comment by xt-cool** [comment]
好的，那我自己实现一个类似infowindow的弹窗
