### ISSUE TITLE
IOS上跳转后调用ImagePicker的拍照会让地图对手势失去响应

### ISSUE THREAD

**Issue by ykrank** [fluttify-project/amap_map_fluttify#297]
**插件版本**
0.25.0
**遇到bug的平台(Android/iOS)**
IOS
**描述bug**
地图页跳转一个新界面，新界面里调用ImagePicker.pickImage(source: ImageSource.camera)，那么返回后地图将失去响应。

一个比较特殊的情况是：
首页为一个IndexStack，地图是其中一个tab页，当切换到地图tab时跳转，回来后地图就会失去响应。
但是假如不是地图tab，这时候进行相同跳转，回来时延迟1.5s自动切到地图tab就会没问题，假如不延迟，直接切换到地图tab，地图一样会失去响应。
希望这个情况可以给问题的解决一点思路。

**flutter doctor**
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G73, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[!] VS Code (version 1.48.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Proxy Configuration
[✓] Connected device (2 available)

**Comment by ykrank** [comment]
最简单的demo：
`
import 'package:flutter/material.dart';
import 'package:amap_map_fluttify/amap_map_fluttify.dart';

import 'webview.dart';

void main()async {
  WidgetsFlutterBinding.ensureInitialized();
  await AmapService.init(iosKey: '', androidKey: '');
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: AmapView(
        mapType: MapType.Bus,
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (context) => WebView())),
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

import 'package:flutter/material.dart' hide Page;
import 'package:image_picker/image_picker.dart';

class WebView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(
        child: Center(
          child: RaisedButton(
              onPressed: () =>
                  ImagePicker.pickImage(source: ImageSource.camera, maxWidth: 1080, maxHeight: 1920, imageQuality: 90)),
        ),
      ),
    );
  }
}

`

**Comment by ZMNOTZ** [comment]
> 最简单的demo：
> `
> import 'package:flutter/material.dart';
> import 'package:amap_map_fluttify/amap_map_fluttify.dart';
> 
> import 'webview.dart';
> 
> void main() async {
> WidgetsFlutterBinding.ensureInitialized();
> await AmapService.init(iosKey: '', androidKey: '');
> runApp(MyApp());
> }
> 
> class MyApp extends StatelessWidget {
> @override
> Widget build(BuildContext context) {
> return MaterialApp(
> title: 'Flutter Demo',
> theme: ThemeData(
> primarySwatch: Colors.blue,
> visualDensity: VisualDensity.adaptivePlatformDensity,
> ),
> home: MyHomePage(title: 'Flutter Demo Home Page'),
> );
> }
> }
> 
> class MyHomePage extends StatefulWidget {
> MyHomePage({Key key, this.title}) : super(key: key);
> 
> final String title;
> 
> @override
> _MyHomePageState createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State {
> @override
> Widget build(BuildContext context) {
> return Scaffold(
> appBar: AppBar(
> title: Text(widget.title),
> ),
> body: AmapView(
> mapType: MapType.Bus,
> ),
> floatingActionButton: FloatingActionButton(
> onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (context) => WebView())),
> tooltip: 'Increment',
> child: Icon(Icons.add),
> ),
> );
> }
> }
> 
> import 'package:flutter/material.dart' hide Page;
> import 'package:image_picker/image_picker.dart';
> 
> class WebView extends StatelessWidget {
> @override
> Widget build(BuildContext context) {
> return Scaffold(
> appBar: AppBar(),
> body: Container(
> child: Center(
> child: RaisedButton(
> onPressed: () =>
> ImagePicker.pickImage(source: ImageSource.camera, maxWidth: 1080, maxHeight: 1920, imageQuality: 90)),
> ),
> ),
> );
> }
> }
> 
> `
_controller.showMyLocation 没有定位到当前位置，是怎么回事？
