### ISSUE TITLE
Android地图全黑

### ISSUE THREAD

**Issue by gushisan** [fluttify-project/amap_map_fluttify#299]
**插件版本**
amap_map_fluttify: ^0.25.1

**遇到bug的平台(Android/iOS)**
Android

**描述bug**
接入ios没有问题，Android出现地图全黑的情况，提供的demo也是全黑

**复现步骤**
初始化-创建地图

**Comment by ZMNOTZ** [comment]
> **插件版本**
> amap_map_fluttify: ^0.25.1
> 
> **遇到bug的平台(Android/iOS)**
> Android
> 
> **描述bug**
> 接入ios没有问题，Android出现地图全黑的情况，提供的demo也是全黑
> 
> **复现步骤**
> 初始化-创建地图

_controller.showMyLocation 没有定位到当前位置，是怎么回事？

**Comment by gushisan** [comment]
> > **插件版本** 
> > amap_map_fluttify：^ 0.25.1
> > **遇到bug的平台（Android / iOS）** 
> > 安卓
> > **描述错误** 
> > 接收ios没有问题，Android出现地图全黑的情况，提供的demo也是全黑
> > **复现步骤** 
> > 初始化-创建地图
> 
> _controller.showMyLocation没有定位到当前位置，是怎么回事？

使用真机调试，模拟器获取不到准确的位置

**Comment by gushisan** [comment]
真机调试 可以显示
