### ISSUE TITLE
建议新增一个点击地图获取点击位置经纬度的事件

### ISSUE THREAD

**Issue by KossFun** [fluttify-project/amap_map_fluttify#3]

**Comment by yohom** [comment]
如果可以的话，最好放一下官网相关的api链接，这样我实现起来快一些，也相当于分担了一些工作😄 @KossFun

**Comment by KossFun** [comment]
implements  AMap.OnMapClickListener 
Android 是这个方法

**Comment by FreAirLy** [comment]
iOS delegate MAMapViewDelegate 
- mapView:didSingleTappedAtCoordinate:

**Comment by yohom** [comment]
0.2.7+591effd版本 已实现此功能
