### ISSUE TITLE
能否更改定位原点样式

### ISSUE THREAD

**Issue by yanqiqi1996** [fluttify-project/amap_map_fluttify#30]
**功能描述**
![71572860852_ pic](https://user-images.githubusercontent.com/31203049/68111927-33d84980-ff2b-11e9-855d-362de69f5a98.jpg)

作者你好，可不可以增加修改这个圈圈样式的方法，我不想要这个圈圈
**Native端对应字段/方法**
![android](https://user-images.githubusercontent.com/31203049/68111693-b44a7a80-ff2a-11e9-99da-766f945ea952.png)
![ios](https://user-images.githubusercontent.com/31203049/68111750-dcd27480-ff2a-11e9-947b-81964301f145.png)
对应文档
 https://lbs.amap.com/api/android-sdk/guide/create-map/mylocation
https://lbs.amap.com/api/ios-sdk/guide/create-map/location-map

**Comment by yanqiqi1996** [comment]
#27 
好像可以和这个一起加

**Comment by yohom** [comment]
`0.3.3`版本，`controller.showMyLocation`方法已经增加`strokeColor`, `strokeWidth`以及`fillColor`参数。 @yanqiqi1996

**Comment by yanqiqi1996** [comment]
谢谢啦
