### ISSUE TITLE
换成自己的key后使用_controller.showMyLocation()不能定位

### ISSUE THREAD

**Issue by ZMNOTZ** [fluttify-project/amap_map_fluttify#300]
使用demo 可以定位到目前位置，但是使用自己的key 不能定位到当前位置（没有鉴权失败）

**Comment by gushisan** [comment]
> 使用demo可以定位到当前位置，但是使用自己的键不能定位到当前位置（没有鉴权失败）

真机调试试试，模拟器获取不到准确的位置

**Comment by gushisan** [comment]
试试将myLocationType设置为 连续定位并跟随， 刚刚ios真机调试了 没问题

**Comment by ZMNOTZ** [comment]
> 试试将myLocationType设置为 连续定位并跟随， 刚刚ios真机调试了 没问题

我还碰到添加marker 不生效，我反复进入地图好几次才能添加成功是为啥啊？

**Comment by ZMNOTZ** [comment]
> 试试将myLocationType设置为 连续定位并跟随， 刚刚ios真机调试了 没问题
请教下，绑定在marker 的object 数据为何在onMarkerClicked中获取不到？不然怎么点击的marker的地理信息呢？
