### ISSUE TITLE
_controller.addMarker/addMarkers() 调用之后在地图上看不到，重入3次后才可以看到marker

### ISSUE THREAD

**Issue by ZMNOTZ** [fluttify-project/amap_map_fluttify#302]
**插件版本**
^0.25.1
**遇到bug的平台(Android/iOS)**
android
**描述bug**
_controller.addMarker/addMarkers() 调用之后在地图上看不到，重入3次后才可以看到marker
**复现步骤**
_controller.addMarker/addMarkers() 调用之后在地图上看不到，重入3次后才可以看到marker
**期望行为**
添加后可以在地图上看到
**截图**

**flutter doctor**

**Comment by iceyx** [comment]
+1，你解决了吗

**Comment by ZMNOTZ** [comment]
重复调用机场

发自我的iPhone

------------------ 原始邮件 ------------------
发件人: misaelriojasftf <notifications@github.com&gt;
发送时间: 2020年9月16日 16:24
收件人: fluttify-project/amap_map_fluttify <amap_map_fluttify@noreply.github.com&gt;
抄送: Yohoho <609026421@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[fluttify-project/amap_map_fluttify] _controller.addMarker/addMarkers() 调用之后在地图上看不到，重入3次后才可以看到marker (#302)





 
+1，你解决了吗

**Comment by iceyx** [comment]
重复调用机场？没听懂

**Comment by ZMNOTZ** [comment]
> 重复调用机场？没听懂



> 重复调用机场？没听懂

请教下，绑定在marker 的object 数据为何在onMarkerClicked中获取不到？不然怎么点击的marker的地理信息呢？
