### ISSUE TITLE
AmapLocation.instance.fetchLocation() 拿不到位置信息

### ISSUE THREAD

**Issue by KossFun** [fluttify-project/amap_map_fluttify#303]
**插件版本**
0.27.0
**遇到bug的平台(Android/iOS)**
IOS
**描述bug**
AmapLocation.instance.fetchLocation() 拿不到位置信息
**复现步骤**

**期望行为**

**截图**
![image](https://user-images.githubusercontent.com/49841387/94102299-69986080-fe64-11ea-9bc6-bccb18a3d34c.png)

**flutter doctor**
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1082], locale zh-CN)
    • Flutter version 1.20.2 at E:\devEnv\Flutter
    • Framework revision bbfbf1770c (6 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by ZMNOTZ** [comment]
> **插件版本**
> 0.27.0
> **遇到bug的平台(Android/iOS)**
> IOS
> **描述bug**
> AmapLocation.instance.fetchLocation() 拿不到位置信息
> **复现步骤**
> 
> **期望行为**
> 
> **截图**
> ![image](https://user-images.githubusercontent.com/49841387/94102299-69986080-fe64-11ea-9bc6-bccb18a3d34c.png)
> 
> **flutter doctor**
> [√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1082], locale zh-CN)
> • Flutter version 1.20.2 at E:\devEnv\Flutter
> • Framework revision bbfbf1770c (6 weeks ago), 2020-08-13 08:33:09 -0700
> • Engine revision 9d5b21729f
> • Dart version 2.9.1
> • Pub download mirror https://pub.flutter-io.cn
> • Flutter download mirror https://storage.flutter-io.cn

请教下，绑定在marker 的object 数据为何在onMarkerClicked中获取不到？不然怎么点击的marker的地理信息呢？
