### ISSUE TITLE
onMarkerClicked 没有返回绑定的object 数据

### ISSUE THREAD

**Issue by ZMNOTZ** [fluttify-project/amap_map_fluttify#304]
**插件版本**
最新的版本
**遇到bug的平台(Android/iOS)**
android 
**描述bug**
无法获取绑定的数据
**复现步骤**
addMakers([MarkerOption])

**期望行为**
能够拿到绑定的object 数据

**截图**
![image](https://user-images.githubusercontent.com/22322315/94363580-be9ed580-00f5-11eb-8d4f-f670e7f3a14c.png)

**flutter doctor**

**Comment by gushisan** [comment]
同问，监听Mark点击事件，拿不到Mark上的数据

**Comment by gushisan** [comment]
请问解决了吗

**Comment by gushisan** [comment]
已解决
