### ISSUE TITLE
AmapView一进入就闪退

### ISSUE THREAD

**Issue by Maconzhang** [fluttify-project/amap_map_fluttify#31]
**插件版本**
amap_map_fluttify: ^0.3.2+22ede1a
**描述bug**
amap_map_fluttify 的内的example run 之后直接闪退，我在项目内引入AmapView 已进入页面就闪退；
log:
🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:61575/Q0nOjm3vEkc=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
D/        (28968): HostConnection::get() New Host Connection established 0xe5e45040, tid 28980
I/flutter (28968): fluttify-dart: com.amap.api.maps.MapView@0::onCreate([])
I/System.out(28968): fluttify-kotlin: com.amap.api.maps.MapView@0::onCreate()
D/        (28968): HostConnection::get() New Host Connection established 0xde1fdac0, tid 29012
D/EGL_emulation(28968): eglCreateContext: 0xc2ae8e00: maj 3 min 0 rcv 3
D/EGL_emulation(28968): eglMakeCurrent: 0xdff85420: ver 3 0 (tinfo 0xdff83500)
D/PlatformFactory(28968): 释放对象: class android.os.Bundle@232590588
D/PlatformFactory(28968): HEAP: {0=com.amap.api.maps.MapView{36057e7 V.E...... ........ 0,0-1080,1584}}
D/EGL_emulation(28968): eglMakeCurrent: 0xc2ae8e00: ver 3 0 (tinfo 0xbd470b20)
D/        (28968): HostConnection::get() New Host Connection established 0xdffa0640, tid 28983
F/libc    (28968): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xf54a0cf1 in tid 29012 (GLThread 913), pid 28968 (ple.flutter_app)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:9/PSR1.180720.075/5124027:user/release-keys'
Revision: '0'
ABI: 'x86'
pid: 28968, tid: 29012, name: GLThread 913  >>> com.example.flutter_app <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xf54a0cf1
    eax 3f0c37d1  ebx eaa3afe8  ecx b6399000  edx b66e3691
    edi b63dd500  esi f54a0cf1
    ebp b92db4d8  esp b92db4cc  eip b66e3893
backtrace:
    #00 pc 0034a893  /data/app/com.example.flutter_app-Srs7cXrnEd0KETExo9jlrg==/lib/x86/libAMapSDK_MAP_v6_9_2.so
Lost connection to device.

**截图**
![image](https://user-images.githubusercontent.com/20869112/68186825-05687600-ffe0-11e9-8197-492343ba829a.png)

**flutter doctor**
![image](https://user-images.githubusercontent.com/20869112/68186858-13b69200-ffe0-11e9-8acc-61cbb09c1a5d.png)

**Comment by yohom** [comment]
你用真机试一下

**Comment by Maconzhang** [comment]
> 你用真机试一下

真机上没问题， 模拟器闪退怎么办？

**Comment by yohom** [comment]
@Maconzhang 因为模拟器是x86架构的，建议还是用真机调试。具体详情可以百度`高德地图`+`模拟器`。
