### ISSUE TITLE
MarkerOption位置移动.

### ISSUE THREAD

**Issue by Jinxishihenian** [fluttify-project/amap_map_fluttify#311]
**插件版本**
amap_map_fluttify: ^0.25.0
**遇到bug的平台(Android/iOS)**
- android 10
- ios 12
**描述bug**
  使用MarkerOption中的widget属性构建MarkerOption,在放大或缩小地图时.MarkerOption的位置在不断变化.
**复现步骤**
  关键代码
```
 MarkerOption(
        widget: Column(
          // mainAxisSize: MainAxisSize.min,
          children: [
            Text("${todoLocals[i]['vehicleId']}"),
            Container(
              width: 50,
              height: 50,
              child: myImage,
            ),
          ],
        ),
```
**期望行为**
  当我放大或缩小地图的时候,我的MarkerOption能够准确定位,不在移动到其他位置.
**截图**
![微信图片_20201109222214](https://user-images.githubusercontent.com/44466363/98552956-0b232680-22da-11eb-9c2b-46f51181cb66.jpg)

**flutter doctor**
```
C:\Users\52889>flutter doctor
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.19041.572], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
***问题原因***
  我想这可能与MarkerOption的偏移量有关,这是属性是可能是anchorU,anchorV.但是我并不知道到怎样去使用它.

**Comment by Jinxishihenian** [comment]
[Uploading f81f85657a948732c557b95d820f6769.mp4…]()

**Comment by Jinxishihenian** [comment]
![Uploading f81f85657a948732c557b95d820f6769.gif…]()

**Comment by Jinxishihenian** [comment]
![f81f85657a948732c557b95d820f6769](https://user-images.githubusercontent.com/44466363/98555054-6c4bf980-22dc-11eb-9223-70d9ab826bb7.gif)

**Comment by Jinxishihenian** [comment]
该问题已经解决,将MarkerOption内的widget设置为正方形,并且ancharV设置为1. 标记将不在移动.

**Comment by yuchenga** [comment]
> 该问题已经解决,将MarkerOption内的widget设置为正方形,并且ancharV设置为1. 标记将不在移动.

你好 确定是你提供的这2个属性就够了吗 我这边还是在偏移
