### ISSUE TITLE
ios 编译报错

### ISSUE THREAD

**Issue by YDJSZY** [fluttify-project/amap_map_fluttify#312]
**插件版本**
0.30.0
**遇到bug的平台(Android/iOS)**
ios
**描述bug**
Module 'amap_map_fluttify' not found
**复现步骤**
flutter run
**期望行为**

**截图**

**flutter doctor**

**Comment by YDJSZY** [comment]
ios编译报错
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/mac/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.20.0/ios/Classes/SubHandler/SubHand
    ler1.m:141:17: error: property 'locationAccuracyMode' not found on object of type 'AMapLocationManager *'
                ref.locationAccuracyMode = locationAccuracyMode;
                    ^
    /Users/mac/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.20.0/ios/Classes/SubHandler/SubHand
    ler1.m:267:17: warning: 'township' is deprecated: 该字段从v2.2.0版本起不再返回数据,建议您使用AMapSearchKit的逆地理功能获取. [-Wdeprecated-declarations]
                ref.township = township;
                    ^
    In module 'AMapLocationKit' imported from
    /Users/mac/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.20.0/ios/Classes/AmapLocationFlutti
    fyPlugin.h:6:
    /Users/mac/Documents/flutterDemos/gaode_map_demo/ios/Pods/AMapLocation-NO-IDFA/AMapLocationKit.framework/Headers/AMapLocation
    CommonObj.h:76:63: note: 'township' has been explicitly marked deprecated here
    @property (nonatomic, copy) NSString *township
    __attribute__((deprecated("该字段从v2.2.0版本起不再返回数据,建议您使用AMapSearchKit的逆地理功能获取.")));
                                                                  ^
    /Users/mac/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.20.0/ios/Classes/SubHandler/SubHand
    ler1.m:288:17: warning: 'neighborhood' is deprecated: 该字段从v2.2.0版本起不再返回数据,建议您使用AMapSearchKit的逆地理功能获取.
    [-Wdeprecated-declarations]
                ref.neighborhood = neighborhood;
                    ^
    In module 'AMapLocationKit' imported from
    /Users/mac/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.20.0/ios/Classes/AmapLocationFlutti
    fyPlugin.h:6:
    /Users/mac/Documents/flutterDemos/gaode_map_demo/ios/Pods/AMapLocation-NO-IDFA/AMapLocationKit.framework/Headers/AMapLocation
    CommonObj.h:79:67: note: 'neighborhood' has been explicitly marked deprecated here
    @property (nonatomic, copy) NSString *neighborhood
    __attribute__((deprecated("该字段从v2.2.0版本起不再返回数据,建议您使用AMapSearchKit的逆地理功能获取.")));
                                                                      ^
    /Users/mac/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.20.0/ios/Classes/SubHandler/SubHand
    ler1.m:309:17: warning: 'building' is deprecated: 该字段从v2.2.0版本起不再返回数据,建议您使用AMapSearchKit的逆地理功能获取. [-Wdeprecated-declarations]
                ref.building = building;
                    ^
    In module 'AMapLocationKit' imported from
    /Users/mac/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.20.0/ios/Classes/AmapLocationFlutti
    fyPlugin.h:6:
    /Users/mac/Documents/flutterDemos/gaode_map_demo/ios/Pods/AMapLocation-NO-IDFA/AMapLocationKit.framework/Headers/AMapLocation
    CommonObj.h:82:63: note: 'building' has been explicitly marked deprecated here
    @property (nonatomic, copy) NSString *building
    __attribute__((deprecated("该字段从v2.2.0版本起不再返回数据,建议您使用AMapSearchKit的逆地理功能获取.")));
                                                                  ^
    /Users/mac/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.20.0/ios/Classes/SubHandler/SubHand
    ler1.m:1165:21: error: property 'locationAccuracyMode' not found on object of type 'AMapLocationManager *'
                    ref.locationAccuracyMode = locationAccuracyMode;
                        ^
    /Users/mac/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.20.0/ios/Classes/SubHandler/SubHand
    ler1.m:1297:21: warning: 'township' is deprecated: 该字段从v2.2.0版本起不再返回数据,建议您使用AMapSearchKit的逆地理功能获取.
    [-Wdeprecated-declarations]
                    ref.township = township;
                        ^
    In module 'AMapLocationKit' imported from
    /Users/mac/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.20.0/ios/Classes/AmapLocationFlutti
    fyPlugin.h:6:
    /Users/mac/Documents/flutterDemos/gaode_map_demo/ios/Pods/AMapLocation-NO-IDFA/AMapLocationKit.framework/Headers/AMapLocation
    CommonObj.h:76:63: note: 'township' has been explicitly marked deprecated here
    @property (nonatomic, copy) NSString *township
    __attribute__((deprecated("该字段从v2.2.0版本起不再返回数据,建议您使用AMapSearchKit的逆地理功能获取.")));
                                                                  ^
    /Users/mac/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.20.0/ios/Classes/SubHandler/SubHand
    ler1.m:1319:21: warning: 'neighborhood' is deprecated: 该字段从v2.2.0版本起不再返回数据,建议您使用AMapSearchKit的逆地理功能获取.
    [-Wdeprecated-declarations]
                    ref.neighborhood = neighborhood;
                        ^
    In module 'AMapLocationKit' imported from
    /Users/mac/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.20.0/ios/Classes/AmapLocationFlutti
    fyPlugin.h:6:
    /Users/mac/Documents/flutterDemos/gaode_map_demo/ios/Pods/AMapLocation-NO-IDFA/AMapLocationKit.framework/Headers/AMapLocation
    CommonObj.h:79:67: note: 'neighborhood' has been explicitly marked deprecated here
    @property (nonatomic, copy) NSString *neighborhood
    __attribute__((deprecated("该字段从v2.2.0版本起不再返回数据,建议您使用AMapSearchKit的逆地理功能获取.")));
                                                                      ^
    /Users/mac/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.20.0/ios/Classes/SubHandler/SubHand
    ler1.m:1341:21: warning: 'building' is deprecated: 该字段从v2.2.0版本起不再返回数据,建议您使用AMapSearchKit的逆地理功能获取.
    [-Wdeprecated-declarations]
                    ref.building = building;
                        ^
    In module 'AMapLocationKit' imported from
    /Users/mac/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/amap_location_fluttify-0.20.0/ios/Classes/AmapLocationFlutti
    fyPlugin.h:6:
    /Users/mac/Documents/flutterDemos/gaode_map_demo/ios/Pods/AMapLocation-NO-IDFA/AMapLocationKit.framework/Headers/AMapLocation
    CommonObj.h:82:63: note: 'building' has been explicitly marked deprecated here
    @property (nonatomic, copy) NSString *building
    __attribute__((deprecated("该字段从v2.2.0版本起不再返回数据,建议您使用AMapSearchKit的逆地理功能获取.")));
                                                                  ^
    6 warnings and 2 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11

**Comment by Seven163** [comment]
这个问题解决了嘛？

**Comment by GeminiSGX** [comment]
Has the problem been solved? I have this problem, too

**Comment by YDJSZY** [comment]
@Seven163 没有，不知道啥情况，ios不懂。

**Comment by Seven163** [comment]
@GeminiSGX I used version 0.24.0+3

**Comment by YDJSZY** [comment]
@GeminiSGX No yet
