### ISSUE TITLE
地图marker随着地图缩放位置偏移很大

### ISSUE THREAD

**Issue by tadpole145** [fluttify-project/amap_map_fluttify#314]
**插件版本** : 0.29.0

**遇到bug的平台(Android/iOS)**  android

**描述bug**
当地图缩放级别较低时,marker明显偏移了,有的都显示在河道里面了,当双手放大地图后,明显看到marker位置向上偏移,地图放大最大倍,marker位置也就正确了..但是缩放过程中,自己的定位指示图标一直显示正确,只有marker会偏移.
**复现步骤**

**截图**
截图2个marker,一个是北京,一个是江苏,缩小地图放大等级后,一个跑到河北,一个跑到了浙江
![定位](https://user-images.githubusercontent.com/35562133/100594193-51e1ca80-3334-11eb-9d31-d7213e012253.jpg)

**Comment by Jinxishihenian** [comment]
我并没有找到具体原因但是我这又一个解决办法你可以尝试一下.
https://github.com/fluttify-project/amap_map_fluttify/issues/311

**Comment by LittleTadpole** [comment]
> 我并没有找到具体原因但是我这有一个解决办法你可以尝试一下.
> #311

大佬请赐教,我试试,谢谢

**Comment by jjva-xiao** [comment]
我也是碰到了这个问题，大佬有没有解决？

**Comment by jjva-xiao** [comment]
> 我并没有找到具体原因但是我这有一个解决办法你可以尝试一下.
> #311

大佬能否赐教

**Comment by jjva-xiao** [comment]
> **插件版本** : 0.29.0
> 
> **遇到bug的平台(Android/iOS)** android
> 
> **描述bug**
> 当地图缩放级别较低时,marker明显偏移了,有的都显示在河道里面了,当双手放大地图后,明显看到marker位置向上偏移,地图放大最大倍,marker位置也就正确了..但是缩放过程中,自己的定位指示图标一直显示正确,只有marker会偏移.
> **复现步骤**
> 
> **截图**
> 截图2个marker,一个是北京,一个是江苏,缩小地图放大等级后,一个跑到河北,一个跑到了浙江
> ![定位](https://user-images.githubusercontent.com/35562133/100594193-51e1ca80-3334-11eb-9d31-d7213e012253.jpg)

您是否已经解决了这个问题？

**Comment by tadpole145** [comment]
> 碰到



> > **插件版本** : 0.29.0
> > **遇到bug的平台(Android/iOS)** android
> > **描述bug**
> > 当地图缩放级别较低时,marker明显偏移了,有的都显示在河道里面了,当双手放大地图后,明显看到marker位置向上偏移,地图放大最大倍,marker位置也就正确了..但是缩放过程中,自己的定位指示图标一直显示正确,只有marker会偏移.
> > **复现步骤**
> > **截图**
> > 截图2个marker,一个是北京,一个是江苏,缩小地图放大等级后,一个跑到河北,一个跑到了浙江
> > ![定位](https://user-images.githubusercontent.com/35562133/100594193-51e1ca80-3334-11eb-9d31-d7213e012253.jpg)
> 
> 您是否已经解决了这个问题？

不好意思,一直没注意到邮件. 这个问题我没有解决,作者也没有给我提供解决办法..目前高德官方已经出了,建议使用官方的吧
