### ISSUE TITLE
安卓版本黑屏

### ISSUE THREAD

**Issue by stjdydayou** [fluttify-project/amap_map_fluttify#315]
**插件版本**
0.30.0
**遇到bug的平台(Android/iOS)**
Android
**描述bug**

安卓版本黑屏

运行报错
No implementation found for void com.autonavi.base.amap.mapcore.AMapNativeRenderer.nativeDrawLineInit

**Comment by kodeflow** [comment]
我也遇到这个问题。你解决了吗？

**Comment by kodeflow** [comment]
我这里用Android 6模拟器正常了。
