### ISSUE TITLE
请问下是否提供更新marker的方法呢

### ISSUE THREAD

**Issue by zhouqingGitHub** [fluttify-project/amap_map_fluttify#316]
**功能描述**
有个需求 点击按钮的时候更改maker的样式 请问有这样的方法吗？ 我现在是把他原先的删了 重新添加 但是这样开销太大 而且有明显的闪烁
**Native端对应字段/方法**

**Comment by jjva-xiao** [comment]
> 
> 
> **功能描述**
> 有个需求 点击按钮的时候更改maker的样式 请问有这样的方法吗？ 我现在是把他原先的删了 重新添加 但是这样开销太大 而且有明显的闪烁
> **Native端对应字段/方法**

如何删了重新添加？

**Comment by zhouqingGitHub** [comment]
比如地图上原先有marker A 点击A需要改变其背景色
那么调用clearMarkers 把A删除 然后再调用addMarker 重新添加一个带背景色的marker






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fluttify-project/amap_map_fluttify"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 下午4:12
收件人:&nbsp;"fluttify-project/amap_map_fluttify"<amap_map_fluttify@noreply.github.com&gt;;
抄送:&nbsp;"会飞的猪"<396104459@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fluttify-project/amap_map_fluttify] 请问下是否提供更新marker的方法呢 (#316)





  
功能描述
 有个需求 点击按钮的时候更改maker的样式 请问有这样的方法吗？ 我现在是把他原先的删了 重新添加 但是这样开销太大 而且有明显的闪烁
 Native端对应字段/方法
  
如何删了重新添加？
