### ISSUE TITLE
onMapMoveEnd的回调中MapMove的coordinate没有赋值

### ISSUE THREAD

**Issue by nickzhuo** [fluttify-project/amap_map_fluttify#318]
使用地图中的onMapMoveEnd回调方法，调用MapMove，注解里面已经写了@Deprecated('使用coordinate代替') this.latLng，但其实，coordinate没有赋值，反而latLng赋值了，请有空改下，太迷惑了搞了半天。

**Comment by xiejibiao** [comment]
@nickzhuo 我也遇到这个问题，请问您解决了吗？

**Comment by sm9i** [comment]
我也是，没值。
