### ISSUE TITLE
一直编译失败

### ISSUE THREAD

**Issue by JD-CP** [fluttify-project/amap_map_fluttify#319]
e: /Users/mac/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub/foundation_fluttify-0.11.1/android/src/main/kotlin/me/yohom/foundation_fluttify/android/view/SurfaceHolderHandler.kt: (13, 34): Object is not abstract and does not implement abstract member public abstract fun surfaceCreated(p0: SurfaceHolder): Unit defined in android.view.SurfaceHolder.Callback
e: /Users/mac/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub/foundation_fluttify-0.11.1/android/src/main/kotlin/me/yohom/foundation_fluttify/android/view/SurfaceHolderHandler.kt: (16, 17): 'surfaceCreated' overrides nothing
e: /Users/mac/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub/foundation_fluttify-0.11.1/android/src/main/kotlin/me/yohom/foundation_fluttify/android/view/SurfaceHolderHandler.kt: (24, 17): 'surfaceChanged' overrides nothing
e: /Users/mac/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub/foundation_fluttify-0.11.1/android/src/main/kotlin/me/yohom/foundation_fluttify/android/view/SurfaceHolderHandler.kt: (32, 17): 'surfaceDestroyed' overrides nothing
e: /Users/mac/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub/foundation_fluttify-0.11.1/android/src/main/kotlin/me/yohom/foundation_fluttify/platform_view/android_view_SurfaceViewFactory.kt: (21, 33): Object is not abstract and does not implement abstract member public abstract fun surfaceCreated(p0: SurfaceHolder): Unit defined in android.view.SurfaceHolder.Callback
e: /Users/mac/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub/foundation_fluttify-0.11.1/android/src/main/kotlin/me/yohom/foundation_fluttify/platform_view/android_view_SurfaceViewFactory.kt: (28, 13): 'surfaceCreated' overrides nothing
e: /Users/mac/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub/foundation_fluttify-0.11.1/android/src/main/kotlin/me/yohom/foundation_fluttify/platform_view/android_view_SurfaceViewFactory.kt: (35, 13): 'surfaceChanged' overrides nothing
e: /Users/mac/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%47dart-pub/foundation_fluttify-0.11.1/android/src/main/kotlin/me/yohom/foundation_fluttify/platform_view/android_view_SurfaceViewFactory.kt: (42, 13): 'surfaceDestroyed' overrides nothing

**Comment by nickzhuo** [comment]
flutter channel stable

**Comment by JD-CP** [comment]
> flutter channel stable

你好 只能在stable分支下 运行吗？

**Comment by nickzhuo** [comment]
> > flutter channel stable
> 
> 你好 只能在stable分支下 运行吗？

yes

**Comment by JD-CP** [comment]
> > > flutter channel stable
> > 
> > 
> > 你好 只能在stable分支下 运行吗？
> 
> yes

我觉得可以把这个注意项添加在README文档中，昨天我在master分支搞了几个小时...

**Comment by nickzhuo** [comment]
> > > > flutter channel stable
> > > 
> > > 
> > > 你好 只能在stable分支下 运行吗？
> > 
> > 
> > yes
> 
> 我觉得可以把这个注意项添加在README文档中，昨天我在master分支搞了几个小时...

我不是contributor，只是路过帮你解决下问题。

**Comment by JD-CP** [comment]
> > > > > flutter channel stable
> > > > 
> > > > 
> > > > 你好 只能在stable分支下 运行吗？
> > > 
> > > 
> > > yes
> > 
> > 
> > 我觉得可以把这个注意项添加在README文档中，昨天我在master分支搞了几个小时...
> 
> 我不是contributor，只是路过帮你解决下问题。

哈哈 误以为你是contributor了，不好意思了。多谢你的帮助😄
