### ISSUE TITLE
IOS出现 " 参数非法, coordinate不能为null " 异常

### ISSUE THREAD

**Issue by xiejibiao** [fluttify-project/amap_map_fluttify#328]
**插件版本**
amap_map_fluttify: ^0.30.1
**遇到bug的平台(Android/iOS)**
iOS
**描述bug**
重新添加 Marker 时，IOS出现 " 参数非法, coordinate不能为null " 异常，安卓系统正常
**复现步骤**
1）创建地图，
2）循环添加多个 Marker 
3）清除全部 Marker
4）重新循环添加 Marker
**期望行为**
清除全部 Marker 后，可重新添加 Marker
**截图**

**flutter doctor**
`[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.12.6 16G29 darwin-x64, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 9.0)
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.6.1 out of date (1.8.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2019.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.`

**Comment by suckson** [comment]
#执行这一步之后地图就崩溃了

flutter: fluttify-dart: MAMapView@5033328640::removeAnnotations([])

**Comment by xiejibiao** [comment]
@suckson 我找到原因了，我是因为添加Marker后，再执行了 setCenterCoordinate 才导致了这个问题，你可以检查一下你的代码流程，应该先执行 setCenterCoordinate 后，再添加 Marker 就不会有此异常

**Comment by suckson** [comment]
@xiejibiao  这个marker 的方法地图内部是不是还有其他的调用。我已经修改了添加marker的方法。但是在页面pop（） 或者popUnitl的时候也会退出。
