### ISSUE TITLE
androidstudio打release包报错，无法编译apk

### ISSUE THREAD

**Issue by JediMaker** [fluttify-project/amap_map_fluttify#329]
**插件版本**
  #  引入高德地图Flutter插件
  amap_map_fluttify: ^0.30.1
  #  引入高德地图搜索Flutter插件
  amap_search_fluttify: ^0.16.2

**遇到bug的平台(Android/iOS)**
Android

**描述bug**
打包报错，插件冲突

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\1024A\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\amap_core_fluttify-0.14.0\android\build.gradle' line: 70

* What went wrong:
A problem occurred evaluating root project 'amap_core_fluttify'.
> Cannot convert a null value to an object of type Dependency.
  The following types/formats are supported:
    - Instances of Dependency.
    - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
    - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
    - FileCollections, for example files('some.jar', 'someOther.jar').
    - Projects, for example project(':some:project:path').
    - ClassPathNotation, for example gradleApi().

  Comprehensive documentation on dependency notations is available in DSL reference for DependencyHandler type.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

The plugin amap_core_fluttify could not be built due to the issue above.

**复现步骤**
新建空项目
引入插件：
  #  图片缓存
  cached_network_image: ^2.3.0-rc
 #  amap_flutter_location: ^1.0.1
  #  引入高德地图Flutter插件
  amap_map_fluttify: ^0.30.1
  #  引入高德地图搜索Flutter插件
  amap_search_fluttify: ^0.16.2
编译打包apk
**期望行为**
解决插件冲突，正常编译apk

**截图**
![微信图片_20210312191124](https://user-images.githubusercontent.com/16040457/110932695-c500d100-8366-11eb-9eec-8148bb28b014.png)

**flutter doctor**
E:\devCode\flutter_amap_conflit_test>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1379], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by youlai** [comment]
没人吗？怎么解决？
