### ISSUE TITLE
要在iOS 11及以上版本使用后台定位服务, 需要实现mapViewRequireLocationAuth: 代理方法

### ISSUE THREAD

**Issue by CodingClearLoveLove** [fluttify-project/amap_map_fluttify#33]
AmapView(
onMapCreated: (AmapController controller) async {

      await controller.showMyLocation(true);
    },
  ),
时 无法显示到当前位置 提示:要在iOS 11及以上版本使用后台定位服务, 需要实现mapViewRequireLocationAuth: 代理方法

**Comment by CodingClearLoveLove** [comment]
AmapView(
        onMapCreated: (AmapController controller) async {

          await controller.showMyLocation(true);
        },
      ),
时 无法显示到当前位置 提示:要在iOS 11及以上版本使用后台定位服务, 需要实现mapViewRequireLocationAuth: 代理方法

**Comment by yohom** [comment]
@CodingClearLoveLove 可否提供一下复现步骤？

**Comment by theecn** [comment]
应该不太一样吧 我是提示请求超时 -- 不懂是什么原因。

**Comment by yohom** [comment]
@CodingClearLoveLove 0.4.0版本已经添加`requireAlwaysAuth`方法，需要时申请后台定位。

**Comment by todother** [comment]
[MAMapKit] 要在iOS 11及以上版本使用后台定位服务, 需要实现mapViewRequireLocationAuth: 代理方法
遇到同样问题

已经实现
 func amapLocationManager(_ manager: AMapLocationManager!, doRequireLocationAuth locationManager: CLLocationManager!) {
        locationManager.requestAlwaysAuthorization()
    }

如果需要去实现mapViewRequireLocationAuth相关的delegate，又在哪实现？谢谢
