### ISSUE TITLE
设置setCenterCoordinate后addMarker无效

### ISSUE THREAD

**Issue by Cvilia** [fluttify-project/amap_map_fluttify#34]
**插件版本**
amap_map_fluttify: ^0.3.2+70bd548
**描述bug**
显示完地图后需要显示指定的位置，然后后添加marker，但是设置指定位置后添加marker无效
**复现步骤**

**期望行为**
两个方法可以同时使用
**截图**

**flutter doctor**

**Comment by yohom** [comment]
@Cvilia 调用`AmapController`的每个方法，前面都加`await`，确保调用顺序。

**Comment by theecn** [comment]
AmapController的每个方法所返回的都是Future对象，你可以在调用完显示位置之后，接一个then，然后在then里面添加marker，应该这样就可以正常执行。
