### ISSUE TITLE
ios使用新版本后报错

### ISSUE THREAD

**Issue by theecn** [fluttify-project/amap_map_fluttify#36]
**插件版本**
0.3.3+10e2842
**描述bug**
原先的0.3.2+70bd548 版本可以正常运行，但是当升级到最新版当时候编译便不通过。flutter clean 重新安装也不行
**复现步骤**

**期望行为**
可以正常运行
**截图**
![image](https://user-images.githubusercontent.com/22100544/68363638-8b162e00-0166-11ea-9171-40b882df9cfd.png)

**flutter doctor**

**Comment by yohom** [comment]
最新底层`foundation_fluttify`加入了对`UIColor`的支持，`flutter packages upgrade`，`flutter packages get`一下。

**Comment by theecn** [comment]
已经能够正常使用，感谢
