### ISSUE TITLE
ios集成错误apiKey为空

### ISSUE THREAD

**Issue by mutu123** [fluttify-project/amap_map_fluttify#37]
错误信息：apiKey为空，请正确设置AMapServices.apiKey。请在 AppDelegate.m 文件的 didFinishLaunchingWithOptions 方法中配置高德 Key。

main里面初始化设置了高德平台申请的ios对应的key

**Comment by yohom** [comment]
代码贴一下

**Comment by chenkang2208** [comment]
同样的问题：

Future main() async {
  Logger.root.level = Level.ALL;
  Logger.root.onRecord.listen((LogRecord rec) {
    print('${rec.level.name}: ${rec.time}: ${rec.message}');
  });

  await AmapService.init('05bb8e665807eb054a392c8841252bd5');
  await FlutterDownloader.initialize();

  runApp(MyApp());
}

**Comment by mutu123** [comment]
用真机就不会出现这个问题了




| |
杜康
邮箱：15527660071@163.com
|

签名由 网易邮箱大师 定制

在2019年11月08日 18:22，chenkang2208 写道：

同样的问题：

Future main() async {
Logger.root.level = Level.ALL;
Logger.root.onRecord.listen((LogRecord rec) {
print('${rec.level.name}: ${rec.time}: ${rec.message}');
});

await AmapService.init('05bb8e665807eb054a392c8841252bd5');
await FlutterDownloader.initialize();

runApp(MyApp());
}

**Comment by chenkang2208** [comment]
多谢，我试一下真机。现在是在模拟器里面调试，会报这个错。
