### ISSUE TITLE
ios初始化不报错 但是不显示地图、获取不到经纬度。

### ISSUE THREAD

**Issue by theecn** [fluttify-project/amap_map_fluttify#39]
**插件版本**
  amap_map_fluttify: 0.3.3+10e2842
**遇到bug的平台(Android/iOS)**
iOS
**描述bug**
1.初始化无法获取到地图
2.初始化无法获取到经纬度（采用了Future的写法依旧不行）
3.添加标记点地图无显示（此时地图仍然是一片灰茫茫，和一个蓝点）
**复现步骤**

**期望行为**
初始化能够正常获取到经纬度，加载地图。
**截图**
![image](https://user-images.githubusercontent.com/22100544/68447287-5d8abc80-021a-11ea-8251-8723705c0914.png)
![image](https://user-images.githubusercontent.com/22100544/68447326-84e18980-021a-11ea-8ce4-44b541e065cb.png)

**报错截图**

![image](https://user-images.githubusercontent.com/22100544/68447451-f7526980-021a-11ea-8a3b-183735ac234d.png)
**日志截图**
**flutter doctor**

**Comment by yohom** [comment]
你是模拟器吗

**Comment by theecn** [comment]
是模拟器没错，，，我想用真机调试来着，但是第一次接触ios打包开发之类的鬼东西 被难住了好几天。真的难

**Comment by yohom** [comment]
最好还是以真机为准。

**Comment by theecn** [comment]
好的

**Comment by theecn** [comment]
![image](https://user-images.githubusercontent.com/22100544/68639037-4b708d00-053e-11ea-8d32-8cb24bc0a4af.png)

作者大佬，比方说我想获取上图的城市名 ，要在哪里获取到呢

**Comment by yohom** [comment]
你这个是调了哪个方法获取到的数据？

**Comment by theecn** [comment]
调用的showMyLocation，能加下你微信吗--

**Comment by yohom** [comment]
目前你可以调用`getLocation`获取到经纬度然后再用`amap_search_fluttify`进行逆地理搜索获取到详细信息。单独使用地图sdk获取详细信息我再看下能不能实现。
