### ISSUE TITLE
建议新增一个removeMarker的方法

### ISSUE THREAD

**Issue by KossFun** [fluttify-project/amap_map_fluttify#4]

**Comment by yohom** [comment]
如果可以的话，最好放一下官网相关的api链接，这样我实现起来快一些，也相当于分担了一些工作😄 @KossFun

**Comment by KossFun** [comment]
应该是 aMap.clear()这个方法
可以参考这篇文章 https://blog.csdn.net/u010378579/article/details/53096864

**Comment by yohom** [comment]
0.2.7+591effd版本 已实现此功能。
addMarker方法会返回Marker对象，Marker类中含有remove方法，把自己从地图中删除。
