### ISSUE TITLE
希望能在添加线(addPolyline)方法里增加一个纹理贴图的参数

### ISSUE THREAD

**Issue by KangYee** [fluttify-project/amap_map_fluttify#40]
### **Native端对应字段/方法**

**_Android_**
_PolylineOptions_
- setCustomTexture
- setUseTexture

**_IOS_**
polylineRenderer.loadStrokeTextureImage(UIImage.init(named: "arrowTexture"))

**Comment by yohom** [comment]
@KangYee `0.5.0`版本里的`addPolyline`添加了`customTexture`参数。
