### ISSUE TITLE
打包之后定位失效

### ISSUE THREAD

**Issue by q869939686** [fluttify-project/amap_map_fluttify#45]
**插件版本**
0.3.2
**遇到bug的平台(Android/iOS)**
andro
**描述bug**
真机测试时有定位，打包app-release后定位功能失效
**复现步骤**
打包之前
![image](https://user-images.githubusercontent.com/29123332/68565432-78fdfd80-048e-11ea-9a32-5a4163c39dab.png)
打包之后
![image](https://user-images.githubusercontent.com/29123332/68565558-dbef9480-048e-11ea-9483-9311a22613b8.png)

**期望行为**

**截图**

**flutter doctor**

**Comment by dinner** [comment]
@q869939686 @yohom 请问下 我这边使用安卓debug定位的时候 始终不能定位成功，我这也申请了高德的key，暂时没有打包，设置的是调试模式下的SHA1。而且example的安卓工程也是定位失败，我打印了申请权限那里，始终报定位的权限是disable，试了好几个机器都是这样，请问您知道这是啥情况么？

**Comment by yohom** [comment]
@dinner 那就是权限没有开？是不是gps关掉了之类的？

**Comment by dinner** [comment]
@yohom  确定是开了的

**Comment by yohom** [comment]
@dinner 会不会是被拒绝了一次，之后就没有再弹过窗了，所以一直那不到权限。你卸载应用重新安装一下试试，重新安装之后就会再弹出授权对话框了。

**Comment by dinner** [comment]
> @dinner 会不会是被拒绝了一次，之后就没有再弹过窗了，所以一直那不到权限。你卸载应用重新安装一下试试，重新安装之后就会再弹出授权对话框了。

 好的 谢谢哈 原因找到了 定位没开  刚开始我在设置里找定位的设置找了很久也没找到后面就没找了 但是微信在定位没开的时候也能定位 而且一个管理软件的权限查看里看到demo的定位也是开了的 感觉很奇怪 今天跟一个朋友讨论说是微信可能是用的基站定位而不是gps定位 所以在设置里定位权限没开的时候也能定位 现在我在高德上下载的demo总算可以定位成功了

**Comment by yohom** [comment]
@q869939686 现在最新版(0.7.1)还有这个问题吗，我自己试了一下，机子也是Mix3，是正常的。是没有定位成功还是说定位的图标不见了？

**Comment by q869939686** [comment]
定位服务是不能用的，我感觉像是高德API设置的SHA1不正确导致的，但是我更换了key.jks的sha1之后还是没有效果

**Comment by yohom** [comment]
高德SDK有没有报错信息？

**Comment by q869939686** [comment]
打包到app-release之后就看不到log了

**Comment by yohom** [comment]
可以打个profile包试试

**Comment by q869939686** [comment]
--profile和--release都没用报错，也没有显示Key不可用，但是就是定位不了
![image](https://user-images.githubusercontent.com/29123332/69520225-08c79f80-0f97-11ea-86ed-6aef605148bc.png)

**Comment by q869939686** [comment]
![image](https://user-images.githubusercontent.com/29123332/69520514-e2563400-0f97-11ea-95af-7ffa4e556be3.png)

**Comment by q869939686** [comment]
自从--release之后，debug模式，高德地图也不起作用了
