### ISSUE TITLE
有关ios打包权限问题

### ISSUE THREAD

**Issue by Cvilia** [fluttify-project/amap_map_fluttify#46]
**插件版本**

**遇到bug的平台(Android/iOS)**

**描述bug**
ios打包时被驳回，邮件中列出了很多权限，但是大部分权限是不必须的
**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
截下图

**Comment by yohom** [comment]
你是不是用了`permission_handler`?如果是的话，参考一下这个插件的说明。

**Comment by Cvilia** [comment]
> 你是不是用了`permission_handler`?如果是的话，参考一下这个插件的说明。

果然是这样，感谢大佬
