### ISSUE TITLE
您好，关于大头针Mark的title，能否增加点击事件？

### ISSUE THREAD

**Issue by dreamCC** [fluttify-project/amap_map_fluttify#47]
**功能描述**
在AmapView中，看了下您的代码，发现只有onMarkerClick、onMapClick、onMapDrag几个事件的回调。是否有（或者能否增加），当点击Mark标记时候，显示title和snippet，并且点击title同样可以有相应的点击事件回调？

**Comment by yohom** [comment]
可以加，最好提供下两端的对应的api文档链接，这样实现起来比较快，节省你我的时间😁。

**Comment by dreamCC** [comment]
这个好像是sdk中好像是没有现成的方法。Android官网地址（https://lbs.amap.com/api/android-sdk/guide/draw-on-map/draw-marker），iOS官网地址（https://lbs.amap.com/api/ios-sdk/guide/draw-on-map/draw-marker）。但是我觉得可能没必要像官网那样完全自定义，只需要自定义弹出的泡泡（title和snippet）就行了，像iOS中MAAnnotationView的customCalloutView属性添加个点击事件应该就行了。
当然您忙的话，可以放一放，我这边改了下实现方式😁。

**Comment by cavanlee** [comment]
点击title同样可以有相应的点击事件回调？ 
关于该需求有实现吗？

**Comment by dreamCC** [comment]
额  这个需求只能等作者更新了。如果时间充足，可以自己写个。

**Comment by yohom** [comment]
`0.12.3`已经实现该方法`setInfoWindowClickListener`.
