### ISSUE TITLE
zoomLevel,showCompass不起作用

### ISSUE THREAD

**Issue by GAONING-abc** [fluttify-project/amap_map_fluttify#48]
**插件版本**最新版（^0.5.3+d62f0ad）

**遇到bug的平台(Android/iOS)** ios模拟器上，android还没有测试

**描述bug**根据插件Readme文件上描述
 AmapView(
      // 是否显示室内地图
      showIndoorMap: true,
      // 地图类型
      mapType: MapType.Standard,
      // 地图语言
      language: Language.Chinese,
      // 是否显示交通情况
      showTraffic: true,
      // 是否显示缩放控件
      showZoomControl: true,
      // 是否显示指南针控件
      showCompass: true,
      // 是否显示定位控件
      showLocateControl: true,
      // 是否显示比例尺控件
      showScaleControl: true,
      // 是否使能缩放手势
      zoomGesturesEnabled: true,
      // 是否使能滚动手势
      scrollGesturesEnabled: true,
      // 是否使能旋转手势
      rotateGestureEnabled: true,
      // 是否使能倾斜手势
      tiltGestureEnabled: true,
      // 是否使能所有手势
      allGesturesEnabled: true,
      // 缩放级别
      zoomLevel: 10, 
      // 中心点坐标
      centerCoordinate: LatLng(39, 120),
      // 标记
      markers: <MarkerOptions>[], 
      // 标识点击回调
      onMarkerClick: (Marker marker) {},
      // 地图点击回调
      onMapClick: (LatLng coord) {},
      // 地图拖动回调
      onMapDrag: (MapDrag drag) {},
      // 地图创建完成回调
      onMapCreated: (controller) async {
        // requestPermission是权限请求方法, 需要你自己实现 
        // 如果不知道怎么处理, 可以参考example工程的实现
        if (await requestPermission()) {
          await controller.showMyLocation(true);
        }
      },
    )
这样写之后没有改变视图的缩放比例

**Comment by yohom** [comment]
我试了如下代码
```dart
AmapView(
  zoomLevel: 20,
  showCompass: false,
  onMapCreated: (controller) async {
    _controller = controller;
    if (await requestPermission()) {
      await controller.showMyLocation(false);
    }
  },
)
```
是能达到期望的效果的，建议你用真机试一下。
