### ISSUE TITLE
Marker是否可以加方向，另外是否可以增加轨迹移动功能

### ISSUE THREAD

**Issue by seavman** [fluttify-project/amap_map_fluttify#49]
**功能描述**
Marker的 方向安卓有现成的方法setRotateAngle，苹果端不知道怎么加。另外就是有个原生的实现，轨迹移动，对应地址
安卓：https://lbs.amap.com/api/android-sdk/guide/draw-on-map/smooth-move
IOS: https://lbs.amap.com/api/ios-sdk/guide/draw-on-map/smooth-move

**Comment by yohom** [comment]
`0.5.4`版本加入了旋转方向和锚点的参数。轨迹移动另外开一个issue吧，这个issue我先关了。 @seavman
