### ISSUE TITLE
您好 麻烦是否可以集成高德的轨迹移动功能

### ISSUE THREAD

**Issue by seavman** [fluttify-project/amap_map_fluttify#50]
**功能描述**
高德轨迹移动，根据输入的关键点和时间参数，实现点的平滑移动效果。

**Native端对应字段/方法**
可以参见高德SDK文档
安卓：https://lbs.amap.com/api/android-sdk/guide/draw-on-map/smooth-move
IOS: https://lbs.amap.com/api/ios-sdk/guide/draw-on-map/smooth-move

**Comment by Gaoxichao** [comment]
我也需要这个功能，希望作者可以加进来

**Comment by yohom** [comment]
参考 https://github.com/fluttify-project/amap_map_fluttify/issues/63#issuecomment-555955044 。

**Comment by yohom** [comment]
与 #63 重复，先关闭了。
