### ISSUE TITLE
安卓端闪退

### ISSUE THREAD

**Issue by WxxShirley** [fluttify-project/amap_map_fluttify#51]
**插件版本**

**遇到bug的平台(Android/iOS)**

**描述bug**

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by WxxShirley** [comment]
作者你好，iOS端我之前一直使用的是你之前开发的插件，正常运行。可是安卓端在这个新插件上却闪退（我已经按照高德地图开发者文档中配置、正确申请了key），（我仅仅做了一个展示地图的test demo）请问这是怎么回事？

**Comment by yohom** [comment]
奔溃日志可否发一份？

**Comment by WxxShirley** [comment]
e: /Users/wu/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/amap_base-0.3.5/android/src/main/kotlin/me/yohom/amapbase/map/MapHandlers.kt: (185, 1): Object 'OpenOfflineManager' is not abstract and does not implement abstract member @UiThread public abstract fun onMethodCall(@NonNull p0: MethodCall, @NonNull p1: MethodChannel.Result): Unit defined in me.yohom.amapbase.MapMethodHandler
e: /Users/wu/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/amap_base-0.3.5/android/src/main/kotlin/me/yohom/amapbase/map/MapHandlers.kt: (191, 5): 'onMethodCall' overrides nothing
e: /Users/wu/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/amap_base-0.3.5/android/src/main/kotlin/me/yohom/amapbase/search/SearchHandlers.kt: (286, 1): Object 'DistanceSearchHandler' is not abstract and does not implement abstract member @UiThread public abstract fun onMethodCall(@NonNull p0: MethodCall, @NonNull p1: MethodChannel.Result): Unit defined in me.yohom.amapbase.SearchMethodHandler
e: /Users/wu/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/amap_base-0.3.5/android/src/main/kotlin/me/yohom/amapbase/search/SearchHandlers.kt: (287, 5): 'onMethodCall' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':amap_base:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2sGradle task assembleDebug failed with exit code 1

**Comment by yohom** [comment]
你这个是amap_base的啊，那个不维护了，跟这个仓库没关系。issue我关了。

**Comment by WxxShirley** [comment]
不好意思刚才没注意，因为昨晚试了这个run不起来后又试了原来的那个。刚才发送崩溃日志的时候没有注意。
下面是运行这个插件后的崩溃日志，麻烦您看一下：
I/ap_memo_androi( 4991): Waiting for a blocking GC ProfileSaver
I/Choreographer( 4991): Skipped 38 frames!  The application may be doing too much work on its main thread.
I/ap_memo_androi( 4991): Background concurrent copying GC freed 7519(800KB) AllocSpace objects, 3(60KB) LOS objects, 49% free, 2189KB/4378KB, paused 1.767ms total 619.518ms
I/ap_memo_androi( 4991): WaitForGcToComplete blocked ProfileSaver on ClassLinker for 6.991ms
D/eglCodecCommon( 4991): setVertexArrayObject: set vao to 0 (0) 1 0
W/Gralloc3( 4991): allocator 3.x is not supported
D/EGL_emulation( 4991): eglMakeCurrent: 0xdda1c6c0: ver 3 0 (tinfo 0xd257ebb0)
D/EGL_emulation( 4991): eglMakeCurrent: 0xe8b7f760: ver 3 0 (tinfo 0xe8b98f10)
D/eglCodecCommon( 4991): setVertexArrayObject: set vao to 0 (0) 10 0
D/EGL_emulation( 4991): eglMakeCurrent: 0xdda1c6c0: ver 3 0 (tinfo 0xd257ebb0)
I/flutter ( 4991): fluttify-dart: com.amap.api.maps.MapView@0::onCreate([])
D/fluttify-java( 4991): fluttify-java: com.amap.api.maps.MapView@0::onCreate(Bundle[{}])
D/EGL_emulation( 4991): eglMakeCurrent: 0xdda1c6c0: ver 3 0 (tinfo 0xd257ebb0)
D/        ( 4991): HostConnection::get() New Host Connection established 0xbacb7450, tid 5063
D/        ( 4991): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_dma_v1 ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0
D/EGL_emulation( 4991): eglCreateContext: 0xd2549700: maj 3 min 0 rcv 3
D/EGL_emulation( 4991): eglMakeCurrent: 0xd2549700: ver 3 0 (tinfo 0xbe6c3a70)
I/flutter ( 4991): fluttify-dart: com.amap.api.maps.MapView@0::getMap([])
F/libc    ( 4991): Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xe8d4bcf1 in tid 5063 (GLThread 343), pid 4991 (ap_memo_android)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QPP6.190730.005.B1/5775370:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2019-11-15 09:22:53+0800
pid: 4991, tid: 5063, name: GLThread 343  >>> com.example.map_memo_android <<<
uid: 10130
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xe8d4bcf1
    eax 3f0c37d1  ebx e91d16b8  ecx a9c44000  edx a9f8e691
    edi a9c88500  esi e8d4bcf1
    ebp b00f0588  esp b00f057c  eip a9f8e893
backtrace:
      #00 pc 0034a893  /data/app/com.example.map_memo_android-7WVHKloems0-2beijP-xgg==/lib/x86/libAMapSDK_MAP_v6_9_2.so (BuildId: 6eea34649a851d0b2de5004519545c844f9e3493)
Lost connection to device.
Exited (sigterm)

**Comment by yohom** [comment]
用真机测试。

**Comment by WxxShirley** [comment]
好的，谢谢🙏！！

**Comment by y692807** [comment]
参考
https://yrom.net/blog/2019/04/24/flutter-run-lost-libflutter-so-when-using-abiFilters/
