### ISSUE TITLE
模拟器上报认证错误 地图不显示， 真机白屏地图和报错信息都不显示。

### ISSUE THREAD

**Issue by Maconzhang** [fluttify-project/amap_map_fluttify#52]
**插件版本**
amap_map_fluttify: ^0.5.4+d2eb645
**遇到bug的平台(Android/iOS)**
ios
**描述bug**
![image](https://user-images.githubusercontent.com/20869112/68916826-9e4a7e80-07a2-11ea-8cf4-b6d1adceb0c5.png)

**复现步骤**
[AMapFoundationKit][Info] : 错误信息：The certificate for this server is invalid. You might be connecting to a server that is pretending to be “restapi.amap.com” which could put your confidential information at risk.
**期望行为**
显示地图
**截图**

**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.37.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by yohom** [comment]
<img width="476" alt="Screen Shot 2019-11-15 at 12 29 33" src="https://user-images.githubusercontent.com/10418364/68917070-9ccd8600-07a3-11ea-986f-d50e44097d78.png">

**Comment by Maconzhang** [comment]
![image](https://user-images.githubusercontent.com/20869112/68986678-ab2ba880-085c-11ea-9a3d-25eb91e6a7dd.png)
flutter sdk 更新过后一直这样？
flutter doctor:
![image](https://user-images.githubusercontent.com/20869112/68986684-c39bc300-085c-11ea-8894-afd6226e5c35.png)

**Comment by yohom** [comment]
插件会以`stable`分支为基准开发，建议你还是切到`stable`分支去测试。

**Comment by Maconzhang** [comment]
![image](https://user-images.githubusercontent.com/20869112/68987927-395a5b80-086a-11ea-837c-47c20158043f.png)
stable 分支上有这个奇怪的问题。
我按google 修改
https://stackoverflow.com/questions/58091905/why-to-fix-frameworks-flutter-framework-permission-denied-while-building-ios
这个并没有用。
有什么办法解决嘛？

**Comment by yohom** [comment]
我也不是很清楚，没遇到过。这个issue不属于当前插件范围内了，我关闭issue了。
