### ISSUE TITLE
安卓真机无法显示地图

### ISSUE THREAD

**Issue by WxxShirley** [fluttify-project/amap_map_fluttify#54]
**插件版本**
amap_map_fluttify: ^0.5.4

**遇到bug的平台(Android/iOS)**
Android真机 Nexus5
 
**描述bug**
做了一个展示地图的demo，真机上地图视图空白，无法显示
output为：
Launching lib/main.dart on Nexus 5 in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
E/PlatformViewsController(10665): Trying to use platform views with API 19, required API level is: 20

**Comment by yohom** [comment]
报错信息已经说的很明白了`Trying to use platform views with API 19, required API level is: 20`.

**Comment by WxxShirley** [comment]
不好意思这里我不太明白，我已经在终端使用了flutter upgrade指令，然后这个插件也使用的是最新的版本。请问要怎么改呢？

**Comment by yohom** [comment]
`amap_map_fluttify`使用了Flutter的`PlatformView`，`PlatformView`最低在**Api Level 20**的设备上运行，而你的设备Api Level为19。

**Comment by WxxShirley** [comment]
明白了，谢谢
