### ISSUE TITLE
调用setCenterCoordinate方法时能否保持zoom不变

### ISSUE THREAD

**Issue by yanqiqi1996** [fluttify-project/amap_map_fluttify#55]
描述：
1. 地图自带的定位按钮点击后会正确定位，并且不改变zoom
2.用setCenterCoordinate方法模拟这一行为的时候（android的在右上角，想改到左下角），在不传zoom参数的时候不会保持zoom不变

期望：调用setCenterCoordinate，在不传zoomLevel时保持地图缩放不变

**Comment by yohom** [comment]
@yanqiqi1996 刚上传`0.5.5`版本，去掉了`zoomLevel`的默认值，如果没有传入就使用当前的`zoomLevel`，没有完整测试代码，但是问题应该不大，你试下，如果有问题再反馈。
