### ISSUE TITLE
【feat】 添加海量点和点聚合的功能

### ISSUE THREAD

**Issue by Maconzhang** [fluttify-project/amap_map_fluttify#56]
**功能描述**
希望解决海量marker的性能问题：
1.添加点聚合的功能 【 https://lbs.amap.com/dev/demo/cluster-marker#Android】
2.添加海量点的功能 【https://lbs.amap.com/api/android-sdk/guide/draw-on-map/mass-points-overlay/?sug_index=0】
**Native端对应字段/方法**

**Comment by yohom** [comment]
当前issue已经被拆分为 #143 和 #144 .
