### ISSUE TITLE
Android打release包运行以后showZoomControl = false无效

### ISSUE THREAD

**Issue by KangYee** [fluttify-project/amap_map_fluttify#58]
**插件版本**
amap_map_fluttify: 0.5.6

**遇到bug的平台(Android/iOS)**
Android

**描述bug**
Android打release包运行以后`showZoomControl = false`无效，打debug包无此问题
无论是在初始参数中设置还是直接调用方法设置均无效果

**复现步骤**
1.在初始参数中
```
AmapView(
  zoomLevel: 15,
  showZoomControl: false,
  onMapCreated: (controller) => {}
)
```
2.打开地图后发现缩放按钮依然存在

**期望行为**
`showZoomControl = false` 应该不显示缩放按钮

**Comment by yohom** [comment]
`0.6.0`版本的所有回调都返回`Future`，并且调用时都加了`await`确保调用顺序，你试下还有没有你说的情况。

**Comment by KangYee** [comment]
经测试，已无此问题
