### ISSUE TITLE
marker 设置问题

### ISSUE THREAD

**Issue by yshye** [fluttify-project/amap_map_fluttify#59]
**插件版本**
0.5.4+d2eb645

**遇到bug的平台(Android/iOS)**
Android

**描述bug**
在设置 markers 时，若不设置`iconUri`，则不会显示标记。
同样在controller中设置也是一样的问题。

**复现步骤**

```dart
AmapView(
            language: Language.Chinese,
            showCompass: true,
            scrollGesturesEnabled: false,
            markers: [
             MarkerOption(
                    latLng: LatLng(31,121),
                    title:  '标题',
                    snippet:  '副标题',
//                    iconUri: Uri.parse(path),
//                    draggable: false,
//                    imageConfig: createLocalImageConfiguration(context),
                    ),
            ],
            centerCoordinate: LatLng(31, 121),
            zoomLevel: 14,
            onMapCreated: (_) {}),
```
**期望行为**

未设置iconUri时，也可以显示标记。可以用默认图标，默认图标可以在初始化时进行配置。

**截图**

**flutter doctor**

**Comment by yohom** [comment]
1. 构造器参数情况下，我复现了这个问题，但是暂时不知道怎么解决，在调用`addMarkers`之后原生端给我返回了`null`. 
2. 使用controller时正常显示了SDK内置的图片。
3. 我把`onMapCreated`改成了返回`Future`，在调用初始化参数前先确保`onMapCreated`执行完成，但是没有解决这个问题，还需要再看一下。

**Comment by Maconzhang** [comment]
MarkerOption可以加一个参数添加marker上文字或者可以iconUri 可以使用自定义的view吗？
类似安卓的markers上添加文字的做法。
![image](https://user-images.githubusercontent.com/20869112/69135719-87828f80-0af4-11ea-9523-fd34e084b481.png)
还有 MarkerOption中imageConfig 的bundle 作用不是很理解？

**Comment by yohom** [comment]
@Maconzhang 自定义View目前实现不了，这是Flutter渲染机制的限制，必须真实渲染在屏幕上的widget才能转换成对应的图片数据。另外关于`imageConfig`参考 https://github.com/fluttify-project/amap_map_fluttify/issues/15#issuecomment-554992601 .

**Comment by yohom** [comment]
@Maconzhang 目前还是建议直接调用 `createLocalImageConfiguration ` 方法来创建`ImageConfiguration`.
