### ISSUE TITLE
单纯使用amap_map_fluttify如何获取定位信息？

### ISSUE THREAD

**Issue by WingedCat** [fluttify-project/amap_map_fluttify#6]
单纯使用amap_map_fluttify如何获取定位信息？

**Comment by yohom** [comment]
有相关高德api文档吗，有的话就可以，没有的话就不行。

**Comment by WingedCat** [comment]
谢谢回复，还有一个问题，就是使用此插件显示我的定位点后如果我想移动到其他地方，它会强制性的移动回中心点，这个改如何设置，或者需要修改哪里的代码呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"小山"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月28日(星期一) 上午7:28
收件人:&nbsp;"fluttify-project/amap_map_fluttify"<amap_map_fluttify@noreply.github.com&gt;;
抄送:&nbsp;"带翅膀的猫 🐱"<2233749193@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fluttify-project/amap_map_fluttify] 单纯使用amap_map_fluttify如何获取定位信息？ (#6)




有相关高德api文档吗，有的话就可以，没有的话就不行。

**Comment by KossFun** [comment]
同求

**Comment by wechatobok** [comment]
mapController.showMyLocation(false);

**Comment by WingedCat** [comment]
我知道这个方法，可是置为false我又无法定位到自己所在位置了呀，地图打开就是北京了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wechatobok"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月28日(星期一) 晚上6:38
收件人:&nbsp;"fluttify-project/amap_map_fluttify"<amap_map_fluttify@noreply.github.com&gt;;
抄送:&nbsp;"带翅膀的猫 🐱"<2233749193@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fluttify-project/amap_map_fluttify] 单纯使用amap_map_fluttify如何获取定位信息？ (#6)




mapController.showMyLocation(false);

**Comment by q869939686** [comment]
可以不强制移动回中心点吗？
