### ISSUE TITLE
体验优化

### ISSUE THREAD

**Issue by hu198021688500** [fluttify-project/amap_map_fluttify#62]
**功能描述**
现在创建地图的时候中心 坐标  和 缩放级别 是分两步，中间有个变化过程，能在创建的时候就一步到位么？
**Native端对应字段/方法**

**Comment by yohom** [comment]
`0.8.0`版本，引擎实现了对`PlatformView`构造器传参，`AmapView`的初始化参数会直接传入原生View的构造器，代替原先调用`AmapController`初始化的方式。你说的这个问题应该可以了，你试下吧。如果碰到问题再Reopen这个issue。
