### ISSUE TITLE
想问下作者轨迹功能有计划加进来吗？

### ISSUE THREAD

**Issue by Gaoxichao** [fluttify-project/amap_map_fluttify#63]
功能描述
高德轨迹移动，根据输入的关键点和时间参数，实现点的平滑移动效果。

Native端对应字段/方法
可以参见高德SDK文档
安卓：https://lbs.amap.com/api/android-sdk/guide/draw-on-map/smooth-move
IOS: https://lbs.amap.com/api/ios-sdk/guide/draw-on-map/smooth-move

**Comment by yohom** [comment]
轨迹功能android端的接口用到了泛型，`Fluttify`引擎目前对泛型支持还比较弱，只支持对列表的处理，所以这个功能暂时不会上了。

**Comment by aohanhe** [comment]
请问我现在有什么办法实现这个功能吗？现在项目必需用
