### ISSUE TITLE
支持swift的创建的flutter项目按目前配置，不能正常显示地图

### ISSUE THREAD

**Issue by jishaofeng89** [fluttify-project/amap_map_fluttify#64]
支持swift的创建的flutter项目按目前配置，不能正常显示地图
因此使用-i objc这样创建项目，可以正常显示地图

flutter create -i objc -a kotlin amap_fluttify_demo

-i swift创建的项目，在xcode报如下错误：

![image](https://user-images.githubusercontent.com/4972984/69205023-bc89f300-0b83-11ea-91e7-6674f2a57ed6.png)
显示地图是这样的：
![image](https://user-images.githubusercontent.com/4972984/69205057-d592a400-0b83-11ea-989b-3aaf42bf177e.png)

**Comment by date13** [comment]
大神出来解决一下呀,在线等

**Comment by yohom** [comment]
两个临时解决方案：
1. ios语言更换成objc；或
2. 手动拷贝AMap.bundle到xcode工程下，详见 https://lbs.amap.com/api/ios-sdk/guide/create-project/manual-configuration 第二步。

**Comment by jishaofeng89** [comment]
请参考：https://www.jianshu.com/p/88a4c8e98046

**Comment by pan365wang** [comment]
该方法确实可以解决ios不能显示地图的问题

**Comment by yohom** [comment]
`0.16.0`开始，使用pod远程依赖高德地图，使用swift创建工程时，需要注释掉Podfile中的`use_frameworks!`.
