### ISSUE TITLE
能否出一个地图的路线规划，加急

### ISSUE THREAD

**Issue by zhengzhuang95** [fluttify-project/amap_map_fluttify#65]
**功能描述**
输入起始位置坐标，在地图上规划出路线规划并显示当前路况
**Native端对应字段/方法**

**Comment by yohom** [comment]
你这个配合[amap_search_fluttify](https://github.com/fluttify-project/amap_search_fluttify)就行了。

**Comment by wangdongmeng** [comment]
你好，请问怎么把路线规划后的数据显示到地图上呢？我没有搞懂怎么整，求教，谢谢！

**Comment by yohom** [comment]
把amap_search的结果用AmapController.addPolylin()画到地图上。

**Comment by wangdongmeng** [comment]
大神，不好意思，还要请教个问题，Android端调用AmapSearch.searchDriveRoute()有问题，
日志：
W/System.err(15628): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
W/System.err(15628): 	at me.yohom.amap_search_fluttify.AmapSearchFluttifyPlugin$1.lambda$new$1267(AmapSearchFluttifyPlugin.java:41741)
W/System.err(15628): 	at me.yohom.amap_search_fluttify.-$$Lambda$AmapSearchFluttifyPlugin$1$mNioKxLSV3sF4Q6uBZnLKa9vBxo.call(Unknown Source:0)
W/System.err(15628): 	at me.yohom.amap_search_fluttify.AmapSearchFluttifyPlugin.onMethodCall(AmapSearchFluttifyPlugin.java:43858)
W/System.err(15628): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
W/System.err(15628): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
W/System.err(15628): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
W/System.err(15628): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(15628): 	at android.os.MessageQueue.next(MessageQueue.java:386)
W/System.err(15628): 	at android.os.Looper.loop(Looper.java:175)
W/System.err(15628): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
W/System.err(15628): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(15628): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
W/System.err(15628): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

IOS没问题。

**Comment by yohom** [comment]
具体的调用代码能否贴一下。

**Comment by wangdongmeng** [comment]
_trackList = List();
    LatLng latLng = LatLng(39.92166, 116.557107);
    _trackList.add(latLng);

    latLng = LatLng(39.9214, 116.560561);
    _trackList.add(latLng);

    latLng = LatLng(39.928474, 116.597013);
    _trackList.add(latLng);

    latLng = LatLng(39.928659, 116.596961);
    _trackList.add(latLng);

AmapView(
        zoomLevel: 6,
        showScaleControl: true,
        onMapCreated: (controller) async {
          _controller = controller;
          if (await requestPermission()) {
            await controller.showLocateControl(false);
            await controller.setZoomLevel(6);

            ///获取驾驶路线
            final routeResult = await AmapSearch.searchDriveRoute(
                from: _trackList[0],
                to: _trackList[_trackList.length - 1],
                passedByPoints: _trackList);

            List<LatLng> _trackPolyLine = List();
            //把结果使用addPolyline绘制到地图
            routeResult.drivePathList.then((value) async {
              List<DrivePath> drivePaths = value;
              print("drivePaths ---> " + drivePaths.toString());
              drivePaths.forEach((drivePath) async {
                drivePath.driveStepList.then((driveStepList) async {
                  List<DriveStep> driveSteps = driveStepList;
                  print("driveSteps ---> " + driveSteps.toString());
                  driveSteps.forEach((driveStep) async {
                    driveStep.polyline.then((polyLineValues) async {
                      print("polyLineValues ---> " + polyLineValues.toString());
                      _trackPolyLine.addAll(polyLineValues);

                      await _controller.addPolyline(PolylineOption(
                          latLngList: _trackPolyLine,
                          width: 10,
                          strokeColor: Colors.blue));
                    });
                  });
                });
              });
            });
}
}
);

您看下 ，谢谢

**Comment by wangdongmeng** [comment]
@yohom 我提供的代码，您看下， 是什么问题导致的呢 ？  谢谢

**Comment by wangdongmeng** [comment]
@yohom  麻烦您看下，有点急。非常感谢。
