### ISSUE TITLE
在IOS下任何设置都不起作用,只显示个地图

### ISSUE THREAD

**Issue by date13** [fluttify-project/amap_map_fluttify#66]
**插件版本**
0.6.0+c454dd5
**遇到bug的平台(Android/iOS)**
IOS 13.2.2
**描述bug**
之前用IOS swift的不显示地图,项目改成了objc的,然后地图可以显示了,但是设置
await _controller?.setCenterCoordinate(lat, lng);
 await _controller?.showMyLocation(true);
任何api接口都没有用,只显示个北京的地图
**复现步骤**

**期望行为**
api能起作用
**截图**

**flutter doctor**

**Comment by date13** [comment]
在andorid下是ok的

**Comment by date13** [comment]
有任何进展吗

**Comment by yohom** [comment]
你先跑一下example是否正常

**Comment by date13** [comment]
example在android下可以跑,没有啥问题,但是ios完全没有作用,永远只是显示个初始化地图

**Comment by NSOYA2000** [comment]
同遇到此问题

**Comment by yohom** [comment]
是模拟器还是真机？要用真机调试。

**Comment by NSOYA2000** [comment]
模拟器和真机，都永远显示在北京的初始化地图，将他的中心点坐标centerCoordinate更改到其他地方也没有反应，markers也标不出来 = =

**Comment by Wood-Water-Peng** [comment]
同问，Android真机只显示北京的初始化地图，调用api没有反应，大佬们怎么解决的？

**Comment by zhouqiangLilin** [comment]
有进展不，我现在也遇到这个问题了，  版本 0.17.1

**Comment by z759341385** [comment]
我也遇到了这个问题  有解决方法吗

**Comment by hidetag** [comment]
iOS 端一直有这个问题，机型和 iOS 版本看情况看心情，目前针对 iOS 的这种情况，我这边处理方式是将地图改为 WebView 实现。
Android 虽然没有这个问题，但应用在前后台切换期间有概率导致地图白屏

**Comment by SunLongbri** [comment]
你们解决了吗？我这边也出现在iOS端只显示地图，定位什么的都用不了。

**Comment by SunLongbri** [comment]
当前版本：amap_map_fluttify: ^0.20.0

**Comment by SunLongbri** [comment]
兄弟们，我的现象和你们的一样，我的已经解决了。解决方法是把你们的分支切回stable分支。

**Comment by hidetag** [comment]
楼上试试 iPhone 6S，我的 6S 没法用，一样有问题，7 以上就 OK 了

**Comment by SunLongbri** [comment]
你们可以看看环境是不是一样。
我当前用的是：iPhone 6 。版本：12.4.6.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

**Comment by SunLongbri** [comment]
上面的环境设置好，再把这些配置上去，运行不了了找我，我的QQ:1749236746.    

<key>io.flutter.embedded_views_preview</key>
    <string>YES</string>
    <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>定位</string>
    <key>NSLocationAlwaysUsageDescription</key>
    <string>定位</string>
    <key>NSLocationWhenInUseUsageDescription</key>
    <string>定位</string>

**Comment by licc** [comment]
这个问题任然存在amap_map_fluttify: ^0.22.2
swift +java   在iphone7上只显示一个地图，   await _controller?.showMyLocation(MyLocationOption(
                      myLocationType: MyLocationType.Locate,
                    ));
无效

**Comment by Antduo** [comment]
这个问题当我使用 0.23.1 版本出现了, 当把插件升级到 0.23.2, 并执行 flutter clean 命令, 重新编译iOS代码就可以了
