### ISSUE TITLE
您好，能否增加一个地图截屏功能？

### ISSUE THREAD

**Issue by JackZhang1994** [fluttify-project/amap_map_fluttify#67]
能否增加一个地图截屏功能？我试过用Flutter的RepaintBoundary截屏，可是图片中的地图是显示不出来的，希望作者能够把API添加进去，谢谢。急需

**Comment by JackZhang1994** [comment]
> 能否增加一个地图截屏功能？我试过用Flutter的RepaintBoundary截屏，可是图片中的地图是显示不出来的，希望作者能够把API添加进去，谢谢。急需

补：
API链接：
Android：https://lbs.amap.com/api/android-sdk/guide/interaction-with-map/map-screenshot
iOS：https://lbs.amap.com/api/ios-sdk/guide/interaction-with-map/map-screenshot

**Comment by yohom** [comment]
`0.6.1`版本，已经加入`screenShot`方法。更新一下，如果你`flutter packages get`不到的话就先依赖github。

**Comment by JackZhang1994** [comment]
> `0.6.1`版本，已经加入`screenShot`方法。更新一下，如果你`flutter packages get`不到的话就先依赖github。

好的，谢谢
