### ISSUE TITLE
打包apk报错，提示amap_controller.dart有bug

### ISSUE THREAD

**Issue by lyy1005664097** [fluttify-project/amap_map_fluttify#69]
flutter 版本：Flutter version 1.12.8-pre.14
插件版本：0.5.6
bug描述：
/amap_map_fluttify-0.5.6+d2eb645/lib/src/dart/amap_controller.dart:1222:30: Error: Getter not found: 'suspending'.
      case AppLifecycleState.suspending:

打开amap_controller.dart发现如下方法：
 @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    debugPrint('didChangeAppLifecycleState: $state');
    switch (state) {
      case AppLifecycleState.resumed:
        _androidController?.onResume();
        break;
      case AppLifecycleState.inactive:
        break;
      case AppLifecycleState.paused:
        _androidController?.onPause();
        break;
      case AppLifecycleState.suspending:   //此处有bug
        break;
    }
  }

bug产生原因：枚举AppLifecycleState中没有suspending
enum AppLifecycleState {

  resumed,

  inactive,

  paused,

  detached,
}

**Comment by yohom** [comment]
我本地的测试环境为stable分支，插件开发也会以stable分支为准。新版本的flutter需要等到并入stable之后再做支持。

**Comment by lyy1005664097** [comment]
好的.
我打包的时候把这两句注释掉就好了，应该对我的app没什么影响
//case AppLifecycleState.suspending: 
//break;

**Comment by yohom** [comment]
从`0.11.0`开始Flutter环境已经提升为`1.12.13`，这个问题应该已经不存在了。
