### ISSUE TITLE
引入amap_map_fluttify编译报错

### ISSUE THREAD

**Issue by q869939686** [fluttify-project/amap_map_fluttify#7]
![image](https://user-images.githubusercontent.com/29123332/67663204-ed6d7280-f99f-11e9-807a-9886edfe224a.png)
引入高德地图时候编译报错

**Comment by yohom** [comment]
这个问题最新的引擎已经处理，等下一波版本吧。目前fluttify引擎变动比较频繁，如果出什么问题就试着`flutter packages upgrade`强制更新一下，一些问题可能会在`amap_core_fluttify`或`foundation_fluttify`中已经处理.

**Comment by q869939686** [comment]
谢谢回复，了解了

**Comment by yohom** [comment]
`flutter packages upgrade`一下，最新版本应该已经修复了 @q869939686
