### ISSUE TITLE
Ios 13.2.3 地图显示不出来

### ISSUE THREAD

**Issue by pan365wang** [fluttify-project/amap_map_fluttify#70]
**插件版本**

**遇到bug的平台(Android/iOS)**
Ios
**描述bug**
Ios 13.2.3 地图显示不出来
![A6F04329-74B8-437D-BA39-C7CB4F72F1C6](https://user-images.githubusercontent.com/11287776/69497094-08d28b80-0f14-11ea-8e8a-78e96a6e363c.png)

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
先参考下置顶的issue。

**Comment by liuyanqiang1989** [comment]
我是IOS 采用object-c开发的，也是运行的黑屏， 目前置顶的issue，并不能解决这个问题。希望作者能发现这个问题，更新解决下这个bug。感谢🙏

**Comment by yohom** [comment]
你运行example工程能正常显示吗

**Comment by liuyanqiang1989** [comment]
> 你运行example工程能正常显示吗

example 可以正常显示，但是接入自己的项目，地图就是黑乎乎的一片，跟楼上兄弟截图一样的效果。

**Comment by yohom** [comment]
那肯定就是配置的问题了，Info.plist配置过了吗

**Comment by liuyanqiang1989** [comment]
> 那肯定就是配置的问题了，Info.plist配置过了吗

info.plist 的3个配置 也配置了

**Comment by pan365wang** [comment]
https://github.com/fluttify-project/amap_map_fluttify/issues/64 参考issues确实能解决ios不显示的问题
