### ISSUE TITLE
根据地图边界，自定义不同城市的颜色背景

### ISSUE THREAD

**Issue by liuyanqiang1989** [fluttify-project/amap_map_fluttify#72]
**功能描述**
希望大佬 能增加个根据地图边界，显示不同城市不同的颜色。感谢
**Native端对应字段/方法**

**Comment by yohom** [comment]
`0.3.2`版本的`amap_search_fluttify`获取行政区划数据接口，已经加入了区域边界信息，你可以使用这些信息画多边形。
