### ISSUE TITLE
添加 经纬度坐标与屏幕像素坐标互转的相关方法

### ISSUE THREAD

**Issue by yshye** [fluttify-project/amap_map_fluttify#76]
**功能描述**
支持经纬度坐标与屏幕像素坐标互转。详见 [坐标转换](https://lbs.amap.com/api/android-sdk/guide/computing-equipment/coordinate-transformation)
**Native端对应字段/方法**

名称 | 说明
-- | --
AMap.getProjection().fromScreenLocation(android.graphics.Point paramPoint) | 根据转入的屏幕位置返回一个地图位置（经纬度）
AMap.getProjection().toScreenLocation(LatLng paramLatLng) | 返回一个从地图位置转换来的屏幕位置
AMap.getProjection().toOpenGLWidth(int screenWidth) | 返回一个屏幕宽度转换来的openGL 需要的宽度
AMap.getProjection().toOpenGLLocation(LatLng paramLatLng) | 返回一个从经纬度坐标转换来的opengles 需要的坐标

**Comment by yohom** [comment]
`0.8.3`版本实现了`fromScreenLocation`和`toScreenLocation`，剩下两个不打算实现了，感觉不会有人用。

**Comment by yshye** [comment]
👌
