### ISSUE TITLE
当marker在屏幕可见范围外生成时，自定义图标失效, 会变成默认的大头针样式！

### ISSUE THREAD

**Issue by IT-Ice** [fluttify-project/amap_map_fluttify#79]
**插件版本**

**遇到bug的平台(Android/iOS)** 只看了ios

**描述bug**

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
你插件什么版本？

**Comment by IT-Ice** [comment]
最新版和老版本都这样

**Comment by beydeng** [comment]
我也会遇见这个问题 
新版本老版本都是

**Comment by yohom** [comment]
跟 #99 重复，先关闭了。
