### ISSUE TITLE
当前位置的图标会默认改变！

### ISSUE THREAD

**Issue by IT-Ice** [fluttify-project/amap_map_fluttify#80]
**插件版本**

**遇到bug的平台(Android/iOS)** ios

**描述bug** 1、当设置了marker自定义图标后，当地图城市切换后，再回到”当前位置“，图标会变成 marker设置的图标； 2、当没有设置marker自定义图标，当地图城市切换后，再回到”当前位置“，图标会变成 默认的大头针样式。

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
你插件什么版本？

**Comment by IT-Ice** [comment]
最新版和老版本都这样

**Comment by yanqiqi1996** [comment]
没错我也遇到了这个bug，。。主要是ios，android 没有这个问题

**Comment by yohom** [comment]
跟 #99 重复，先关闭了。
