### ISSUE TITLE
显示蓝点方向指向

### ISSUE THREAD

**Issue by IT-Ice** [fluttify-project/amap_map_fluttify#82]
**功能描述** 显示当前位置蓝点的方向指向

**Native端对应字段/方法**   ios：r.showsHeadingIndicator = NO;///是否显示方向指示(MAUserTrackingModeFollowWithHeading模式开启)。默认为YES

**Comment by yohom** [comment]
这种比较简单的配置字段的需求，我建议你还是fork一份去自己改一下然后pr回来我合并一下就ok，地图的接口太多，靠我一个人要加也比较累 :)
