### ISSUE TITLE
执行flutter pub upgrade 后报错

### ISSUE THREAD

**Issue by theecn** [fluttify-project/amap_map_fluttify#85]
**插件版本**

**遇到bug的平台(Android/iOS)**
android
**描述bug**

**复现步骤**

**期望行为**

**截图**
![image](https://user-images.githubusercontent.com/22100544/69946525-b9e5b100-1526-11ea-9692-e47b8e961ec0.png)
**flutter doctor**
![image](https://user-images.githubusercontent.com/22100544/69946591-db469d00-1526-11ea-952d-cbba4bb2886f.png)

**Comment by theecn** [comment]
已确认不是由于安卓工具所造成

**Comment by theecn** [comment]
![image](https://user-images.githubusercontent.com/22100544/69947310-5eb4be00-1528-11ea-84d2-c1a20856c3ef.png)
版本号

**Comment by yohom** [comment]
参考一下 https://github.com/fluttify-project/amap_map_fluttify/issues/26#issuecomment-548693045 清除掉旧版本的插件。
