### ISSUE TITLE
关于 动态调整地图展示整屏Marker

### ISSUE THREAD

**Issue by KerryBai** [fluttify-project/amap_map_fluttify#90]
功能描述
可用于将所有动态加载的Annotation覆盖物（可以是车，也可以是任何带有经纬度坐标的事物）调整至同一屏幕中显示，便于用户概览。

可以参见高德SDK文档
安卓：https://lbs.amap.com/dev/demo/map-zoomtospan#Android
IOS: https://lbs.amap.com/dev/demo/map-zoomtospan#iOS

该功能和JS的setFitView方法一样，页面演示效果如下：
https://lbs.amap.com/api/javascript-api/example/marker/adaptive-show-multiple-markers

作者，辛苦啦~

**Comment by yohom** [comment]
`0.10.3`版本已加入此方法，`padding`参数两端效果不一致，详情看方法的注释文档。
