### ISSUE TITLE
IOS添加Marker显示不同类型的问题

### ISSUE THREAD

**Issue by yanglilizhang** [fluttify-project/amap_map_fluttify#92]
**插件版本**
老版本和新版本都有此问题
**遇到bug的平台(Android/iOS)**
IOS
**描述bug**
本来是用addMarkers方法根据服务返回的num的不同显示不同的颜色类型icon(Marker)的，
在android平台一直很好，但是IOS平台始终是只能显示一种颜色类型的icon(Marker)，你代码中有这样的描述：[目前iOS端所有的marker的icon和draggable参数都只能一样]，不知道这个问题何时解决，
于是用widget方式添加不同的布局，根据num的不同动态改变包裹不同类型icon的widget，IOS端仍然是只显示同一种类型Android端正常，想问下博主这两个问题是什么原因导致的，有没有处理方案，期待回复，谢谢！
**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
目前你可以尝试一下分批添加Marker方式（就是同种marker调用一次addMarkers）。

**Comment by yanglilizhang** [comment]
@yohom  在1.9.1稳定版本采用作者的分批加载的方式再IOS端解决了问题，但近期升级了稳定版本1.12.13+5，之前的分批加载的方式在IOS端失效。1.只要marker不在屏幕中加载，采用分批加载也会导致marker不能分批，并且有时偶现大头针样式的marker。使用版本：0.16.1+a3d4e61

**Comment by yohom** [comment]
0.17.3处理了这个问题，你试下，应该可以了。

**Comment by yanglilizhang** [comment]
@yohom 好的，家里没苹果电脑，我明天上班试下然后反馈你

**Comment by yanglilizhang** [comment]
问题已解决。
