### ISSUE TITLE
可以添加绘制线适配屏幕功能吗

### ISSUE THREAD

**Issue by q869939686** [fluttify-project/amap_map_fluttify#93]
**功能描述**
安卓和iOS绘制轨迹之后可以自动适配屏幕的显示范围
**Native端对应字段/方法**
Android
https://lbs.amap.com/dev/demo/path-smooth#Android
![image](https://user-images.githubusercontent.com/29123332/70222985-c451b600-1785-11ea-887d-b4a4c68161d6.png)

iOS
未知

**Comment by khkdz** [comment]
我也需要这个功能,等待,谢谢

**Comment by yohom** [comment]
@q869939686 @khkdz 你们要的是 https://github.com/fluttify-project/amap_map_fluttify/issues/90 一样的方法吗？可以试下`zoomToSpan`方法。

**Comment by yohom** [comment]
@q869939686 我看你提供的文档应该不是你描述的想要的方法吧？

**Comment by khkdz** [comment]
我试过#90的功能了,符合我的需求,谢谢
