### ISSUE TITLE
ios引用最新版本后，无法编译

### ISSUE THREAD

**Issue by pan365wang** [fluttify-project/amap_map_fluttify#94]
**插件版本**
  amap_location_fluttify: ^0.4.0+82a2243
  amap_map_fluttify: ^0.10.2+a1a3fff
  amap_search_fluttify: ^0.3.4+97873c8
**遇到bug的平台(Android/iOS)**
iOS
**描述bug**
无法编译， 

amap_controller.dart:1426:30: Error: Getter not found: 'suspending'.
case AppLifecycleState.suspending:

                                 ^^^^^^^^^^

    Compiler terminated unexpectedly.

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by yohom** [comment]
参考 https://github.com/fluttify-project/amap_map_fluttify/issues/91.
