### ISSUE TITLE
第一次调用controller.fromScreenLocation 报错

### ISSUE THREAD

**Issue by dsmjoy** [fluttify-project/amap_map_fluttify#95]
**插件版本**
0.10.2+a1a3fff

**遇到bug的平台(Android/iOS)**
Android

**描述bug**
在onMapCreated 回调里 第一次调用 controller.fromScreenLocation 报错, 如下: 

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(Attempt to invoke virtual method 'com.amap.api.maps.AMap com.amap.api.maps.MapView.getMap()' on a null object reference, null, null)
```

而关闭地图后, 再次进入, 就不报错了

具体调用如下: 

```
LatLng topLeft = await _controller.fromScreenLocation(Point(0, 0));
LatLng topRight = await _controller.fromScreenLocation(Point(screenWidth, 0));
LatLng bottomLeft = await _controller.fromScreenLocation(Point(0, screenHeight));
LatLng bottomRight = await _controller.fromScreenLocation(Point(screenWidth, screenHeight));

await _controller.addMarkers([MarkerOption(latLng: topLeft), MarkerOption(latLng: topRight), MarkerOption(latLng: bottomLeft), MarkerOption(latLng: bottomRight)]);
```
错误指向了 topRight 这一行,  topLeft那一行却不报错.  如果注释topRight 这一行, 后续的bottomLeft也会报错, 以此类推.   第二次进入,就不报错了.  重启app后, 再次复现.

另外如果只保留topLeft这一行,   错误又执向了  addMarkers  这一行.

关闭地图相关页面, 销毁地图,  重新进入,  不会有任何问题

**复现步骤**

**期望行为**

**截图**

**flutter doctor**

**Comment by hongliang211** [comment]
> **插件版本**
> 0.10.2+a1a3fff
> 
> **遇到bug的平台(Android/iOS)**
> Android
> 
> **描述bug**
> 在onMapCreated 回调里 第一次调用 controller.fromScreenLocation 报错, 如下:
> 
> ```
> [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(Attempt to invoke virtual method 'com.amap.api.maps.AMap com.amap.api.maps.MapView.getMap()' on a null object reference, null, null)
> ```
> 
> 而关闭地图后, 再次进入, 就不报错了
> 
> 具体调用如下:
> 
> ```
> LatLng topLeft = await _controller.fromScreenLocation(Point(0, 0));
> LatLng topRight = await _controller.fromScreenLocation(Point(screenWidth, 0));
> LatLng bottomLeft = await _controller.fromScreenLocation(Point(0, screenHeight));
> LatLng bottomRight = await _controller.fromScreenLocation(Point(screenWidth, screenHeight));
> 
> await _controller.addMarkers([MarkerOption(latLng: topLeft), MarkerOption(latLng: topRight), MarkerOption(latLng: bottomLeft), MarkerOption(latLng: bottomRight)]);
> ```
> 
> 错误指向了 topRight 这一行, topLeft那一行却不报错. 如果注释topRight 这一行, 后续的bottomLeft也会报错, 以此类推. 第二次进入,就不报错了. 重启app后, 再次复现.
> 
> 另外如果只保留topLeft这一行, 错误又执向了 addMarkers 这一行.
> 
> 关闭地图相关页面, 销毁地图, 重新进入, 不会有任何问题
> 
> **复现步骤**
> 
> **期望行为**
> 
> **截图**
> 
> **flutter doctor**

确实有这个问题  一旦用了fromScreenLocation函数  之后关于controller所有的操作都失效了 原因大概就是fromScreenLocation里面去获取地图实例失败  希望能尽快解决

**Comment by dsmjoy** [comment]
> `0.14.2`试下。

还是报一样的错. 用的最新当前版本 0.17.1+2721fb9  @yohom

**Comment by yohom** [comment]
> > `0.14.2`试下。
> 
> 还是报一样的错. 用的最新当前版本 0.17.4+59a3abb @yohom

可否试一下延迟1秒钟再调用`fromScreenLocation`方法？确认一下是否是因为地图还没有加载完成的原因。

**Comment by dsmjoy** [comment]
> > > `0.14.2`试下。
> > 
> > 
> > 还是报一样的错. 用的最新当前版本 0.17.4+59a3abb @yohom
> 
> 可否试一下延迟1秒钟再调用`fromScreenLocation`方法？确认一下是否是因为地图还没有加载完成的原因。

在 `onMapCreated` 里延迟了2s, 还是会报错.  但是报错指向了`setZoomLevel`这个方法. 
比较奇怪. 没发现共性在哪.
报错如下: 
`Unhandled Exception: PlatformException(com.amap.api.maps.model.Circle cannot be cast to com.amap.api.maps.MapView, null, null)`

指向这里
![image](https://user-images.githubusercontent.com/15439238/71793592-63651880-3078-11ea-8b3d-d85539df81c4.png)

**Comment by yohom** [comment]
我用最新版本`0.17.9`测试能够正常获取。测试代码:
```dart
AmapView(
              showZoomControl: false,
              maskDelay: Duration(milliseconds: 500),
              onMapCreated: (controller) async {
                _controller = controller;
                final latlng = _controller.fromScreenLocation(Point(250, 250));
                toast((await latlng).toString());
                if (await requestPermission()) {
//                  await controller.showMyLocation(true);
//                  final latLng = await _controller?.getLocation(
//                      delay: Duration(seconds: 1));
//                  toast('当前经纬度: ${latLng.toString()}');
                }
              },
            )
```

**Comment by dsmjoy** [comment]
你好, 现在不是fromScreenLocation的问题了. 就是启动后第一次进入地图一定报错, 退出地图后再进, 就不报错了. 

报错如下: 
```
E/flutter (12116): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(com.amap.api.maps.model.Circle cannot be cast to com.amap.api.maps.MapView, null, null)
```
指向了这里

```
E/flutter (12116): #0      AmapController.setZoomLevel (package:amap_map_fluttify/src/dart/amap_controller.dart:472:5)
```
还不确定是setZoomLevel的错还是其他api导致的错误
