### ISSUE TITLE
addMarker 添加的widget里包含图片, 图片无法显示

### ISSUE THREAD

**Issue by dsmjoy** [fluttify-project/amap_map_fluttify#97]
**插件版本**
0.10.2+a1a3fff

**遇到bug的平台(Android/iOS)**
Android

**描述bug**
addMarker 添加的widget里包含图片, 图片无法显示

用 widget 做 marker  ,  如果widget包含图片,  图片有概率显示不了.   是不是底层在做widget转图片的时候,  图片还没加载完毕,  会导致这个问题.   无论网络图片还是asset图片都会有问题.    

目前单纯用iconUri  还不够,  因为需要在Marker图片周围做一些装饰,  并且iconUri目前设置不了图片大小, 所以需要使用widget.   这个问题有办法从底层解决吗 ?  或者有没有其他办法规避?

**Comment by yohom** [comment]
@dsmjoy 根据 https://github.com/flutter/flutter/issues/43085 这个issue以及 https://github.com/flutter/flutter/issues/43085#issuecomment-553731602 这条评论，应该可以认为下个stable版本flutter（预计就是12月11号的`Flutter Interact`上发布）会修复这个问题，届时会进行适配，并观察结果。

**Comment by Maconzhang** [comment]
这个问题有修复吗？ 我看在插件amap_map_fluttify: ^0.17.5的版本还是有类似的问题， 第一次进入有概率图片无法显示，第二次情况会好很多.

**Comment by yohom** [comment]
这个跟flutter有关，插件只能依赖flutter的更新来处理这个问题。

**Comment by view-man** [comment]
这个问题修复了吗

**Comment by yohom** [comment]
可以在地图页面，使用precacheImage(:imageProvider:context)方法先把图片加载完成，再去添加marker。
